"""Generate the preview's static language table using existing project dependencies.

Run from the repository root, then format language_flags_data.js with Prettier.
No network access or new runtime dependencies are needed.
"""

import json
from pathlib import Path

import langcodes
import pycountry
from babel import Locale
from babel.core import UnknownLocaleError, get_global

ROOT = Path(__file__).resolve().parents[1]
FLAGS = ROOT / "web_ui/static/img/flags"
OUTPUT = ROOT / "web_ui/static/js/language_flags_data.js"
REPRESENTATIVES = {
    "en": "gb",
    "pt": "pt",
    "ca": "es-ct",
    "eu": "es-pv",
    "gl": "es-ga",
    "cy": "gb-wls",
    "gd": "gb-sct",
    "cmn": "cn",
    "tw": "gh",
    "cnr": "me",
}


def main() -> None:
    locales = [Locale(name) for name in ("en", "pt", "fr")]
    likely = get_global("likely_subtags")
    languages = []
    supported = set()
    for language in sorted(pycountry.languages, key=lambda item: item.alpha_3):
        code = getattr(language, "alpha_2", language.alpha_3)
        parsed = langcodes.get(code)
        canonical = parsed.language
        # Language families, special codes and constructed languages have no
        # single representative country. Never maximize an unknown code.
        if language.scope not in {"I", "M"} or language.type == "C":
            continue
        if code not in locales[0].languages and language.alpha_3 not in locales[0].languages and code not in REPRESENTATIVES and not parsed.territory:
            continue
        territory = (parsed.territory or (likely.get(canonical) or likely.get(code) or "").split("_")[-1]).lower()
        flag = REPRESENTATIVES.get(code, territory)
        if not (FLAGS / f"{flag}.svg").is_file():
            continue
        aliases = {code, language.alpha_3, language.name}
        # A regional language must not override its broader language's alias
        # (e.g. Dari/prs -> fa-AF must not replace Persian/fa -> Iran).
        if not parsed.territory:
            aliases.add(canonical)
        for key in ("bibliographic", "common_name", "inverted_name"):
            if value := getattr(language, key, None):
                aliases.add(value)
        for locale in locales:
            if name := locale.languages.get(code) or locale.languages.get(language.alpha_3):
                aliases.add(name)
        try:
            native = Locale.parse(code)
            if name := native.languages.get(code):
                aliases.add(name)
        except ValueError, LookupError, UnknownLocaleError:
            pass
        languages.append([code, flag, *sorted(aliases)])
        supported.add(code)

    regions = []
    for country in sorted(pycountry.countries, key=lambda item: item.alpha_2):
        code = country.alpha_2.lower()
        aliases = {code, country.name}
        for key in ("common_name", "official_name"):
            if value := getattr(country, key, None):
                aliases.add(value)
        for locale in locales:
            if name := locale.territories.get(country.alpha_2):
                aliases.add(name)
        regions.append([code, *sorted(aliases)])
    regions.append(["xk", "xk", "Kosovo"])
    scripts = []
    for tag, expanded in sorted(likely.items()):
        parts = tag.split("_")
        flag = expanded.split("_")[-1].lower()
        if len(parts) == 2 and len(parts[1]) == 4 and parts[0] in supported and (FLAGS / f"{flag}.svg").is_file():
            scripts.append([tag.replace("_", "-").lower(), flag])
    data = {"languages": languages, "regions": regions, "scripts": scripts}
    OUTPUT.write_text(
        "// Generated by scripts/generate_webui_language_flags.py; do not edit.\n"
        "// CLDR data: Unicode license in static/img/flags/UNICODE-LICENSE.\n"
        "// ISO names/aliases: pycountry LGPL 2.1; see static/img/flags/PYCOUNTRY-LICENSE and PYCOUNTRY-COPYRIGHT.\n"
        "window.UAPreviewLanguageFlagData = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Generated {len(languages)} languages, {len(regions)} territories and {len(scripts)} script variants.")


if __name__ == "__main__":
    main()
