ENG_TO_PTBR_GENRE_MAP: dict[str, str] = {
    "action & adventure": "ação e aventura",
    "action": "ação",
    "adventure": "aventura",
    "animation": "animação",
    "arcade": "arcade",
    "biography & autobiography": "biografia e autobiografia",
    "board game": "tabuleiro",
    "board": "tabuleiro",
    "card": "cartas",
    "casual": "casual",
    "classic": "clássico",
    "comedy": "comédia",
    "crime": "crime",
    "documentary": "documentário",
    "drama": "drama",
    "driving": "corrida",
    "educational": "educativo",
    "family & relationships": "família e relacionamentos",
    "family": "família",
    "fantasy": "fantasia",
    "fiction": "ficção",
    "fighting": "luta",
    "hack and slash": "ação",
    "hack and slash/beat 'em up": "ação",
    "history": "história",
    "horror": "terror",
    "indie": "indie",
    "juvenile fiction": "ficção juvenil",
    "kids": "infantil",
    "mmo": "mmo",
    "moba": "moba",
    "music": "musical",
    "mystery": "mistério",
    "philosophy": "filosofia",
    "platform": "plataforma",
    "platformer": "plataforma",
    "point-and-click": "aventura",
    "psychological": "psicológico",
    "psychology": "psicologia",
    "puzzle": "puzzle",
    "racing": "corrida",
    "real time strategy (rts)": "rts",
    "real time strategy": "rts",
    "reality": "reality show",
    "religion": "religião",
    "rhythm": "musical",
    "role-playing (rpg)": "rpg",
    "role-playing": "rpg",
    "romance": "romance",
    "rpg": "rpg",
    "rts": "rts",
    "sandbox": "sandbox",
    "sci-fi & fantasy": "ficção científica e fantasia",
    "science fiction": "ficção científica",
    "science": "ciência",
    "self-help": "autoajuda",
    "shooter": "fps",
    "simulation": "simulação",
    "simulator": "simulação",
    "slice of life": "cotidiano",
    "soap": "novela",
    "social science": "ciências sociais",
    "sport": "esportes",
    "sports": "esportes",
    "strategy": "estratégia",
    "survival": "sobrevivência",
    "tactical": "estratégia",
    "thriller": "suspense",
    "turn-based strategy (tbs)": "estratégia",
    "turn-based strategy": "estratégia",
    "tv movie": "telefilme",
    "virtual reality": "rv",
    "visual novel": "aventura",
    "vr": "rv",
    "war": "guerra",
    "western": "faroeste",
    "young adult fiction": "ficção jovem adulto",
}
