import re

ENG_TO_PTBR_GENRE_MAP: dict[str, str] = {
    "action & adventure": "ação e aventura",
    "action": "ação",
    "adventure": "aventura",
    "animation": "animação",
    "arcade": "arcade",
    "biography & autobiography": "biografia e autobiografia",
    "board game": "tabuleiro",
    "board": "tabuleiro",
    "card": "cartas",
    "casual": "casual",
    "classic": "clássico",
    "comedy": "comédia",
    "crime": "crime",
    "documentary": "documentário",
    "drama": "drama",
    "driving": "corrida",
    "educational": "educativo",
    "family & relationships": "família e relacionamentos",
    "family": "família",
    "fantasy": "fantasia",
    "fiction": "ficção",
    "fighting": "luta",
    "hack and slash": "ação",
    "hack and slash/beat 'em up": "ação",
    "history": "história",
    "horror": "terror",
    "indie": "indie",
    "juvenile fiction": "ficção juvenil",
    "kids": "infantil",
    "mmo": "mmo",
    "moba": "moba",
    "music": "musical",
    "mystery": "mistério",
    "philosophy": "filosofia",
    "platform": "plataforma",
    "platformer": "plataforma",
    "point-and-click": "aventura",
    "psychological": "psicológico",
    "psychology": "psicologia",
    "puzzle": "puzzle",
    "racing": "corrida",
    "real time strategy (rts)": "rts",
    "real time strategy": "rts",
    "reality": "reality show",
    "religion": "religião",
    "rhythm": "musical",
    "role-playing (rpg)": "rpg",
    "role-playing": "rpg",
    "romance": "romance",
    "rpg": "rpg",
    "rts": "rts",
    "sandbox": "sandbox",
    "sci-fi": "ficção científica",
    "sci-fi & fantasy": "ficção científica e fantasia",
    "science fiction": "ficção científica",
    "science": "ciência",
    "self-help": "autoajuda",
    "shooter": "fps",
    "simulation": "simulação",
    "simulator": "simulação",
    "slice of life": "cotidiano",
    "soap": "novela",
    "social science": "ciências sociais",
    "sport": "esportes",
    "sports": "esportes",
    "strategy": "estratégia",
    "survival": "sobrevivência",
    "tactical": "estratégia",
    "thriller": "suspense",
    "turn-based strategy (tbs)": "estratégia",
    "turn-based strategy": "estratégia",
    "tv movie": "telefilme",
    "virtual reality": "rv",
    "visual novel": "aventura",
    "vr": "rv",
    "war": "guerra",
    "western": "faroeste",
    "young adult fiction": "ficção jovem adulto",
}


AUDIBLE_PTBR_GENRE_MAP: dict[str, list[str]] = {
    "administração": ["administração"],
    "adolescentes e jovens adultos": ["adolescentes", "jovens adultos"],
    "amadurecimento": ["amadurecimento"],
    "amizade": ["amizade"],
    "américa central e do sul": ["américa central", "américa do sul"],
    "américa do norte": ["américa do norte"],
    "américas": ["américas"],
    "animais": ["animais"],
    "animais de estimação e cuidados com animais": ["animais de estimação", "cuidados com animais"],
    "animais e natureza": ["animais", "natureza"],
    "antiga": ["antiga"],
    "antologias e contos": ["antologias", "contos"],
    "aprendizagem de línguas": ["aprendizagem de línguas"],
    "apresentadores e celebridades": ["apresentadores", "celebridades"],
    "arquitetura": ["arquitetura"],
    "arte e literatura": ["arte", "literatura"],
    "artes e entretenimento": ["artes", "entretenimento"],
    "artesanatos e passatempos": ["artesanatos", "passatempos"],
    "atividades e hobbies": ["atividades", "hobbies"],
    "atletismo": ["atletismo"],
    "audiobook": ["audiobook"],
    "audiolivros infantis": ["infantis"],
    "austrália e oceania": ["austrália", "oceania"],
    "austrália, nova zelândia e oceania": ["austrália", "nova zelândia", "oceania"],
    "autoajuda": ["autoajuda"],
    "aventura": ["aventura"],
    "aventura, lazer e natureza": ["aventura", "lazer", "natureza"],
    "aventuras marítimas": ["aventuras marítimas"],
    "aventureiros, exploradores e sobreviventes": ["aventureiros", "exploradores", "sobreviventes"],
    "ação e aventura": ["ação", "aventura"],
    "basquete": ["basquete"],
    "beisebol e softball": ["beisebol", "softball"],
    "biografias": ["biografias"],
    "biografias e memórias": ["biografias", "memórias"],
    "budismo": ["budismo"],
    "caminhada": ["caminhada"],
    "caribenha": ["caribenha"],
    "casa e jardim": ["casa", "jardim"],
    "casa e lar": ["casa", "lar"],
    "ciclismo": ["ciclismo"],
    "cidade pequena e rural": ["cidade pequena", "rural"],
    "ciência da computação": ["ciência da computação"],
    "ciência de dados": ["ciência de dados"],
    "ciência e tecnologia": ["ciência", "tecnologia"],
    "ciências": ["ciências"],
    "ciências e engenharia": ["ciências", "engenharia"],
    "ciências sociais": ["ciências sociais"],
    "clássicos": ["clássicos"],
    "clássicos e alegorias": ["clássicos", "alegorias"],
    "comentários e conteúdos de viagens": ["comentários de viagens", "conteúdos de viagens"],
    "comida e vinho": ["comida", "vinho"],
    "comportamento": ["comportamento"],
    "comportamento organizacional e no local de trabalho": ["comportamento organizacional", "local de trabalho"],
    "computadores e tecnologia": ["computadores", "tecnologia"],
    "comédia e humor": ["comédia", "humor"],
    "contemporâneo": ["contemporâneo"],
    "contos de fada": ["contos de fadas"],
    "contos de fadas, contos folclóricos e mitos": ["contos de fadas", "contos folclóricos", "mitos"],
    "criação de conteúdo e mídias sociais": ["criação de conteúdo", "mídias sociais"],
    "criação de filhos e famílias": ["criação de filhos", "famílias"],
    "crime verídico": ["crimes reais"],
    "crimes reais": ["crimes reais"],
    "cristianismo": ["cristianismo"],
    "cristão": ["cristão"],
    "críquete": ["críquete"],
    "cultural e regional": ["cultural", "regional"],
    "cyberpunk": ["cyberpunk"],
    "desenvolvimento de negócios e empreendedorismo": ["desenvolvimento de negócios", "empreendedorismo"],
    "desenvolvimento pessoal": ["desenvolvimento pessoal"],
    "didáticos": ["didáticos"],
    "dinheiro e finanças": ["dinheiro", "finanças"],
    "distopia": ["distopia"],
    "diários e correspondência": ["diários", "correspondência"],
    "doença física": ["doença física"],
    "dragões e criaturas míticas": ["dragões", "criaturas míticas"],
    "dramatizações e apresentações de áudio": ["dramatizações", "apresentações de áudio"],
    "dramaturgia e peças": ["dramaturgia", "peças"],
    "economia": ["economia"],
    "educação": ["educação"],
    "educação e aprendizagem": ["educação", "aprendizagem"],
    "ensaios": ["ensaios"],
    "entretenimento e artes cênicas": ["entretenimento", "artes cênicas"],
    "envelhecimento e longevidade": ["envelhecimento", "longevidade"],
    "epistolar": ["epistolar"],
    "erótica": ["erótica"],
    "escrita esportiva": ["escrita esportiva"],
    "esoterismo": ["esoterismo"],
    "espiritualidade": ["espiritualidade"],
    "esportes": ["esportes"],
    "esportes automotivos": ["esportes automotivos"],
    "esportes de combate e autodefesa": ["esportes de combate", "autodefesa"],
    "esportes de inverno": ["esportes de inverno"],
    "esportes e atividades ao ar livre": ["esportes", "atividades ao ar livre"],
    "esportes equestres": ["esportes equestres"],
    "estudos lgbt": ["estudos lgbt"],
    "europa": ["europa"],
    "exploração espacial": ["exploração espacial"],
    "fantasia": ["fantasia"],
    "fantasia sombria": ["fantasia sombria"],
    "faroeste": ["faroeste"],
    "feriados e celebrações": ["feriados", "celebrações"],
    "ficção": ["ficção"],
    "ficção biográfica": ["ficção biográfica"],
    "ficção científica": ["ficção científica"],
    "ficção científica e fantasia": ["ficção científica", "fantasia"],
    "ficção científica hard": ["ficção científica hard"],
    "ficção contemporânea": ["ficção contemporânea"],
    "ficção cristã": ["ficção cristã"],
    "ficção histórica": ["ficção histórica"],
    "ficção literária": ["ficção literária"],
    "finanças pessoais": ["finanças pessoais"],
    "fotografia": ["fotografia"],
    "futebol": ["futebol"],
    "gaslamp": ["gaslamp"],
    "gestão e liderança": ["gestão", "liderança"],
    "golfe": ["golfe"],
    "guerra e militar": ["guerra", "militar"],
    "gênero ficção": ["ficção"],
    "higiene e vida saudável": ["higiene", "vida saudável"],
    "hinduísmo": ["hinduísmo"],
    "história": ["história"],
    "história alternativa": ["história alternativa"],
    "história e cultura": ["história", "cultura"],
    "histórias reais": ["histórias reais"],
    "históricas": ["históricas"],
    "histórico": ["histórico"],
    "humor": ["humor"],
    "humor e sátira": ["humor", "sátira"],
    "humorístico": ["humorístico"],
    "hóquei": ["hóquei"],
    "império galáctico": ["império galáctico"],
    "imóveis": ["imóveis"],
    "indústria da medicina e cuidados da saúde": ["indústria da medicina", "cuidados da saúde"],
    "informática": ["informática"],
    "instrução sexual": ["instrução sexual"],
    "islã": ["islã"],
    "jardinagem e horticultura": ["jardinagem", "horticultura"],
    "jogos olímpicos e paralímpicos": ["jogos olímpicos", "jogos paralímpicos"],
    "leve": ["leve"],
    "lgbt": ["lgbt"],
    "literatura": ["literatura"],
    "literatura antiga, clássica e medieval": ["literatura antiga", "literatura clássica", "literatura medieval"],
    "literatura e ficção": ["literatura", "ficção"],
    "literatura mundial": ["literatura mundial"],
    "marketing e vendas": ["marketing", "vendas"],
    "medicina alternativa e complementar": ["medicina alternativa", "medicina complementar"],
    "memórias, diários e correspondência": ["memórias", "diários", "correspondência"],
    "metafísica e visionária": ["metafísica", "visionária"],
    "militar": ["militar"],
    "militares e guerras": ["militares", "guerras"],
    "mistério": ["mistério"],
    "mistério e suspense": ["mistério", "suspense"],
    "mistério, intriga e suspense": ["mistério", "intriga", "suspense"],
    "moderno": ["moderno"],
    "mulheres": ["mulheres"],
    "mulheres nos negócios": ["mulheres nos negócios"],
    "mundo": ["mundo"],
    "médico": ["médico"],
    "mídias digitais": ["mídias digitais"],
    "música": ["música"],
    "músicas e artes performáticas": ["músicas", "artes performáticas"],
    "negócios": ["negócios"],
    "negócios e carreiras": ["negócios", "carreiras"],
    "ocultismo": ["ocultismo"],
    "odontologia e saúde oral": ["odontologia", "saúde oral"],
    "oriente médio": ["oriente médio"],
    "outras religiões, práticas e textos sagrados": ["outras religiões", "práticas e textos sagrados"],
    "paranormal": ["paranormal"],
    "paranormal e urbano": ["paranormal", "urbano"],
    "pessoas com deficiências": ["pessoas com deficiências"],
    "poesia": ["poesia"],
    "poesias": ["poesias"],
    "política e ativismo": ["política", "ativismo"],
    "política e ciências sociais": ["política", "ciências sociais"],
    "política e governo": ["política", "governo"],
    "política, sociedade e eventos atuais": ["política", "sociedade", "eventos atuais"],
    "político": ["político"],
    "preparo físico, dieta e nutrição": ["preparo físico", "dieta", "nutrição"],
    "primeiro contato": ["primeiro contato"],
    "profissionais e acadêmicos": ["profissionais", "acadêmicos"],
    "psicologia": ["psicologia"],
    "psicologia e saúde mental": ["psicologia", "saúde mental"],
    "psicológico": ["psicológico"],
    "pós-apocalíptico": ["pós-apocalíptico"],
    "realeza": ["realeza"],
    "realismo mágico": ["realismo mágico"],
    "regiões polares": ["regiões polares"],
    "relacionamentos, criação de filhos e desenvolvimento pessoal": ["relacionamentos", "criação de filhos", "desenvolvimento pessoal"],
    "religião": ["religião"],
    "religião e espiritualidade": ["religião", "espiritualidade"],
    "religiões": ["religiões"],
    "religiosos": ["religiosos"],
    "romance": ["romance"],
    "rúgbi": ["rúgbi"],
    "rússia": ["rússia"],
    "sagas": ["sagas"],
    "saúde da criança": ["saúde da criança"],
    "saúde e bem-estar": ["saúde", "bem-estar"],
    "saúde sexual e reprodutiva": ["saúde sexual", "saúde reprodutiva"],
    "segurança e preparação para emergências": ["segurança", "preparação para emergências"],
    "sociologia": ["sociologia"],
    "sociologia dos esportes": ["sociologia dos esportes"],
    "steampunk": ["steampunk"],
    "sucesso na carreira": ["sucesso na carreira"],
    "super-herói": ["super-herói"],
    "suspense romântico": ["suspense romântico"],
    "século xx": ["século xx"],
    "tecnologia": ["tecnologia"],
    "terror": ["terror"],
    "thriller e suspenses": ["thriller", "suspenses"],
    "tie-ins de filmes, tv e videogames": ["tie-ins de filmes", "tv", "videogames"],
    "tênis": ["tênis"],
    "urbano": ["urbano"],
    "veículos e transporte": ["veículos", "transporte"],
    "viagem no tempo": ["viagem no tempo"],
    "viagens de aventura": ["viagens de aventura"],
    "viagens e turismo": ["viagens", "turismo"],
    "vida em família": ["vida em família"],
    "vida na cidade": ["vida na cidade"],
    "vida sustentável e verde": ["vida sustentável", "vida verde"],
    "vício e recuperação": ["vício", "recuperação"],
    "young adult": ["young adult"],
    "áfrica": ["áfrica"],
    "ártico e antártida": ["ártico", "antártida"],
    "ásia": ["ásia"],
    "épico": ["épico"],
    "ópera espacial": ["ópera espacial"],
}


AUDIBLE_ENG_GENRE_MAP: dict[str, list[str]] = {
    "action & adventure": ["action", "adventure"],
    "activities & hobbies": ["activities", "hobbies"],
    "addiction & recovery": ["addiction", "recovery"],
    "adventure travel": ["adventure travel"],
    "adventurers, explorers & survival": ["adventurers", "explorers", "survival"],
    "africa": ["africa"],
    "african american": ["african american"],
    "aging & longevity": ["aging", "longevity"],
    "agnosticism": ["agnosticism"],
    "alternative & complementary medicine": ["alternative medicine", "complementary medicine"],
    "americas": ["americas"],
    "ancient": ["ancient"],
    "ancient, classical & medieval literature": ["ancient literature", "classical literature", "medieval literature"],
    "animals & nature": ["animals", "nature"],
    "anthologies & short stories": ["anthologies", "short stories"],
    "anthropology": ["anthropology"],
    "archaeology": ["archaeology"],
    "architecture": ["architecture"],
    "arctic & antarctica": ["arctic", "antarctica"],
    "art": ["art"],
    "art & literature": ["art", "literature"],
    "arts & entertainment": ["arts", "entertainment"],
    "asia": ["asia"],
    "atheism": ["atheism"],
    "audio performances & dramatizations": ["audio performances", "dramatizations"],
    "australia & oceania": ["australia", "oceania"],
    "australia, new zealand & oceania": ["australia", "new zealand", "oceania"],
    "banks & banking": ["banks", "banking"],
    "baseball & softball": ["baseball", "softball"],
    "basketball": ["basketball"],
    "beauty, grooming & style": ["beauty", "grooming", "style"],
    "biographies": ["biographies"],
    "biographies & memoirs": ["biographies", "memoirs"],
    "bodybuilding & strength training": ["bodybuilding", "strength training"],
    "buddhism": ["buddhism"],
    "business & careers": ["business", "careers"],
    "business development & entrepreneurship": ["business development", "entrepreneurship"],
    "career success": ["career success"],
    "caribbean": ["caribbean"],
    "central & south america": ["central america", "south america"],
    "children's audiobooks": ["children's audiobooks"],
    "children's health": ["children's health"],
    "christian": ["christian"],
    "christianity": ["christianity"],
    "classics": ["classics"],
    "clean & wholesome": ["clean & wholesome"],
    "coaching": ["coaching"],
    "combat sports & self-defense": ["combat sports", "self-defense"],
    "comedy & humor": ["comedy", "humor"],
    "computer science": ["computer science"],
    "computers & technology": ["computers", "technology"],
    "contemporary": ["contemporary"],
    "content creation & social media": ["content creation", "social media"],
    "corporate & public finance": ["corporate finance", "public finance"],
    "crafts & hobbies": ["crafts", "hobbies"],
    "cricket": ["cricket"],
    "crime fiction": ["crime fiction"],
    "cultural & regional": ["cultural", "regional"],
    "cycling": ["cycling"],
    "data science": ["data science"],
    "dentistry & oral health": ["dentistry", "oral health"],
    "diaries & correspondence": ["diaries", "correspondence"],
    "drama & plays": ["drama", "plays"],
    "e-commerce": ["e-commerce"],
    "economics": ["economics"],
    "education": ["education"],
    "education & learning": ["education", "learning"],
    "engineering": ["engineering"],
    "entertainment & celebrities": ["entertainment", "celebrities"],
    "entertainment & performing arts": ["entertainment", "performing arts"],
    "equestrian sports": ["equestrian sports"],
    "erotica": ["erotica"],
    "essays": ["essays"],
    "europe": ["europe"],
    "extreme sports": ["extreme sports"],
    "fairy tales, folk tales & myths": ["fairy tales", "folk tales", "myths"],
    "fantasy": ["fantasy"],
    "fitness, diet & nutrition": ["fitness", "diet", "nutrition"],
    "food & wine": ["food", "wine"],
    "football": ["football"],
    "gardening & horticulture": ["gardening", "horticulture"],
    "genre fiction": ["genre fiction"],
    "geography & cultures": ["geography", "cultures"],
    "golf": ["golf"],
    "growing up & facts of life": ["growing up", "facts of life"],
    "guided tours": ["guided tours"],
    "health & wellness": ["health", "wellness"],
    "health, lifestyle & relationships": ["health", "lifestyle", "relationships"],
    "hinduism": ["hinduism"],
    "historical": ["historical"],
    "historical fiction": ["historical fiction"],
    "history": ["history"],
    "history & culture": ["history", "culture"],
    "hockey": ["hockey"],
    "holidays & celebrations": ["holidays", "celebrations"],
    "home & garden": ["home", "garden"],
    "horror": ["horror"],
    "house & home": ["house", "home"],
    "humor": ["humor"],
    "humor & satire": ["humor", "satire"],
    "hygiene & healthy living": ["hygiene", "healthy living"],
    "insurance": ["insurance"],
    "international": ["international"],
    "investing & trading": ["investing", "trading"],
    "islam": ["islam"],
    "judaism": ["judaism"],
    "language learning": ["language learning"],
    "law": ["law"],
    "lgbtq+": ["lgbtq+"],
    "lgbtq+ studies": ["lgbtq+ studies"],
    "literary history & criticism": ["literary history", "criticism"],
    "literature & fiction": ["literature", "fiction"],
    "management & leadership": ["management", "leadership"],
    "marketing & sales": ["marketing", "sales"],
    "mathematics": ["mathematics"],
    "medicine & health care industry": ["medicine", "health care industry"],
    "memoirs, diaries & correspondence": ["memoirs", "diaries", "correspondence"],
    "middle east": ["middle east"],
    "military": ["military"],
    "military & war": ["military", "war"],
    "modern": ["modern"],
    "money & finance": ["money", "finance"],
    "motor sports": ["motor sports"],
    "multicultural": ["multicultural"],
    "music": ["music"],
    "music & performing arts": ["music", "performing arts"],
    "mystery": ["mystery"],
    "mystery & suspense": ["mystery", "suspense"],
    "mystery, thriller & suspense": ["mystery", "thriller", "suspense"],
    "north america": ["north america"],
    "occult": ["occult"],
    "olympics & paralympics": ["olympics", "paralympics"],
    "other religions, practices & sacred texts": ["other religions", "practices & sacred texts"],
    "outdoors & nature": ["outdoors", "nature"],
    "paranormal": ["paranormal"],
    "parenting & families": ["parenting", "families"],
    "people with disabilities": ["people with disabilities"],
    "performing arts": ["performing arts"],
    "personal development": ["personal development"],
    "personal finance": ["personal finance"],
    "pets & animal care": ["pets", "animal care"],
    "philosophy": ["philosophy"],
    "photography": ["photography"],
    "physical illness & disease": ["physical illness", "disease"],
    "poetry": ["poetry"],
    "polar regions": ["polar regions"],
    "politics & activism": ["politics", "activism"],
    "politics & government": ["politics", "government"],
    "politics & social sciences": ["politics", "social sciences"],
    "politics, society & current events": ["politics", "society", "current events"],
    "professionals & academics": ["professionals", "academics"],
    "programming & software development": ["programming", "software development"],
    "psychology & mental health": ["psychology", "mental health"],
    "real estate": ["real estate"],
    "relationships": ["relationships"],
    "relationships, parenting & personal development": ["relationships", "parenting", "personal development"],
    "religion & spirituality": ["religion", "spirituality"],
    "religions": ["religions"],
    "religious": ["religious"],
    "religious studies": ["religious studies"],
    "romance": ["romance"],
    "romantic comedy": ["romantic comedy"],
    "romantic suspense": ["romantic suspense"],
    "royalty": ["royalty"],
    "rugby": ["rugby"],
    "running & jogging": ["running", "jogging"],
    "russia": ["russia"],
    "safety & emergency preparedness": ["safety", "emergency preparedness"],
    "science": ["science"],
    "science & engineering": ["science", "engineering"],
    "science & technology": ["science", "technology"],
    "science fiction": ["science fiction"],
    "science fiction & fantasy": ["science fiction", "fantasy"],
    "security & encryption": ["security", "encryption"],
    "sex instruction": ["sex instruction"],
    "sexual & reproductive health": ["sexual health", "reproductive health"],
    "soccer": ["soccer"],
    "social sciences": ["social sciences"],
    "sociology": ["sociology"],
    "sociology of sports": ["sociology of sports"],
    "spirituality": ["spirituality"],
    "sports": ["sports"],
    "sports & outdoors": ["sports", "outdoors"],
    "sports history": ["sports history"],
    "sports psychology": ["sports psychology"],
    "sports writing": ["sports writing"],
    "study guides & test preparation": ["study guides", "test preparation"],
    "sustainable & green living": ["sustainable living", "green living"],
    "taxation": ["taxation"],
    "teen & young adult": ["teen", "young adult"],
    "tennis": ["tennis"],
    "thriller & suspense": ["thriller", "suspense"],
    "track & field": ["track & field"],
    "travel & tourism": ["travel", "tourism"],
    "travel writing & commentary": ["travel writing", "commentary"],
    "triathlon": ["triathlon"],
    "true crime": ["true crime"],
    "vehicles & transportation": ["vehicles", "transportation"],
    "volleyball": ["volleyball"],
    "walking": ["walking"],
    "water sports": ["water sports"],
    "westerns": ["westerns"],
    "winter sports": ["winter sports"],
    "women": ["women"],
    "women in business": ["women in business"],
    "women's fiction": ["women's fiction"],
    "words, language & grammar": ["words", "language", "grammar"],
    "workouts": ["workouts"],
    "workplace & organizational behavior": ["workplace", "organizational behavior"],
    "world": ["world"],
    "world literature": ["world literature"],
    "writing & publishing": ["writing", "publishing"],
}


def map_audiobook_keywords(genres: str | list[str]) -> list[str]:
    """Map audiobook genre(s) using AUDIBLE_PTBR_GENRE_MAP and AUDIBLE_ENG_GENRE_MAP,

    falling back to original cleaned genre(s) if not matched in the maps.
    """
    raw_items = [genres] if isinstance(genres, str) else list(genres)

    def _lookup(val: str) -> list[str] | None:
        clean = re.sub(r"^\d+\.\s*", "", val).strip().lower()
        if not clean:
            return []
        return AUDIBLE_PTBR_GENRE_MAP.get(clean) or AUDIBLE_ENG_GENRE_MAP.get(clean)

    results: list[str] = []
    for item in raw_items:
        if not item or not isinstance(item, str):
            continue

        matched = _lookup(item)
        if matched:
            for m in matched:
                if m not in results:
                    results.append(m)
            continue

        for part in re.split(r"[;,/|]", item):
            p_clean = re.sub(r"^\d+\.\s*", "", part).strip().lower()
            if not p_clean:
                continue
            for m in _lookup(p_clean) or [p_clean]:
                if m not in results:
                    results.append(m)

    return results
