# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import importlib
import re
from collections.abc import Callable
from typing import Any

GuessitFn = Callable[[str, dict[str, Any] | None], dict[str, Any]]
_guessit_module = importlib.import_module("guessit")
_guessit_fn: GuessitFn = _guessit_module.guessit


def guessit_fn(value: str, options: dict[str, Any] | None = None) -> dict[str, Any]:
    return _guessit_fn(value, options)


async def get_region(bdinfo: dict[str, Any], region: str | None = None) -> str:
    label = (bdinfo.get("label") or bdinfo.get("title") or bdinfo.get("path") or "").replace(".", " ")
    if region is not None:
        region = region.upper()
    else:
        regions = {
            "AFG": "AFG",
            "AIA": "AIA",
            "ALA": "ALA",
            "ALG": "ALG",
            "AND": "AND",
            "ANG": "ANG",
            "ARG": "ARG",
            "ARM": "ARM",
            "ARU": "ARU",
            "ASA": "ASA",
            "ATA": "ATA",
            "ATF": "ATF",
            "ATG": "ATG",
            "AUS": "AUS",
            "AUT": "AUT",
            "AZE": "AZE",
            "BAH": "BAH",
            "BAN": "BAN",
            "BDI": "BDI",
            "BEL": "BEL",
            "BEN": "BEN",
            "BER": "BER",
            "BES": "BES",
            "BFA": "BFA",
            "BHR": "BHR",
            "BHU": "BHU",
            "BIH": "BIH",
            "BLM": "BLM",
            "BLR": "BLR",
            "BLZ": "BLZ",
            "BOL": "BOL",
            "BOT": "BOT",
            "BRA": "BRA",
            "BRB": "BRB",
            "BRU": "BRU",
            "BVT": "BVT",
            "CAM": "CAM",
            "CAN": "CAN",
            "CAY": "CAY",
            "CCK": "CCK",
            "CEE": "CEE",
            "CGO": "CGO",
            "CHA": "CHA",
            "CHI": "CHI",
            "CHN": "CHN",
            "CIV": "CIV",
            "CMR": "CMR",
            "COD": "COD",
            "COK": "COK",
            "COL": "COL",
            "COM": "COM",
            "CPV": "CPV",
            "CRC": "CRC",
            "CRO": "CRO",
            "CTA": "CTA",
            "CUB": "CUB",
            "CUW": "CUW",
            "CXR": "CXR",
            "CYP": "CYP",
            "DJI": "DJI",
            "DMA": "DMA",
            "DOM": "DOM",
            "ECU": "ECU",
            "EGY": "EGY",
            "ENG": "ENG",
            "EQG": "EQG",
            "ERI": "ERI",
            "ESH": "ESH",
            "ESP": "ESP",
            "ETH": "ETH",
            "EUR": "EUR",
            "FIJ": "FIJ",
            "FLK": "FLK",
            "FRA": "FRA",
            "FRO": "FRO",
            "FSM": "FSM",
            "GAB": "GAB",
            "GAM": "GAM",
            "GBR": "GBR",
            "GEO": "GEO",
            "GER": "GER",
            "GGY": "GGY",
            "GHA": "GHA",
            "GIB": "GIB",
            "GLP": "GLP",
            "GNB": "GNB",
            "GRE": "GRE",
            "GRL": "GRL",
            "GRN": "GRN",
            "GUA": "GUA",
            "GUF": "GUF",
            "GUI": "GUI",
            "GUM": "GUM",
            "GUY": "GUY",
            "HAI": "HAI",
            "HKG": "HKG",
            "HMD": "HMD",
            "HON": "HON",
            "HUN": "HUN",
            "IDN": "IDN",
            "IMN": "IMN",
            "IND": "IND",
            "IOT": "IOT",
            "IRL": "IRL",
            "IRN": "IRN",
            "IRQ": "IRQ",
            "ISL": "ISL",
            "ISR": "ISR",
            "ITA": "ITA",
            "JAM": "JAM",
            "JEY": "JEY",
            "JOR": "JOR",
            "JPN": "JPN",
            "KAZ": "KAZ",
            "KEN": "KEN",
            "KGZ": "KGZ",
            "KIR": "KIR",
            "KNA": "KNA",
            "KOR": "KOR",
            "KSA": "KSA",
            "KUW": "KUW",
            "KVX": "KVX",
            "LAO": "LAO",
            "LBN": "LBN",
            "LBR": "LBR",
            "LBY": "LBY",
            "LCA": "LCA",
            "LES": "LES",
            "LIE": "LIE",
            "LKA": "LKA",
            "LUX": "LUX",
            "MAC": "MAC",
            "MAD": "MAD",
            "MAF": "MAF",
            "MAR": "MAR",
            "MAS": "MAS",
            "MDA": "MDA",
            "MDV": "MDV",
            "MEX": "MEX",
            "MHL": "MHL",
            "MKD": "MKD",
            "MLI": "MLI",
            "MLT": "MLT",
            "MNG": "MNG",
            "MNP": "MNP",
            "MON": "MON",
            "MOZ": "MOZ",
            "MRI": "MRI",
            "MSR": "MSR",
            "MTN": "MTN",
            "MTQ": "MTQ",
            "MWI": "MWI",
            "MYA": "MYA",
            "MYT": "MYT",
            "NAM": "NAM",
            "NCA": "NCA",
            "NCL": "NCL",
            "NEP": "NEP",
            "NFK": "NFK",
            "NIG": "NIG",
            "NIR": "NIR",
            "NIU": "NIU",
            "NLD": "NLD",
            "NOR": "NOR",
            "NRU": "NRU",
            "NZL": "NZL",
            "OMA": "OMA",
            "PAK": "PAK",
            "PAN": "PAN",
            "PAR": "PAR",
            "PCN": "PCN",
            "PER": "PER",
            "PHI": "PHI",
            "PLE": "PLE",
            "PLW": "PLW",
            "PNG": "PNG",
            "POL": "POL",
            "POR": "POR",
            "PRK": "PRK",
            "PUR": "PUR",
            "QAT": "QAT",
            "REU": "REU",
            "ROU": "ROU",
            "RSA": "RSA",
            "RUS": "RUS",
            "RWA": "RWA",
            "SAM": "SAM",
            "SCO": "SCO",
            "SDN": "SDN",
            "SEN": "SEN",
            "SEY": "SEY",
            "SGS": "SGS",
            "SHN": "SHN",
            "SIN": "SIN",
            "SJM": "SJM",
            "SLE": "SLE",
            "SLV": "SLV",
            "SMR": "SMR",
            "SOL": "SOL",
            "SOM": "SOM",
            "SPM": "SPM",
            "SRB": "SRB",
            "SSD": "SSD",
            "STP": "STP",
            "SUI": "SUI",
            "SUR": "SUR",
            "SWZ": "SWZ",
            "SXM": "SXM",
            "SYR": "SYR",
            "TAH": "TAH",
            "TAN": "TAN",
            "TCA": "TCA",
            "TGA": "TGA",
            "THA": "THA",
            "TJK": "TJK",
            "TKL": "TKL",
            "TKM": "TKM",
            "TLS": "TLS",
            "TOG": "TOG",
            "TRI": "TRI",
            "TUN": "TUN",
            "TUR": "TUR",
            "TUV": "TUV",
            "TWN": "TWN",
            "UAE": "UAE",
            "UGA": "UGA",
            "UKR": "UKR",
            "UMI": "UMI",
            "URU": "URU",
            "USA": "USA",
            "UZB": "UZB",
            "VAN": "VAN",
            "VAT": "VAT",
            "VEN": "VEN",
            "VGB": "VGB",
            "VIE": "VIE",
            "VIN": "VIN",
            "VIR": "VIR",
            "WAL": "WAL",
            "WLF": "WLF",
            "YEM": "YEM",
            "ZAM": "ZAM",
            "ZIM": "ZIM",
        }
        for key, value in regions.items():
            if f" {key} " in label:
                region = value

    if region is None:
        region = ""
    return region


_DISTRIBUTORS = frozenset(
    (
        "01 DISTRIBUTION",
        "100 DESTINATIONS TRAVEL FILM",
        "101 FILMS",
        "1091",
        "1FILMS",
        "2 ENTERTAIN VIDEO",
        "20TH CENTURY FOX",
        "2GOOD",
        "2L",
        "35MM.ONLINE",
        "3D CONTENT HUB",
        "3D MEDIA",
        "3L FILM",
        "3RD WINDOW",
        "3RD WINDOW FILMS",
        "4DIGITAL",
        "4DVD",
        "4K UHD",
        "4K ULTRA HD MOVIES",
        "8-FILMS",
        "84 ENTERTAINMENT",
        "88 FILMS",
        "@ANIME",
        "A CONTRACORRIENTE",
        "A CONTRACORRIENTE FILMS",
        "A&E",
        "A&E HOME VIDEO",
        "A&M RECORDS",
        "A+E NETWORKS",
        "A+R",
        "A-FILM",
        "A24",
        "AAA",
        "AAMU FILM COMPANY",
        "AB VIDEO",
        "AB VIDÉO",
        "ABC",
        "ABC - (AMERICAN BROADCASTING CORPORATION)",
        "ABC - (AUSTRALIAN BROADCASTING CORPORATION)",
        "ABC STUDIOS",
        "ABKCO",
        "ABSOLUT MEDIEN",
        "ABSOLUTE",
        "ACCENT FILM ENTERTAINMENT",
        "ACCENTUS",
        "ACME FILM",
        "ACORN MEDIA",
        "AD VITAM",
        "ADA",
        "ADITYA VIDEOS",
        "ADSO FILMS",
        "ADV FILMS",
        "AFILM",
        "AFM RECORDS",
        "AGFA",
        "AIX RECORDS",
        "ALAMODE FILM",
        "ALBA RECORDS",
        "ALBANY RECORDS",
        "ALBATROS",
        "ALCHEMY",
        "ALIVE",
        "ALL ANIME",
        "ALL INTERACTIVE ENTERTAINMENT",
        "ALLEGRO",
        "ALLIANCE",
        "ALLIED VAUGHN",
        "ALLUMINATION FILMWORKS",
        "ALPHA MUSIC",
        "ALPHA VIDEO",
        "ALTERDYSTRYBUCJA",
        "ALTERED INNOCENCE",
        "ALTITUDE FILM DISTRIBUTION",
        "ALTRO",
        "ALUCARD RECORDS",
        "AMAZING D.C.",
        "AMAZING DC",
        "AMAZON PRIME",
        "AMMO CONTENT",
        "AMUSE SOFT ENTERTAINMENT",
        "ANCHOR BAY",
        "ANCONNECT",
        "ANDERSON MERCHANDISE",
        "ANEC",
        "ANIMATSU",
        "ANIME",
        "ANIME FACTORY",
        "ANIME HOUSE",
        "ANIME LTD",
        "ANIME WORKS",
        "ANIMEIGO",
        "ANIPLEX",
        "ANOLIS ENTERTAINMENT",
        "ANOTHER WORLD ENTERTAINMENT",
        "ANTI-WORLDS",
        "AP INTERNATIONAL",
        "APPLE",
        "APPLE TV+",
        "ARA MEDIA",
        "ARBELOS",
        "ARC ENTERTAINMENT",
        "ARCADE VIDEO",
        "ARCADES",
        "ARCADÈS",
        "ARISTA",
        "ARISTA BMG",
        "ARISTA/BMG",
        "ARISTABMG",
        "ARIZTICAL ENTERTAINMENT",
        "ARP SELECTION",
        "ARP SÉLECTION",
        "ARROW",
        "ARROW VIDEO",
        "ART SERVICE",
        "ART VISION",
        "ARTE EDITIONS",
        "ARTE PO POLSKU",
        "ARTE VIDEO",
        "ARTE VIDÉO",
        "ARTE ÉDITIONS",
        "ARTHAUS",
        "ARTHAUS MUSIK",
        "ARTIFICIAL EYE",
        "ARTISAN",
        "ARTISAN HOME ENTERTAINMENT",
        "ARTISTA FILMI",
        "ARTS MAGIC",
        "ARTSMAGIC",
        "ARTSPLOITATION FILMS",
        "ARTUS FILMS",
        "ASCOT ELITE HOME ENTERTAINMENT",
        "ASIA VIDEO",
        "ASIAN FILM ARCHIVE",
        "ASMIK ACE",
        "ASTRO RECORDS & FILMWORKS",
        "ASYLUM",
        "ATALANTA FILMES",
        "ATHENA",
        "ATLANTIC FILM",
        "ATLANTIC RECORDS",
        "ATLANTICFILM",
        "ATLAS FILM",
        "ATTRACTION DISTRIBUTION",
        "AUD",
        "AUDIO VISUAL ENTERTAINMENT",
        "AURO-3D CREATIVE LABEL",
        "AURUM",
        "AV VISIONEN",
        "AV-JET",
        "AVALON",
        "AVENTI",
        "AVEX TRAX",
        "AVH",
        "AXIOM",
        "AXIS RECORDS",
        "AYNGARAN",
        "B-SPREE CLASSICS",
        "BAC FILMS",
        "BACH FILMS",
        "BANDAI ENTERTAINMENT",
        "BANDAI VISUAL",
        "BARCLAY",
        "BAYVIEW",
        "BBC",
        "BBI",
        "BBI FILMS",
        "BCI HOME ENTERTAINMENT",
        "BEGGARS BANQUET",
        "BEL AIR CLASSIQUES",
        "BEL CANTO",
        "BELGA FILMS",
        "BELVEDERE",
        "BENELUX FILM DISTRIBUTORS",
        "BENNETT-WATT MEDIA",
        "BERLIN CLASSICS",
        "BERLINER PHILHARMONIKER RECORDINGS",
        "BEST ENTERTAINMENT",
        "BEYOND HOME ENTERTAINMENT",
        "BFI",
        "BFI VIDEO",
        "BFS",
        "BFS ENTERTAINMENT",
        "BHAVANI",
        "BIBER RECORDS",
        "BIG HOME VIDEO",
        "BIG WORLD PICTURES",
        "BILDSTORUNG",
        "BILDSTÖRUNG",
        "BILL ZEBUB",
        "BIM",
        "BIRNENBLATT",
        "BIT WEL",
        "BLACK BEAR",
        "BLACK BOX",
        "BLACK HILL",
        "BLACK HILL PICTURES",
        "BLACK HOLE",
        "BLACK HOLE RECORDINGS",
        "BLAQOUT",
        "BLAUFIELD",
        "BLAUFIELD MUSIC",
        "BLEEDING SKULL",
        "BLOCKBUSTER",
        "BLOCKBUSTER ENTERTAINMENT",
        "BLU",
        "BLU PHASE MEDIA",
        "BLU-RAY",
        "BLU-RAY ONLY",
        "BLUE GENTIAN RECORDS",
        "BLUE KINO",
        "BLUE UNDERGROUND",
        "BLUE WATER CONTENT",
        "BLUEBELL FILMS",
        "BLURAY",
        "BLURAY ONLY",
        "BMG",
        "BMG ARISTA",
        "BMG/ARISTA",
        "BMGARISTA",
        "BONTON",
        "BONTON FILM",
        "BOOMERANG",
        "BOOMERANG PICTURES",
        "BOUNTY FILMS",
        "BQHL",
        "BQHL EDITIONS",
        "BQHL ÉDITIONS",
        "BREAKING GLASS",
        "BRENTWOOD",
        "BRETZ FILMES",
        "BRIDGESTONE",
        "BRINK",
        "BRITISH BROADCASTING CORPORATION",
        "BRITISH FILM INSTITUTE",
        "BRITISH HOME ENTERTAINMENT",
        "BROAD GREEN",
        "BROAD GREEN PICTURES",
        "BUENA VISTA",
        "BURNING BULB PRODUCTIONS",
        "BUSCH",
        "BUSCH MEDIA GROUP",
        "C MAJOR",
        "C.B.S.",
        "CAHIERS DU CINEMA",
        "CAHIERS DU CINÉMA",
        "CAICHANG",
        "CALIFORNIA",
        "CALIFORNIA FILMES",
        "CALIFÓRNIA FILMES",
        "CAMEO",
        "CAMERA OBSCURA",
        "CAMERATA",
        "CAMP MOTION",
        "CAMP MOTION PICTURES",
        "CANADIAN INTERNATIONAL PICTURES",
        "CANAL+ ONLINE",
        "CANAL+ POLSKA",
        "CAPELIGHT",
        "CAPELIGHT PICTURES",
        "CAPITOL",
        "CAPITOL RECORDS",
        "CAPRICCI",
        "CARDINAL RELEASING",
        "CARGO RECORDS",
        "CARLOTA",
        "CARLOTTA",
        "CARLOTTA FILMS",
        "CARLTON",
        "CARMEN FILM",
        "CARTUNA",
        "CASCADE",
        "CATCHPLAY",
        "CATCOM HOME VIDEO",
        "CATTLEYA",
        "CAULDRON",
        "CAULDRON FILMS",
        "CBS",
        "CBS TELEVISION STUDIOS",
        "CC",
        "CCTV",
        "CCV",
        "CCV ENTERTAINMENT",
        "CD BABY",
        "CD LAND",
        "CDA PREMIUM",
        "CDI",
        "CECCHI GORI",
        "CECCHI GORI HOME VIDEO",
        "CELLULOID DREAMS",
        "CENTRAL PARK MEDIA",
        "CENTRE AUDIOVISUEL SIMONE DE BEAUVOIR",
        "CENTURY MEDIA",
        "CG ENTERTAINMENT",
        "CHAMELEON FILMS",
        "CHANNEL 4",
        "CHANNEL ONE",
        "CHE KU YU LE",
        "CHILI",
        "CHIMERA ENTERTAINMENT",
        "CHRISTAL FILMS",
        "CHRYSTAL FILMS",
        "CHUAN XUN SHI DAI MULTIMEDIA",
        "CINE PLUS HOME ENTERTAINMENT",
        "CINE-ASIA",
        "CINEART",
        "CINECOM",
        "CINEDIGM",
        "CINEFIL IMAGICA",
        "CINEHOLLYWOOD",
        "CINELICIOUS PICS",
        "CINEMA CLUB",
        "CINEMA EPOCH",
        "CINEMA GUILD",
        "CINEMA LIBRE STUDIOS",
        "CINEMA MONDO",
        "CINEMAGI",
        "CINEMATIC VISION",
        "CINEMATOGRAFICA",
        "CINEMATOGRAPHE",
        "CINEPHOBIA RELEASING",
        "CINEPLOIT RECORDS",
        "CINERAMA",
        "CINERIZ",
        "CINESTRANGE EXTREME",
        "CINÉART",
        "CINÉMATOGRAPHE",
        "CITEL",
        "CITEL VIDEO",
        "CJ",
        "CJ ENTERTAINMENT",
        "CLASSIC MEDIA",
        "CLASSICFLIX",
        "CLASSICLINE",
        "CLAUDIO RECORDS",
        "CLAVIS FILMS",
        "CLEAR VISION",
        "CLEOPATRA",
        "CLOSE UP",
        "CLOUD TEN PICTURES",
        "CLOUT MMA",
        "CMF",
        "CMS MEDIA LIMITED",
        "CMV LASERVISION",
        "CN ENTERTAINMENT",
        "CNN",
        "CODE RED",
        "COHEN",
        "COHEN MEDIA GROUP",
        "COIN DE MIRE CINEMA",
        "COIN DE MIRE CINÉMA",
        "COLORED FILMS",
        "COLOSSEO FILM",
        "COLUMBIA",
        "COLUMBIA PICTURES",
        "COLUMBIA/TRI-STAR",
        "COMMAND VIDEO",
        "COMMERCIAL MARKETING",
        "CONCORD MUSIC GROUP",
        "CONCORDE VIDEO",
        "CONDOR",
        "CONSTANTIN",
        "CONSTANTIN FILM",
        "CONSTANTINO",
        "CONSTANTINO FILMES",
        "CONSTRUCTIVE",
        "CONSTRUCTIVE MEDIA SERVICE",
        "CONTENDER ENTERTAINMENT GROUP",
        "CONTENT ZONE",
        "CONTENTS GATE",
        "COQUEIRO VERDE",
        "CORINTH FILMS",
        "CORNERSTONE",
        "CORNERSTONE MEDIA",
        "CP DIGITAL",
        "CRASH CINEMA",
        "CREST MOVIES",
        "CRISTALDI FILM",
        "CRITERION",
        "CRITERION COLLECTION",
        "CRITERION COLLECTION - CRITERION PREMIERES",
        "CROCOFILMS",
        "CRUNCHYROLL",
        "CRUNCHYROLL, LLC",
        "CRYSTAL CLASSICS",
        "CULT EPICS",
        "CULT FILMS",
        "CULT MEDIA",
        "CULT VIDEO",
        "CURZON FILM WORLD",
        "D & D GLASS AND WYATT",
        "D AILLY",
        "D AILLY COMPANY",
        "D FILMS",
        "D'AILLY",
        "D'AILLY COMPANY",
        "DA CAPO",
        "DA MUSIC",
        "DAIEI",
        "DAILLY",
        "DAILLY COMPANY",
        "DALL ANGELO",
        "DALL ANGELO PICTURES",
        "DALL'ANGELO",
        "DALL'ANGELO PICTURES",
        "DALLANGELO PICTURES",
        "DAREDO",
        "DARK FORCE",
        "DARK FORCE ENTERTAINMENT",
        "DARK SIDE",
        "DARK SIDE RELEASING",
        "DARK SKY FILMS",
        "DARK STAR PICTURES",
        "DAUNTLESS STUDIOS",
        "DAVID BURTON MORRIS FILMS",
        "DAZZLER",
        "DAZZLER MEDIA",
        "DCM",
        "DCM PICTURES",
        "DD HOME ENTERTAINMENT",
        "DEAF CROCODILE",
        "DEAPLANETA",
        "DECAL RELEASING",
        "DECCA",
        "DEEPJOY",
        "DEFIANT",
        "DEFIANT SCREEN",
        "DEFIANT SCREEN ENTERTAINMENT",
        "DEGAUSSER VIDEO",
        "DEKANALOG",
        "DELOS",
        "DELPHIAN",
        "DELPHIAN RECORDS",
        "DELTA MUSIC",
        "DELTA MUSIC & ENTERTAINMENT",
        "DELTA MUSIC AND ENTERTAINMENT",
        "DELTA MUSIC ENTERTAINMENT",
        "DELTAMAC",
        "DELTAMAC CO",
        "DELTAMAC CO LTD",
        "DELTAMAC CO. LTD.",
        "DEMAND",
        "DEMAND MEDIA",
        "DEP",
        "DEUTSCHE GRAMMOPHON",
        "DFW",
        "DGM",
        "DIAPHANA",
        "DIGIDREAMS",
        "DIGIDREAMS STUDIOS",
        "DIGITAL",
        "DIGITAL CLASSICS",
        "DIGITAL ELEMENT",
        "DIGITAL ENVIRONMENTS",
        "DIGITAL MEME",
        "DIMENSION FILMS",
        "DINO DE LAURENTIIS",
        "DISCOTEK MEDIA",
        "DISCOVERY",
        "DISCOVERY CHANNEL",
        "DISK KINO",
        "DISNEY",
        "DISNEY +",
        "DISNEY / BUENA VISTA",
        "DISNEY BUENA VISTA",
        "DISTRIB FILMS",
        "DISTRIBPIX",
        "DISTRIBUTION SELECT",
        "DISTRIMAX",
        "DIVISA",
        "DNC",
        "DNC ENTERTAINMENT",
        "DOCURAMA",
        "DOGWOOF",
        "DOLMEN",
        "DOLMEN HOME VIDEO",
        "DOMINO FILM",
        "DONAU",
        "DONAU FILM",
        "DORADO",
        "DORADO FILMS",
        "DORIANE FILMS",
        "DRAFTHOUSE",
        "DRAFTHOUSE FILMS",
        "DRAGON",
        "DRAGON ENTERTAINMENT",
        "DRAGON FILM",
        "DRAGON FILM ENTERTAINMENT",
        "DREAMSCAPE",
        "DREAMWORKS",
        "DRIVE ON",
        "DRIVE ON RECORDS",
        "DRIVE-ON",
        "DRIVEON",
        "DS MEDIA",
        "DTP",
        "DTP AG",
        "DTP ENTERTAINMENT",
        "DTP ENTERTAINMENT AG",
        "DTS",
        "DTS ENTERTAINMENT",
        "DUKE",
        "DUKE MARKETING",
        "DUKE VIDEO DISTRIBUTION",
        "DUTCH",
        "DUTCH FILMWORKS",
        "DVD",
        "DVD INTERNATIONAL",
        "DVD POCKET",
        "DYBEX",
        "DYNAMIC",
        "DYNIT",
        "E-KINO POD BARANAMI",
        "E1",
        "E1 ENTERTAINMENT",
        "EAGLE ENTERTAINMENT",
        "EAGLE HOME ENTERTAINMENT",
        "EAGLE HOME ENTERTAINMENT PVT LTD",
        "EAGLE HOME ENTERTAINMENT PVT.LTD.",
        "EAGLE HOME ENTERTAINMENT PVTLTD",
        "EAGLE PICTURES",
        "EAGLE ROCK",
        "EAGLE ROCK ENTERTAINMENT",
        "EAGLE VISION",
        "EAGLE VISION MEDIA",
        "EARMUSIC",
        "EARTH",
        "EARTH ENTERTAINMENT",
        "EASTWIND FILMS",
        "ECHO BRIDGE",
        "ECHO BRIDGE ENTERTAINMENT",
        "EDEL GERMANY",
        "EDEL GERMANY GMBH",
        "EDEL RECORDS",
        "EDICIONES 79",
        "EDITION FILMMUSEUM",
        "EDITION TONFILM",
        "EDITIONS MONTPARNASSE",
        "EDITO FILMS",
        "EDKO",
        "EDKO FILMS",
        "EDKO FILMS LTD",
        "EDKO FILMS LTD.",
        "EESTI FILM 100",
        "EIN'S M&M",
        "EIN'S M&M CO",
        "EINS M&M",
        "EINS M&M CO",
        "ELEA",
        "ELEA MEDIA",
        "ELEA-MEDIA",
        "ELECTRIC",
        "ELECTRIC PICTURE",
        "ELEMENT PICTURES",
        "ELEPHANT",
        "ELEPHANT FILMS",
        "ELEVATION",
        "ELITE ENTERTAINMENT",
        "ELOKUVAPALVELU J. SUOMALAINEN",
        "EMBREM ENTERTAINMENT",
        "EMI",
        "EMON",
        "EMS",
        "EMYLIA",
        "ENCORE",
        "ENE",
        "ENE MEDIA",
        "ENTERTAINMENT IN",
        "ENTERTAINMENT IN VIDEO",
        "ENTERTAINMENT ONE",
        "ENTERTAINMENT ONE CANADA",
        "ENTERTAINMENT ONE CANADA INC",
        "ENTERTAINMENT ONE FILMS CANADA",
        "ENTERTAINMENT ONE FILMS CANADA INC",
        "ENTERTAINMENT ONE FILMS CANADA INC.",
        "ENTERTAINMENTONE",
        "EONE",
        "EOS",
        "EPELPOL",
        "EPF MEDIA",
        "EPIC",
        "EPIC PICTURES",
        "EPIC RECORDS",
        "EPICENTRE FILMS",
        "ERATO",
        "EROS",
        "ERROR 4444",
        "ESC EDITIONS",
        "ESCAPI MEDIA BV",
        "ESOTERIC RECORDINGS",
        "ESPN FILMS",
        "ETR MEDIA",
        "EUREKA",
        "EUREKA - MASTERS OF CINEMA",
        "EUREKA ENTERTAINMENT",
        "EURO PICTURES",
        "EURO VIDEO",
        "EUROARTS",
        "EUROPA",
        "EUROPA FILMES",
        "EUROPACORP",
        "EUROZOOM",
        "EUSTON HOME ENTERTAINMENT",
        "EXCEL",
        "EXPLOSIVE",
        "EXPLOSIVE MEDIA",
        "EXTRALUCID",
        "EXTRALUCID FILMS",
        "EXTREME+",
        "EYE SEE",
        "EYE SEE MOVIES",
        "EYK",
        "EYK MEDIA",
        "FABULOUS",
        "FABULOUS FILMS",
        "FACETS",
        "FACTORIS",
        "FACTORIS FILMS",
        "FACTORY 25",
        "FACTORY25",
        "FAME MMA",
        "FANDANGO",
        "FANTOMA",
        "FARAO RECORDS",
        "FARBFILM",
        "FARBFILM ENTERTAINMENT",
        "FARBFILM HOME",
        "FARBFILM HOME ENTERTAINMENT",
        "FEEL FILMS",
        "FEELGOOD",
        "FEELGOOD ENTERTAINMENT",
        "FERNSEHJUWELEN",
        "FILM 2000",
        "FILM CHEST",
        "FILM DETECTIVE",
        "FILM FOETUS",
        "FILM MASTERS",
        "FILM MEDIA",
        "FILM MOVEMENT",
        "FILM PRESERVATION SOCIETY",
        "FILM4",
        "FILMART",
        "FILMAURO",
        "FILMAX",
        "FILMBUFF",
        "FILMCONFECT",
        "FILMCONFECT ENTERTAINMENT",
        "FILMCONFECT HOME",
        "FILMCONFECT HOME ENTERTAINMENT",
        "FILMEDIA",
        "FILMGALERIE 451",
        "FILMHUB",
        "FILMJUWELEN",
        "FILMNATION ENTERTAINMENT",
        "FILMOTECA ESPANOLA",
        "FILMOTECA ESPAÑOLA",
        "FILMOTEKA NARODAWA",
        "FILMOTRONIK",
        "FILMRISE",
        "FILMS SANS FRONTIERES",
        "FINAL CUT",
        "FINAL CUT ENTERTAINMENT",
        "FINNKINO",
        "FIREHOUSE 12",
        "FIREHOUSE 12 RECORDS",
        "FIRST INTERNATIONAL",
        "FIRST INTERNATIONAL PRODUCTION",
        "FIRST LOOK",
        "FIRST LOOK STUDIOS",
        "FIRST RUN FEATURES",
        "FLAGMAN TRADE",
        "FLASHBACK ENTERTAINMENT",
        "FLASHSTAR",
        "FLASHSTAR FILMES",
        "FLASHSTAR HOME ENTERTAINMENT",
        "FLICKER ALLEY",
        "FLIXCLASSIC",
        "FNC ADD CULTURE",
        "FOCUS",
        "FOCUS FILMES",
        "FOKUS MEDIA",
        "FOKUSA",
        "FOLKETS BIO",
        "FOX",
        "FOX EUROPA",
        "FOX LORBER",
        "FOX MGM",
        "FOX PATHE",
        "FOX PATHE EUROPA",
        "FOX/MGM",
        "FPE",
        "FRACTURED VISIONS",
        "FRAMEHAMMER FILMS",
        "FRAMELINE",
        "FRANCE",
        "FRANCE TELEVISIONS",
        "FRANCE TELEVISIONS DISTRIBUTION",
        "FRANCE TÉLÉVISIONS DISTRIBUTION",
        "FREE DOLPHIN",
        "FREE DOLPHIN ENTERTAINMENT",
        "FREESTYLE",
        "FREESTYLE DIGITAL",
        "FREESTYLE DIGITAL MEDIA",
        "FREMANTL",
        "FREMANTLE ENTERTAINMENT",
        "FREMANTLE HOME",
        "FREMANTLE HOME ENTERTAINMENT",
        "FRENETIC",
        "FRENETIC FILMS",
        "FRONTIER",
        "FRONTIER WORKS",
        "FRONTIERS MUSIC",
        "FRONTIERS RECORDS",
        "FS FILM",
        "FS FILM OY",
        "FULL MOON",
        "FULL MOON FEATURES",
        "FUN CITY",
        "FUN CITY EDITIONS",
        "FUNIMATION",
        "FUNIMATION ENTERTAINMENT",
        "FUSION",
        "FUTURAMA",
        "FUTUREFILM",
        "G2",
        "G2 PICTURES",
        "GABITA BARBIERI FILMS",
        "GAGA",
        "GAGA COMMUNICATIONS",
        "GAIAM",
        "GALAPAGOS",
        "GAMMA",
        "GAMMA ENTERTAINMENT",
        "GAMMA HOME",
        "GAMMA HOME ENTERTAINMENT",
        "GARAGEHOUSE",
        "GARAGEHOUSE PICTURES",
        "GARAGEPLAY",
        "GARAGEPLAY (CHE KU YU LE )",
        "GARAGEPLAY (CHE KU YU LE)",
        "GARAGEPLAY (車庫娛樂)",
        "GAUMONT",
        "GEFFEN",
        "GEMINI VIDEO EDITIONS",
        "GEMINI VIDÉO EDITIONS",
        "GENEON",
        "GENEON ENTERTAINMENT",
        "GENEON UNIVERSAL ENTERTAINMENT",
        "GENERAL VIDEO RECORDING",
        "GENIUS ENTERTAINMENT",
        "GHIBLI",
        "GIANT INTERACTIVE",
        "GLASS DOLL",
        "GLASS DOLL FILMS",
        "GLOBAL FILM",
        "GLOBE",
        "GLOBE MEDIA",
        "GLOBE MUSIC",
        "GLOBE MUSIC MEDIA",
        "GLOBO FILMES",
        "GLOBUS GROUP",
        "GO",
        "GO ENTERTAIN",
        "GOLDEN HARVEST",
        "GOLDHIL VIDEO",
        "GOOD GUYS MEDIA",
        "GOOD MOVIES",
        "GOOD TIMES",
        "GOOD! MOVIES",
        "GOOD!MOVIES",
        "GRAPEVINE",
        "GRAPEVINE VIDEO",
        "GRASSHOPPER",
        "GRASSHOPPER FILM",
        "GRASSHOPPER FILMS",
        "GRAVITAS",
        "GRAVITAS VENTURES",
        "GREAT",
        "GREAT MOVIES",
        "GREEN",
        "GREEN APPLE",
        "GREEN APPLE ENTERTAINMENT",
        "GREEN ENTERTAINMENT",
        "GREENNARAE",
        "GREENNARAE MEDIA",
        "GRIND HOUSE",
        "GRINDHOUSE",
        "GRINDHOUSE RELEASING",
        "GROUP GENDAI FILMS",
        "GRYPHON",
        "GRYPHON ENTERTAINMENT",
        "GUNPOWDER",
        "GUNPOWDER & SKY",
        "GUNPOWDER + SKY",
        "GUNPOWDER AND SKY",
        "GUNPOWDER SKY",
        "GZBEAUTY",
        "HALLMARK",
        "HAMBURG",
        "HAMBURG ENTERPRISES",
        "HAMBURGER MEDIEN HAUS",
        "HAMMER FILMS",
        "HANABEE",
        "HANABEE ENTERTAINMENT",
        "HANNA-BARBERA",
        "HANNOVER",
        "HANNOVER HOUSE",
        "HANNSLER",
        "HANNSLER CLASSIC",
        "HANSE",
        "HANSE SOUND",
        "HANSESOUND",
        "HAPPINET",
        "HAPPY ENTERTAINMENT",
        "HARDY CLASSIC VIDEO",
        "HARMONIA",
        "HARMONIA MUNDI",
        "HART SHARP",
        "HBO",
        "HBO MAX",
        "HD CINEMA CLASSICS",
        "HDC",
        "HEC",
        "HELL & BACK",
        "HELL & BACK RECORDINGS",
        "HELL AND BACK",
        "HELL AND BACK RECORDINGS",
        "HEN'S TOOTH",
        "HEN'S TOOTH VIDEO",
        "HENS TOOTH",
        "HENS TOOTH VIDEO",
        "HIGH FLIERS",
        "HIGHLIGHT",
        "HILLSONG",
        "HIP-O RECORDS",
        "HISTORY",
        "HISTORY CHANNEL",
        "HK",
        "HK VIDEO",
        "HK VIDÉO",
        "HMH",
        "HMH HAMBURGER",
        "HMH HAMBURGER MEDIEN",
        "HMH HAMBURGER MEDIEN HAUS",
        "HOLLYWOOD",
        "HOLLYWOOD CLASSIC",
        "HOLLYWOOD CLASSIC ENTERTAINMENT",
        "HOLLYWOOD DVD",
        "HOLLYWOOD PICTURES",
        "HOME MOVIES",
        "HOME VISION ENTERTAINMENT",
        "HONG KONG LEGENDS",
        "HOPSCOTCH",
        "HOPSCOTCH ENTERTAINMENT",
        "HPM",
        "HÄNNSLER CLASSIC",
        "I CATCHER",
        "I ON NEW MEDIA",
        "I WONDER PICTURES",
        "I-CATCHER",
        "I-ON",
        "I-ON NEW MEDIA",
        "IAN",
        "IAN PRODUCTIONS",
        "ICA",
        "ICARUS FILMS",
        "ICATCHER",
        "ICESTORM",
        "ICON",
        "ICON DISTRIBUTION",
        "ICON FILM",
        "ICON FILM DISTRIBUTION",
        "IDEALE",
        "IDEALE AUDIENCE",
        "IFC",
        "IFC FILMS",
        "IFILM",
        "IGNITE FILMS",
        "ILLUME",
        "ILLUMINATIONS",
        "ILLUSIONS",
        "ILLUSIONS UNLTD",
        "ILLUSIONS UNLTD.",
        "IMAGE",
        "IMAGE ENTERTAINMENT",
        "IMAGEM",
        "IMAGEM FILMES",
        "IMAGINE FILM DISTRIBUTION",
        "IMMINA FILMS",
        "IMOVISION",
        "IMPERIAL CINEPIX",
        "IMPRINT",
        "IMPULS",
        "IMPULS ENTERTAINMENT",
        "IMPULS HOME",
        "IMPULS HOME ENTERTAINMENT",
        "IMPULSE PICTURES",
        "IMPULSO",
        "IN AKUSTIK",
        "IN-AKUSTIK",
        "INAKUSTIK",
        "INCEPTION",
        "INCEPTION GROUP",
        "INCEPTION MEDIA",
        "INCEPTION MEDIA GROUP",
        "INDEED FILM",
        "INDEPENDENT",
        "INDICAN",
        "INDICATOR",
        "INDIE",
        "INDIE RIGHTS",
        "INDIEPIX FILMS",
        "INDIES ENTERTAINMENT",
        "INDIGO",
        "INFINITY ARTHOUSE",
        "INFINITY ENTERTAINMENT",
        "INFO",
        "INJOINGAN",
        "INKED",
        "INKED PICTURES",
        "INSIDE",
        "INSIDE MUSIC",
        "INSIDE OUT",
        "INSIDE OUT MUSIC",
        "INTERCOM",
        "INTERCONTINENTAL",
        "INTERCONTINENTAL VIDEO",
        "INTERESTING FILMS DIFFERENT PERSPECTIVES",
        "INTERGROOVE",
        "INTERNATIONAL SAMI FILM INSTITUTE",
        "INTERSCOPE",
        "INVINCIBLE",
        "INVINCIBLE PICTURES",
        "ION",
        "ION MEDIA",
        "ION NEW MEDIA",
        "IPLA VOD",
        "ISLA SALES",
        "ISLAND",
        "ISLAND & MERCURY",
        "ISLAND AND MERCURY",
        "ISLAND MERCURY",
        "ISLAND/MERCURY",
        "ISLANDMERCURY",
        "ISRAELI FILM FUND",
        "ISTITUTO LUCE",
        "ITN",
        "ITUNES",
        "ITV",
        "ITV DVD",
        "ITV STUDIOS HOME ENTERTAINMENT",
        "IVC",
        "IVE",
        "IVE ENTERTAINMENT",
        "J&R",
        "J&R ADVENTURES",
        "JAKOB",
        "JANSON MEDIA",
        "JANUS FILMS",
        "JOKERS",
        "JONU",
        "JONU MEDIA",
        "JOY SALES",
        "JR",
        "JRB",
        "JRB PRODUCTIONS",
        "JUPITER",
        "JUST",
        "JUST BRIDGE",
        "JUST BRIDGE ENTERTAINMENT",
        "JUST ENTERTAINMENT",
        "KABOOM",
        "KABOOM ENTERTAINMENT",
        "KADOKAWA",
        "KADOKAWA ENTERTAINMENT",
        "KADR",
        "KAIROS",
        "KALEIDOSCOPE",
        "KALEIDOSCOPE ENTERTAINMENT",
        "KAM & RONSON",
        "KAM & RONSON ENTERPRISES",
        "KAM AND RONSON",
        "KAM AND RONSON ENTERPRISES",
        "KAM&RONSON",
        "KAM&RONSON ENTERPRISES",
        "KANA HOME VIDEO",
        "KANI",
        "KANI RELEASING",
        "KARMA",
        "KARMA FILMS",
        "KATOFLIX",
        "KATZENBERGER",
        "KAZE",
        "KBS",
        "KBS MEDIA",
        "KD",
        "KD MEDIA",
        "KIDDIEPUNK",
        "KIMSTIM",
        "KING",
        "KING MEDIA",
        "KING RECORDS",
        "KINO",
        "KINO LORBER",
        "KINO POLSKA TV",
        "KINO SWIAT",
        "KINO-LORBER",
        "KINOKUNIYA",
        "KINOVISTA",
        "KINOWELT",
        "KINOWELT DVD",
        "KINOWELT ENTERTAINMENT",
        "KINOWELT ENTERTAINMENT/DVD",
        "KINOWELT FILM ENTERTAINMENT",
        "KINOWELT HOME DVD",
        "KINOWELT HOME ENTERTAINMENT",
        "KINOWELT HOME ENTERTAINMENT/DVD",
        "KIT PARKER",
        "KIT PARKER FILMS",
        "KITTY MEDIA",
        "KNM",
        "KNM ENTERTAINMENT",
        "KNM HOME",
        "KNM HOME ENTERTAINMENT",
        "KOBA",
        "KOBA FILMS",
        "KOCH",
        "KOCH ENTERTAINMENT",
        "KOCH MEDIA",
        "KOREAN FILM ARCHIVE",
        "KRAKEN",
        "KRAKEN RELEASING",
        "KRUPNYY PLAN",
        "KSCOPE",
        "KSM",
        "KSM ANIME",
        "KSW",
        "KULTUR",
        "KUMAR FILMS",
        "L ATELIER",
        "L ATELIER D IMAGES",
        "L ATELIER D'IMAGES",
        "L'ATELIER",
        "L'ATELIER D IMAGES",
        "L'ATELIER D'IMAGES",
        "L'ATELIER DIMAGES",
        "LA AVENTURA",
        "LA AVENTURA AUDIOVISUAL",
        "LA ENTERTAINMENT",
        "LA RABBIA",
        "LA TRAVERSE",
        "LA VIE EST BELLE",
        "LACE",
        "LACE GROUP",
        "LANCE ENTERTAINMENT",
        "LASER PARADISE",
        "LATELIER",
        "LATELIER D'IMAGES",
        "LATELIER DIMAGES",
        "LAVA",
        "LAYONS",
        "LCJ",
        "LCJ EDITIONS",
        "LE CHAT QUI FUME",
        "LE PACTE",
        "LEDICK FILMHANDEL",
        "LEGEND",
        "LEOMARK",
        "LEOMARK STUDIOS",
        "LEONINE",
        "LEONINE FILMS",
        "LES DOCUMENTS CINEMATOGRAPHIQUES",
        "LES DOCUMENTS CINÉMATOGRAPHIQUES",
        "LES FILMS DE MA VIE",
        "LES FILMS DU 3 MARS",
        "LES FILMS DU CAMELIA",
        "LES FILMS DU CAMÉLIA",
        "LES FILMS DU PARADOXE",
        "LEVEL 1 PRODUCTIONS",
        "LEVEL 33 ENTERTAINMENT",
        "LIBERATION ENTERTAINMENT",
        "LIBERATION HALL",
        "LICHTUNG",
        "LICHTUNG LTD",
        "LICHTUNG LTD.",
        "LICHTUNG MEDIA",
        "LICHTUNG MEDIA LTD",
        "LICHTUNG MEDIA LTD.",
        "LIGHTBULB FILM DISTRIBUTION",
        "LIGHTHOUSE",
        "LIGHTHOUSE ENTERTAINMENT",
        "LIGHTHOUSE HOME",
        "LIGHTHOUSE HOME ENTERTAINMENT",
        "LIGHTYEAR",
        "LIONSGATE",
        "LIONSGATE FILMS",
        "LIZARD CINEMA TRADE",
        "LLAMENTOL",
        "LOBSTER",
        "LOBSTER FILMS",
        "LOGON",
        "LOOKOUT MOUNTAIN STUDIO",
        "LORBER",
        "LORBER FILMS",
        "LOS BANDITOS",
        "LOS BANDITOS FILMS",
        "LOST TIME MEDIA",
        "LOUD & PROUD",
        "LOUD & PROUD RECORDS",
        "LOUD AND PROUD",
        "LOUD AND PROUD RECORDS",
        "LSO LIVE",
        "LUCASFILM",
        "LUCKY RED",
        "LUMIERE",
        "LUMIERE ENTERTAINMENT",
        "LUMIERE HOME",
        "LUMIERE HOME ENTERTAINMENT",
        "LUMIMIESFILMI",
        "LUMIÈRE HOME ENTERTAINMENT",
        "LUSOMUNDO",
        "M6",
        "M6 VIDEO",
        "MAD DIMENSION",
        "MADACY ENTERTAINMENT",
        "MADMAN",
        "MADMAN ENTERTAINMENT",
        "MAGIC BOX",
        "MAGIC PLAY",
        "MAGNA",
        "MAGNA ENTERTAINMENT",
        "MAGNA HOME",
        "MAGNA HOME ENTERTAINMENT",
        "MAGNOLIA",
        "MAGNOLIA PICTURES",
        "MAIDEN",
        "MAIDEN JAPAN",
        "MAISON4TIERS",
        "MAJENG",
        "MAJENG MEDIA",
        "MAJESTIC",
        "MAJESTIC ENTERTAINMENT",
        "MAJESTIC HOME",
        "MAJESTIC HOME ENTERTAINMENT",
        "MAKE PEACE PRODUCTONS",
        "MALAVIDA",
        "MANGA",
        "MANGA CORPS",
        "MANGA ENTERTAINMENT",
        "MANGA FILMS",
        "MANGA HOME",
        "MANGA HOME ENTERTAINMENT",
        "MANTA LAB",
        "MAPLE",
        "MAPLE STUDIOS",
        "MARCO POLO",
        "MARCO POLO PRODUCTION",
        "MARFILMES",
        "MARIINSKY",
        "MARVEL",
        "MARVEL STUDIOS",
        "MASCOT",
        "MASCOT RECORDS",
        "MASSACRE",
        "MASSACRE VIDEO",
        "MASTERS OF CINEMA",
        "MATCHBOX",
        "MATRIX D",
        "MAWU FILMS",
        "MAX",
        "MAXAM",
        "MAYA ENTERTAINMENT",
        "MAYA HOME",
        "MAYA HOME ENTERTAINMENT",
        "MAYAT",
        "MAYFLY",
        "MCINTYRE MEDIA INC",
        "MDG",
        "MEDIA BLASTERS",
        "MEDIA FACTORY",
        "MEDIA TARGET",
        "MEDIA TARGET DISTRIBUTION",
        "MEDIABOOK",
        "MEDIACS",
        "MEDIAINVISION",
        "MEDIATOON",
        "MEDIATRES",
        "MEDIATRES ESTUDIO",
        "MEDIATRES STUDIO",
        "MEDICI ARTS",
        "MEDICI CLASSICS",
        "MEDIEN",
        "MEDIUMRARE",
        "MEDIUMRARE ENTERTAINMENT",
        "MEDUSA",
        "MEGASTAR",
        "MEGOGO",
        "MEI AH",
        "MELI MEDIAS",
        "MELI MÉDIAS",
        "MELUSINE",
        "MEMENTO",
        "MEMENTO FILMS",
        "MEMORY",
        "MENEMSHA",
        "MENEMSHA FILMS",
        "MERCURY",
        "MERCURY STUDIOS",
        "MERGE",
        "MERGE PRODUCTIONS",
        "MERGE SOFT",
        "MERGE SOFT PRODUCTIONS",
        "MERIDIAN",
        "METAL BLADE",
        "METAL BLADE RECORDS",
        "METEOR",
        "METRO GOLDWYN MAYER",
        "METRO-GOLDWYN-MAYER",
        "METRODOME",
        "METRODOME VIDEO",
        "METROGOLDWYNMAYER",
        "METROPOLITAN",
        "MFA",
        "MFA+",
        "MGM",
        "MGM/FOX",
        "MHZ",
        "MICROCINEMA",
        "MIDNIGHT FACTORY",
        "MIG",
        "MIG FILMGROUP",
        "MIKADO",
        "MILESTONE",
        "MILL CREEK",
        "MILL CREEK ENTERTAINMENT",
        "MILLENNIUM",
        "MILLENNIUM MEDIA",
        "MILLENNIUM STORM",
        "MIRAGE",
        "MIRAGE ENTERTAINMENT",
        "MIRAMAX",
        "MIS LABEL",
        "MISTERIYA ZVUKA",
        "MK2",
        "MOC",
        "MODE",
        "MODE RECORDS",
        "MODERN FILMS",
        "MOJEEKINO",
        "MOKEP",
        "MOKÉP",
        "MOLOT ENTERTAINMENT",
        "MOMENTUM PICTURES",
        "MONARCH HOME ENTERTAINMENT",
        "MONDO ENTERTAINMENT",
        "MONDO HOME",
        "MONDO HOME ENTERTAINMENT",
        "MONDO HOME ENTERTAINMENT (ITALY)",
        "MONDO MACABRO",
        "MONGREL MEDIA",
        "MONOLIT",
        "MONOLITH",
        "MONOLITH VIDEO",
        "MONSTER",
        "MONSTER PICTURES",
        "MONTEREY",
        "MONTEREY VIDEO",
        "MONUMENT",
        "MONUMENT RELEASING",
        "MORE ENTERTAINMENT",
        "MORNING STAR",
        "MORNINGSTAR",
        "MOSERBAER",
        "MOVIEMAX",
        "MOVINSIDE",
        "MPI",
        "MPI MEDIA",
        "MPI MEDIA GROUP",
        "MR BONGO",
        "MR BONGO FILMS",
        "MR. BONGO FILMS",
        "MRG",
        "MRG (MERIDIAN)",
        "MRG MERIDIAN",
        "MUBI",
        "MUG SHOT",
        "MUG SHOT PRODUCTIONS",
        "MULTI MUSIC",
        "MULTI-MUSIC",
        "MULTIMUSIC",
        "MUNDO EN DVD",
        "MUSE",
        "MUSIC BOX",
        "MUSIC BOX FILMS",
        "MUSIC BROKERS",
        "MUSIC THEORIES",
        "MUSIC VIDEO",
        "MUSIC VIDEO DISTRIBUTORS",
        "MUSICBOX",
        "MUSICTRONIC ENTERTAINMENT",
        "MUSTANG",
        "MUSTANG ENTERTAINMENT",
        "MVD",
        "MVD VISUAL",
        "MVD/VSC",
        "MVL",
        "MVM",
        "MVM ENTERTAINMENT",
        "MYA",
        "MYNDFORM",
        "MYSTIC NIGHT",
        "MYSTIC NIGHT PICTURES",
        "NAMELESS",
        "NAMELESS MEDIA",
        "NAPALM",
        "NAPALM RECORDS",
        "NAT GEO",
        "NAT GEO TV",
        "NATIONAL ARCHIVE",
        "NATIONAL ENTERTAINMENT",
        "NATIONAL ENTERTAINMENT MEDIA",
        "NATIONAL FILM",
        "NATIONAL FILM ARCHIVE",
        "NATIONAL FILM BOARD OF CANADA",
        "NATIONAL GEOGRAPHIC",
        "NATIONAL MEDIA",
        "NAXOS",
        "NBC HOME VIDEO",
        "NBC JAPAN",
        "NBC UNIVERSAL ENTERTAINMENT JAPAN",
        "NBC UNIVERSAL JAPAN",
        "NBCUNIVERSAL ENTERTAINMENT JAPAN",
        "NBCUNIVERSAL JAPAN",
        "NBO",
        "NBO ENTERTAINMENT",
        "ND PLAY",
        "NEON",
        "NEOS",
        "NETFLIX",
        "NETWORK",
        "NEW BLOOD",
        "NEW DISC",
        "NEW KSM",
        "NEW LINE",
        "NEW LINE CINEMA",
        "NEW LINE HOME VIDEO",
        "NEW MOVIE TRADING",
        "NEW MOVIE TRADING CO",
        "NEW MOVIE TRADING CO LTD",
        "NEW MOVIE TRADING CO. LTD",
        "NEW STAR",
        "NEW VIDEO",
        "NEW WAVE",
        "NEW WAVE FILMS",
        "NEW YORKER FILMS",
        "NFI",
        "NGI",
        "NGO",
        "NHK",
        "NIGHT VISIONS",
        "NIKKATSU",
        "NINATEKA",
        "NIPPONART",
        "NIS AMERICA",
        "NJUTAFILMS",
        "NMC UNITED ENTERTAINMENT",
        "NO SHAME FILMS",
        "NOBLE",
        "NOBLE ENTERTAINMENT",
        "NORDISK",
        "NORDISK FILM",
        "NORMA PRODUCTIONS",
        "NORSK",
        "NORSK FILM",
        "NORTH AMERICAN MOTION PICTURES",
        "NOS AUDIOVISUAIS",
        "NOTORIOUS",
        "NOTORIOUS PICTURES",
        "NOVA",
        "NOVA MEDIA",
        "NOVA SALES & DISTRIBUTION",
        "NOVA SALES AND DISTRIBUTION",
        "NOVY DISK",
        "NOWE HORYZONTY",
        "NSM",
        "NSM RECORDS",
        "NU BOYANA",
        "NUCLEAR BLAST",
        "NUCLEUS",
        "NUCLEUS FILMS",
        "NUMAX",
        "OBERLIN",
        "OBERLIN MUSIC",
        "OBLIVION",
        "OBRAS PRIMAS",
        "OBRAS PRIMAS CINEMA",
        "OBRAS PRIMAS DO CINEMA",
        "OBRAS-PRIMAS",
        "OBRAS-PRIMAS CINEMA",
        "OBRAS-PRIMAS DO CINEMA",
        "OBRASPRIMAS",
        "OBRASPRIMAS CINEMA",
        "OBRASPRIMAS DO CINEMA",
        "ODEON",
        "ODYSSEY",
        "ODYSSEY QUEST",
        "OFDB",
        "OFDB FILMWORKS",
        "OLD GOLD MEDIA",
        "OLIVE",
        "OLIVE FILMS",
        "OLYDRI",
        "ON",
        "ON AIR",
        "ONDINE",
        "ONEGATE MEDIA",
        "ONSCREEN",
        "ONSCREEN FILMS",
        "OPENING DISTRIBUTION",
        "OPERA AUSTRALIA",
        "OPTIMALE",
        "OPTIMUM",
        "OPTIMUM ENTERTAINMENT",
        "OPTIMUM HOME",
        "OPTIMUM HOME ENTERTAINMENT",
        "OPTIMUM WORLD",
        "OPUS ARTE",
        "ORANGE",
        "ORANGE STUDIO",
        "ORLANDO",
        "ORLANDO EASTWOOD",
        "ORLANDO EASTWOOD FILMS",
        "ORLANDO FILMS",
        "ORUSTAK",
        "ORUSTAK PICTURES",
        "OSCILLOSCOPE",
        "OSCILLOSCOPE PICTURES",
        "OSTALGICA",
        "OUTCAST FILMS",
        "OUTFILM",
        "OUTPLAY",
        "P.O.M. FILMS",
        "PALISADES TARTAN",
        "PALM PICTURES",
        "PAN VISION",
        "PANAMINT",
        "PANAMINT CINEMA",
        "PANDA STORM",
        "PANDA STORM ENTERTAINMENT",
        "PANDASTORM",
        "PANDASTORM ENTERTAINMENT",
        "PANDORA",
        "PANDORA FILM",
        "PANEGYRIC",
        "PANIK HOUSE",
        "PANORAMA",
        "PANVISION",
        "PARADE DECK",
        "PARADE DECK FILMS",
        "PARADISE",
        "PARADISO FILMS",
        "PARADOX",
        "PARAMOUNT",
        "PARAMOUNT PICTURES",
        "PARIS",
        "PARIS FILMES",
        "PARIS FILMS",
        "PARK CIRCUS",
        "PARLOPHONE",
        "PASSION RIVER",
        "PASSPORT VIDEO",
        "PATHE",
        "PATHE DISTRIBUTION",
        "PATHFINDER HOME ENTERTAINMENT",
        "PATRIOT FILMS",
        "PAYLESS ENTERTAINMENT LIMITED",
        "PBS",
        "PEACE ARCH TRINITY",
        "PECCADILLO PICTURES",
        "PEPPERMINT",
        "PERISCOPE FILM",
        "PHASE 4",
        "PHASE 4 FILMS",
        "PHILHARMONIA BAROQUE",
        "PICTURE",
        "PICTURE ENTERTAINMENT",
        "PICTURE HOUSE",
        "PICTURE HOUSE ENTERTAINMENT",
        "PICTURE THIS",
        "PIDAX",
        "PIEC SMAKOW",
        "PIERROT LE FOU",
        "PINK FLOYD",
        "PINK FLOYD RECORDS",
        "PINNACLE",
        "PINNACLE FILMS",
        "PIONEER",
        "PIĘĆ SMAKÓW",
        "PLAIN",
        "PLAION",
        "PLAION PICTURES",
        "PLAN B",
        "PLANET DVD",
        "PLANET MEDIA HOME ENTERTAINMENT",
        "PLATFORM",
        "PLATFORM ENTERTAINMENT",
        "PLATFORM ENTERTAINMENT LIMITED",
        "PLATFORM ENTERTAINMENT LTD",
        "PLATFORM ENTERTAINMENT LTD.",
        "PLATINUM DISC",
        "PLAY NOW",
        "PLAYARTE",
        "PLAYER",
        "PLEXIFILM",
        "PLG",
        "PLG UK",
        "PLG UK CLASSICS",
        "PLUMERIA PICTURES",
        "POLAR FILM",
        "POLSAT BOX GO",
        "POLYBAND",
        "POLYBAND & TOPPIC",
        "POLYBAND & TOPPIC VIDEO",
        "POLYBAND & TOPPIC VIDEO & WVG",
        "POLYBAND & TOPPIC VIDEO AND WVG",
        "POLYBAND & TOPPIC VIDEO WVG",
        "POLYBAND & TOPPIC VIDEO/WVG",
        "POLYBAND AND TOPPIC",
        "POLYBAND AND TOPPIC VIDEO",
        "POLYBAND AND TOPPIC VIDEO & WVG",
        "POLYBAND AND TOPPIC VIDEO AND WVG",
        "POLYBAND AND TOPPIC VIDEO WVG",
        "POLYBAND AND TOPPIC VIDEO/WVG",
        "POLYDOR",
        "POLYGRAM",
        "POLYGRAM VIDEO",
        "PONY",
        "PONY CANYON",
        "POTEMKINE",
        "POWERHOUSE",
        "POWERHOUSE FILMS",
        "POWERSTATIOM",
        "PRECISION PICTURES",
        "PRIDE & JOY",
        "PRIDE AND JOY",
        "PRIME",
        "PRIME ->",
        "PRIME MMA",
        "PRIME VIDEO",
        "PRIME ➡️",
        "PRINZ",
        "PRINZ MEDIA",
        "PRIS AUDIOVISUAIS",
        "PRO MOTION",
        "PRO VIDEO",
        "PRO-FUN MEDIA",
        "PRO-MOTION",
        "PRO-VIDEO",
        "PROD JRB",
        "PROD. JRB",
        "PRODISC",
        "PROGRAM STORE",
        "PROKINO",
        "PROVOGUE",
        "PROVOGUE RECORDS",
        "PROWARE",
        "PTTRIP",
        "PULP",
        "PULP VIDEO",
        "PULSE",
        "PULSE VIDEO",
        "PURE AUDIO",
        "PURE AUDIO RECORDINGS",
        "PURE ENTERTAINMENT",
        "PURE FLIX",
        "PURE FLIX ENTERTAINMENT",
        "PYRAMIDE",
        "PYRAMIDE VIDEO",
        "QUALITY",
        "QUALITY FILMS",
        "QUARTO VALLEY",
        "QUARTO VALLEY RECORDS",
        "QUESTAR",
        "R SQUARED",
        "R SQUARED FILMS",
        "RABINOVICH FOUNDATION",
        "RADIANCE FILMS",
        "RADIOTELEVISIONE ITALIANA",
        "RAI",
        "RAI - RADIOTELEVISIONE ITALIANA",
        "RAI − RADIOTELEVISIONE ITALIANA",  # noqa: RUF001 - Distributor spelling from the source list.
        "RAKUTEN",
        "RAPID EYE",
        "RAPID EYE MOVIES",
        "RARO",
        "RARO U.S.",
        "RARO US",
        "RARO VIDEO",
        "RARO VIDEO U.S.",
        "RARO VIDEO US",
        "RAROVIDEO U.S.",
        "RAROVIDEO US",
        "RAVEN",
        "RAVEN BANNER",
        "RAVEN BANNER RELEASING",
        "RAZOR DIGITAL",
        "RAZOR DIGITAL ENTERTAINMENT",
        "RCA",
        "RCO",
        "RCO LIVE",
        "RCV",
        "RE:VOIR",
        "REAL GONE",
        "REAL GONE MUSIC",
        "REANI MEDIA",
        "REANIMEDIA",
        "RED BULL MEDIA HOUSE",
        "RED GO",
        "REDEMPTION",
        "REEL",
        "REEL ROCK",
        "REELIN' IN THE YEARS",
        "REFRESH",
        "RELIANCE",
        "RELIANCE HOME",
        "RELIANCE HOME VIDEO",
        "RELIANCE HOME VIDEO & GAMES",
        "RELIANCE HOME VIDEO AND GAMES",
        "RELIANCE VIDEO",
        "REM CULTURE",
        "REMAIN IN LIGHT",
        "RENE CHATEAU VIDEO",
        "RENOWN",
        "RENTRAK",
        "RENÉ CHATEAU VIDEO",
        "REPRISE",
        "REPUBLIC PICTURES",
        "RESEN",
        "RETRO GOLD 63",
        "RETROMEDIA",
        "REVELATION",
        "REVELATION FILMS",
        "REVELATION FILMS LTD",
        "REVELATION FILMS LTD.",
        "REVELATION LTD",
        "REVELATION LTD.",
        "REVOLVER",
        "REVOLVER ENTERTAINMENT",
        "RHI",
        "RHINO",
        "RHINO HOME VIDEO",
        "RHINO MUSIC",
        "RHV",
        "RIGHT STUF",
        "RIMINI EDITIONS",
        "RISING SUN MEDIA",
        "RLJ",
        "RLJ ENTERTAINMENT",
        "ROADRUNNER RECORDS",
        "ROADSHOW",
        "ROADSHOW ENTERTAINMENT",
        "RONE",
        "RONIN FLIX",
        "ROTANA",
        "ROTANA ENTERTAINMENT",
        "ROTANA HOME",
        "ROTANA HOME ENTERTAINMENT",
        "ROUGH TRADE",
        "ROUNDER",
        "ROUTE ONE RELEASING",
        "RUSCICO",
        "RUSTBLADE",
        "RYKO DISTRIBUTION",
        "RYKODISC",
        "SABOTAKT",
        "SAFFRON",
        "SAFFRON HILL",
        "SAFFRON HILL FILMS",
        "SALZGEBER & CO.",
        "SAMUEL GOLDWYN",
        "SAMUEL GOLDWYN FILMS",
        "SAMURAIDVD",
        "SAN FRANCISCO SYMPHONY",
        "SANCTUARY RECORDS",
        "SANDPIPER PICTURES",
        "SANDREW METRONOME",
        "SAPHRANE",
        "SATURN'S CORE AUDIO & VIDEO",
        "SAVOR",
        "SCANBOX",
        "SCANBOX ENTERTAINMENT",
        "SCANTRADE",
        "SCENIC LABS",
        "SCHOLAR VIDEO",
        "SCHRODER MEDIA",
        "SCHRODERMEDIA",
        "SCHRÖDERMEDIA",
        "SCORPION",
        "SCORPION RELEASING",
        "SCREAM FACTORY",
        "SCREAM TEAM",
        "SCREAM TEAM RELEASING",
        "SCREEN",
        "SCREEN ARCHIVES ENTERTAINMENT",
        "SCREEN MEDIA",
        "SCREENBOUND",
        "SCREENBOUND PICTURES",
        "SCREENWAVE",
        "SCREENWAVE MEDIA",
        "SECOND RUN",
        "SECOND SIGHT",
        "SECOND SIGHT FILMS",
        "SEEDSMAN GROUP",
        "SELECT VIDEO",
        "SELECTA VISION",
        "SENATOR",
        "SENATOR HOME ENTERTAINMENT",
        "SENTAI",
        "SENTAI FILMWORKS",
        "SEPTEMBER FILM",
        "SEVEN SPRINGS PICTURES",
        "SEVEN7",
        "SEVERIN",
        "SEVERIN FILMS",
        "SEVILLE",
        "SEYONS",
        "SEYONS ENTERTAINMENT",
        "SF STUDIOS",
        "SFI",
        "SGL",
        "SGL ENTERTAINMENT",
        "SHAMELESS",
        "SHAMROCK",
        "SHAMROCK MEDIA",
        "SHANACHIE",
        "SHANGHAI",
        "SHANGHAI ENTERTAINMENT",
        "SHANGHAI EPIC ENTERTAINMENT",
        "SHANGHAI EPIC MUSIC",
        "SHANGHAI EPIC MUSIC ENTERTAINMENT",
        "SHANGHAI MUSIC",
        "SHANGHAI MUSIC ENTERTAINMENT",
        "SHELLAC",
        "SHEMAROO",
        "SHOCHIKU",
        "SHOCK",
        "SHOGAKU KAN",
        "SHORELINE ENTERTAINMENT",
        "SHOUT",
        "SHOUT FACTORY",
        "SHOUT!",
        "SHOUT! FACTORY",
        "SHOWBOX",
        "SHOWSHANK FILMS",
        "SHOWTIME",
        "SHOWTIME ENTERTAINMENT",
        "SHRIEK SHOW",
        "SHUDDER",
        "SIDONIS",
        "SIDONIS CALYSTA",
        "SIGNAL ONE",
        "SIGNAL ONE ENTERTAINMENT",
        "SIGNATURE",
        "SIGNATURE ENTERTAINMENT",
        "SILVER VISION",
        "SIMPLY MEDIA",
        "SINISTER",
        "SINISTER FILM",
        "SIREN",
        "SIREN ENTERTAINMENT",
        "SIREN VISUAL",
        "SIREN VISUAL ENTERTAINMENT",
        "SKANI",
        "SKY DIGI",
        "SKYSHOWTIME",
        "SLAM DUNK MEDIA",
        "SLASHER",
        "SLASHER / VIDEO",
        "SLASHER // VIDEO",
        "SLASHER VIDEO",
        "SLOVAK FILM",
        "SLOVAK FILM INSTITUTE",
        "SLOVENIAN FILM CENTRE",
        "SM LIFE DESIGN GROUP",
        "SMOOTH",
        "SMOOTH PICTURES",
        "SMORE ENTERTAINMENT",
        "SNAPPER",
        "SNAPPER MUSIC",
        "SND",
        "SODA",
        "SODA PICTURES",
        "SOGEMEDIA",
        "SOGEPAQ",
        "SOMETHING WEIRD",
        "SONO LUMINUS",
        "SONY",
        "SONY CLASSICS",
        "SONY MUSIC",
        "SONY PICTURES",
        "SONY PICTURES CLASSICS",
        "SOUL",
        "SOUL MEDIA",
        "SOULFOOD",
        "SOULFOOD DISTRIBUTION",
        "SOULFOOD MUSIC",
        "SOULFOOD MUSIC DISTRIBUTION",
        "SOURCE 1 MEDIA B.V.",
        "SOVEREIGN FILM",
        "SOYUZ",
        "SPECTRUM",
        "SPENTZOS",
        "SPENTZOS FILM",
        "SPHERE FILMS",
        "SPIRIT",
        "SPIRIT ENTERTAINMENT",
        "SPIRIT MEDIA",
        "SPIRIT MEDIA GMBH",
        "SPLENDID ENTERTAINMENT",
        "SPLENDID FILM",
        "SPO",
        "SPROCKET VAULT",
        "SQUARE ENIX",
        "SRI",
        "SRI BALAJI",
        "SRI BALAJI VIDEO",
        "SRI VIDEO",
        "SRS",
        "SRS CINEMA",
        "SSO",
        "SSO RECORDINGS",
        "ST2",
        "ST2 MUSIC",
        "STAR",
        "STAR ENTERTAINMENT",
        "STAR MEDIA",
        "STAR MEDIA ENTERTAINMENT",
        "STARLIGHT",
        "STARZ",
        "STARZ / ANCHOR BAY",
        "STARZ ANCHOR BAY",
        "STER KINEKOR",
        "STERLING",
        "STERLING ENTERTAINMENT",
        "STINGRAY",
        "STOCKFISCH",
        "STOCKFISCH RECORDS",
        "STONE LANTERN FILMS",
        "STRADA FILM",
        "STRAND",
        "STRAND RELEASING",
        "STRAWBERRY MEDIA",
        "STUDIO 24",
        "STUDIO 4K",
        "STUDIO CANAL",
        "STUDIO DISTRIBUTION SERVICES",
        "STUDIO FILMOWE PERSPEKTYWA",
        "STUDIO GHIBLI",
        "STUDIO HAMBURG",
        "STUDIO HAMBURG ENTERPRISES",
        "STUDIO S",
        "STUDIOCANAL",
        "SUB ROSA",
        "SUBKULTUR",
        "SUBKULTUR ENTERTAINMENT",
        "SUBVERSIVE CINEMA",
        "SUEVIA",
        "SUEVIA FILMS",
        "SULLIVAN ENTERTAINMENT",
        "SUMMIT",
        "SUMMIT ENTERTAINMENT",
        "SUNDANCE",
        "SUNFILM",
        "SUNFILM ENTERTAINMENT",
        "SURF VIDEO",
        "SURROUND",
        "SURROUND RECORDS",
        "SURVIVANCE",
        "SVENSK",
        "SVENSK FILMINDUSTRI",
        "SWEN",
        "SWEN FILMES",
        "SWEN FILMS",
        "SYNAPSE",
        "SYNAPSE FILMS",
        "SYNDICADO",
        "SYNERGETIC",
        "T SERIES",
        "T- SERIES",
        "T-SERIES",
        "T.V.P.",
        "TABU",
        "TACET",
        "TACET RECORDS",
        "TAI SENG",
        "TAI SHENG",
        "TAIWAN FILM INSTITUTE",
        "TAKEONE",
        "TAKESHOBO",
        "TAMASA DIFFUSION",
        "TANELORN FILMS",
        "TANGO ENTERTAINMENT",
        "TARTAN VIDEO",
        "TC",
        "TC ENTERTAINMENT",
        "TDK",
        "TEAM MARKETING",
        "TEATRO REAL",
        "TELEVIO",
        "TELEVISTA",
        "TELEWIZJA POLSKA",
        "TEMA DISTRIBUCIONES",
        "TEMPE DIGITAL",
        "TERMINAL VIDEO",
        "TERROR VISION",
        "TETON GRAVITY RESEARCH",
        "TF1",
        "TF1 VIDEO",
        "TF1 VIDÉO",
        "TFC",
        "TGG DIRECT",
        "THAI FILM ARCHIVE",
        "THANK U INTERNATIONAL CO., LTD.",
        "THE BLU",
        "THE CRITERION COLLECTION",
        "THE ECSTASY OF FILMS",
        "THE FILM DESK",
        "THE FILM DETECTIVE",
        "THE FILM PRESERVE",
        "THE JOKERS",
        "THE ON",
        "THE THIRD EAR",
        "THIM",
        "THIM FILM",
        "THIMFILM",
        "THINKFILM",
        "THIRD WINDOW",
        "THIRD WINDOW FILMS",
        "THUNDERBEAN",
        "THUNDERBEAN ANIMATION",
        "THUNDERBIRD",
        "THUNDERBIRD RELEASING",
        "TIBERIUS FILM",
        "TIME LIFE",
        "TIMELESS",
        "TIMELESS GROUP",
        "TIMELESS MEDIA",
        "TIMELESS MEDIA GROUP",
        "TLA",
        "TLA RELEASING",
        "TOBIS",
        "TOBIS FILM",
        "TOEI",
        "TOHO",
        "TOKYO",
        "TOKYO SHOCK",
        "TONPOOL MEDIEN",
        "TONPOOL MEDIEN GMBH",
        "TOPICS",
        "TOPICS ENTERTAINMENT",
        "TOUCHSTONE",
        "TOUCHSTONE PICTURES",
        "TOY ROBOT VIDEO",
        "TRANSFORMER",
        "TRANSMISSION",
        "TRANSMISSION FILMS",
        "TRAVEL VIDEO STORE",
        "TREASURED FILMS",
        "TRI PICTURES",
        "TRI-PICTURES",
        "TRI-STAR",
        "TRIART",
        "TRIBECA",
        "TRIGON",
        "TRIGON FILM",
        "TRIMARK",
        "TRINITY",
        "TRINITY ENTERTAINMENT",
        "TRINITY HOME",
        "TRINITY HOME ENTERTAINMENT",
        "TRIPICTURES",
        "TROMA",
        "TSERIES",
        "TT",
        "TURBINE MEDIEN",
        "TURTLE",
        "TURTLE RECORDS",
        "TVA",
        "TVA FILMS",
        "TVN",
        "TVP",
        "TVP SPORT",
        "TVP VOD",
        "TVSMART",
        "TWILIGHT",
        "TWILIGHT TIME",
        "TWIN",
        "TWIN CO",
        "TWIN CO LTD",
        "TWIN CO, LTD",
        "TWIN CO, LTD.",
        "TWIN CO.",
        "TWIN CO., LTD",
        "TWIN CO., LTD.",
        "TWIN LTD",
        "TYPECAST RELEASING",
        "U.S. MANGA CORPS",
        "UCA",
        "UDR",
        "UEK",
        "UFA DVD",
        "UFA/DVD",
        "UFADVD",
        "UFO DISTRIBUTION",
        "UGC PH",
        "ULTIMATE3DHEAVEN",
        "ULTRA",
        "UMBRELLA",
        "UMBRELLA ENTERTAINMENT",
        "UMC",
        "UNCORK D",
        "UNCORK D ENTERTAINMENT",
        "UNCORK'D",
        "UNCORK'D ENTERTAINMENT",
        "UNCORKD",
        "UNCORKD ENTERTAINMENT",
        "UNDERCRANK PRODUCTIONS",
        "UNEARTHED",
        "UNEARTHED FILMS",
        "UNI DISC",
        "UNIMUNDOS",
        "UNITED KING FILMS",
        "UNITEL",
        "UNIVERSAL",
        "UNIVERSAL ENTERTAINMENT",
        "UNIVERSAL HOME",
        "UNIVERSAL HOME ENTERTAINMENT",
        "UNIVERSAL MUSIC",
        "UNIVERSAL PICTURES",
        "UNIVERSAL PICTURES HOME ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES",
        "UNIVERSAL SONY PICTURES ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES HOME",
        "UNIVERSAL SONY PICTURES HOME ENTERTAINMENT",
        "UNIVERSAL STUDIOS",
        "UNIVERSE LASER",
        "UNIVERSE LASER & VIDEO CO",
        "UNIVERSE LASER & VIDEO CO.",
        "UNIVERSE LASER AND VIDEO CO",
        "UNIVERSE LASER AND VIDEO CO.",
        "UNIVERSE LASER CO",
        "UNIVERSE LASER CO.",
        "UNIVERSLA RELEASE",
        "UNIVERSUM",
        "UNIVERSUM FILM",
        "URBAN VISION",
        "US MANGA CORPS",
        "UTOPIA DISTRIBUTION",
        "UTV",
        "VAI",
        "VANGUARD",
        "VAP",
        "VCI",
        "VENDETTA",
        "VENDETTA FILMS",
        "VERSATIL",
        "VERSATIL HOME",
        "VERSATIL HOME VIDEO",
        "VERSATIL VIDEO",
        "VERSÁTIL",
        "VERSÁTIL HOME",
        "VERSÁTIL HOME VIDEO",
        "VERSÁTIL VIDEO",
        "VERTICAL",
        "VERTICAL ENTERTAINMENT",
        "VERTICE 360",
        "VERTICE 360O",
        "VERTICE CINE",
        "VERTIGO",
        "VERTIGO BERLIN",
        "VERTIGO FILMS",
        "VERVE PICTURES",
        "VIA VISION",
        "VIA VISION ENTERTAINMENT",
        "VIAPLAY",
        "VICOL",
        "VICOL ENTERTAINMENT",
        "VICOM",
        "VICTOR",
        "VICTOR ENTERTAINMENT",
        "VIDANGEL STUDIOS",
        "VIDEA CDE",
        "VIDEO EXPRESS",
        "VIDEO FILM",
        "VIDEO FILM EXPRESS",
        "VIDEO MAX",
        "VIDEO MUSIC",
        "VIDEO MUSIC INC",
        "VIDEO MUSIC INC.",
        "VIDEO MUSIC, INC",
        "VIDEO MUSIC, INC.",
        "VIDEO PROJECT",
        "VIDEO SERVICE",
        "VIDEO SERVICE CORP",
        "VIDEO SERVICE CORP.",
        "VIDEO TRAVEL",
        "VIDEODIS",
        "VIDEOMAX",
        "VIEW VIDEO",
        "VII PILLARS",
        "VII PILLARS ENTERTAINMENT",
        "VILLAGE FILMS",
        "VINCA FILM",
        "VINEGAR",
        "VINEGAR SYNDROME",
        "VINNY",
        "VINNY MOVIES",
        "VINTAGE CLASSICS",
        "VIPCO",
        "VIRGIL",
        "VIRGIL ENTERTAINMENT",
        "VIRGIL FILMS",
        "VIRGIL FILMS & ENTERTAINMENT",
        "VIRGIL FILMS AND ENTERTAINMENT",
        "VIRGIN",
        "VIRGIN RECORDS",
        "VISION",
        "VISION FILM (POLAND)",
        "VISION FILMS",
        "VISION VIDEO UK",
        "VISUAL",
        "VISUAL ENTERTAINMENT",
        "VISUAL ENTERTAINMENT GROUP",
        "VISUAL GROUP",
        "VISUAL VENGEANCE",
        "VIVENDI",
        "VIVENDI VISUAL",
        "VIVENDI VISUAL ENTERTAINMENT",
        "VIZ",
        "VIZ MEDIA",
        "VIZ MEDIA, LLC",
        "VIZ PICTURES",
        "VL",
        "VL MEDIA",
        "VLMEDIA",
        "VOD WARSZAWA",
        "VOD.MDAG.PL",
        "VOLGA",
        "VS",
        "VVS",
        "VVS FILMS",
        "VZ HANDELS",
        "VZ HANDELS GMBH",
        "VÉRTICE 360",
        "VÉRTICE 360º",
        "VÉRTICE CINE",
        "VÉRTIGO",
        "VÉRTIGO FILMS",
        "WAC",
        "WALT DISNEY PRODUCTION",
        "WARD",
        "WARD RECORDS",
        "WARNER",
        "WARNER ARCHIVE",
        "WARNER ARCHIVE COLLECTION",
        "WARNER BROS",
        "WARNER BROS.",
        "WARNER HOME VIDEO",
        "WARNER MUSIC",
        "WARREN MILLER ENTERTAINMENT",
        "WATER BEARER FILMS",
        "WEA",
        "WEINSTEIN",
        "WEINSTEIN COMPANY",
        "WELL GO",
        "WELL GO USA",
        "WELLSPRING",
        "WELTKINO FILMVERLEIH",
        "WEST",
        "WEST VIDEO",
        "WHITE PEARL",
        "WHITE PEARL MOVIES",
        "WHITE PINE PICTURES",
        "WHOLE GRAIN PICTURES",
        "WICKED VISION",
        "WICKED VISION MEDIA",
        "WICKED-VISION",
        "WICKED-VISION MEDIA",
        "WICKEDVISION",
        "WICKEDVISION MEDIA",
        "WIENERWORLD",
        "WILD BUNCH",
        "WILD BUNCH BENELUX",
        "WILD EAST",
        "WILD EYE",
        "WILD EYE RELEASING",
        "WILD SIDE",
        "WILD SIDE VIDEO",
        "WINSTAR",
        "WME",
        "WMM",
        "WOLFE",
        "WOLFE VIDEO",
        "WONDER MULTIMIDIA",
        "WONDER MULTIMÍDIA",
        "WORD ON FIRE",
        "WORKS FILM GROUP",
        "WORLD WRESTLING",
        "WP PILOT",
        "WVG",
        "WVG MEDIEN",
        "WWE",
        "WWE STUDIOS",
        "X RATED",
        "X RATED CULT",
        "X RATED KULT",
        "X-RATED",
        "X-RATED CULT",
        "X-RATED KULT",
        "XCESS",
        "XENON",
        "XLRATOR",
        "XT",
        "XT VIDEO",
        "YAMATO",
        "YAMATO VIDEO",
        "YASH RAJ FILMS",
        "YASH RAJS",
        "YELLOW VEIL PICTURES",
        "YUME PICTURES",
        "ZEITGEIST",
        "ZEITGEIST FILMS",
        "ZENITH",
        "ZENITH PICTURES",
        "ZILLION FILM",
        "ZIMA",
        "ZORRO MEDIEN",
        "ZYLO",
        "ZYX",
        "ZYX MUSIC",
        "車庫娛樂",
    )
)


async def get_distributor(distributor_in: str | None) -> str:
    normalized = distributor_in.upper() if distributor_in else ""
    return normalized if normalized in _DISTRIBUTORS else ""


async def get_service(
    video: str | None = None, tag: str | None = None, audio: str | None = None, guess_title: str | None = None, get_services_only: bool = False
) -> dict[str, str] | tuple[str, str]:
    services = {
        "35mm.online": "35MM",
        "35MM": "35MM",
        "3Sat": "3SAT",
        "3SAT": "3SAT",
        "9Now": "9NOW",
        "9NOW": "9NOW",
        "À LA CARTE": "BELA",
        "A&E": "AE",
        "A3P": "A3P",
        "ABC (AU) iView": "AUBC",
        "ABC (US)": "AMBC",
        "ABC Australia": "AUBC",
        "ABC iView": "AUBC",
        "ABC": "AMBC",
        "Acorn TV": "ACORN",
        "ACORN": "ACORN",
        "ADN": "ADN",
        "Adult Swim": "AS",
        "AE": "AE",
        "AHA": "AHA",
        "aha": "AHA",
        "AJAZ": "AJAZ",
        "Al Jazeera English": "AJAZ",
        "All 4": "ALL4",
        "All4": "ALL4",
        "ALL4": "ALL4",
        "Amazon Prime Video": "AMZN",
        "Amazon Prime": "AMZN",
        "AMBC": "AMBC",
        "AMC": "AMC",
        "AMC+": "AMCP",
        "AMCP": "AMCP",
        "America's Test Kitchen": "ATK",
        "AMZN": "AMZN",
        "Angel Studios": "ANGL",
        "Angel": "ANGL",
        "ANGL": "ANGL",
        "Animal Planet": "ANPL",
        "Animation Digital Network": "ADN",
        "Anime Digital Network": "ADN",
        "AnimeLab": "ANLB",
        "ANLB": "ANLB",
        "ANPL": "ANPL",
        "AOL": "AOL",
        "Apple TV": "ATV",
        "Apple TV+": "ATVP",
        "APPS": "APPS",
        "ARD Mediathek": "ARD",
        "ARD Plus": "ARDP",
        "ARD": "ARD",
        "ARDP": "ARDP",
        "Arte": "ARTE",
        "ARTE": "ARTE",
        "AS": "AS",
        "ATK": "ATK",
        "Atresplayer": "A3P",
        "ATV": "ATV",
        "ATVP": "ATVP",
        "AUBC": "AUBC",
        "BB": "BB",
        "BBC iPlayer": "iP",
        "BCORE": "BCORE",
        "BELA": "BELA",
        "Belas Artes À La Carte": "BELA",
        "Bentkey": "BK",
        "BILI": "BILI",
        "Bilibili": "BILI",
        "Binge": "BNGE",
        "BK": "BK",
        "BKPL": "BKPL",
        "Blackpills": "BKPL",
        "BLU": "BLU",
        "BluTV": "BLU",
        "BMS": "BMS",
        "BNGE": "BNGE",
        "BookMyShow": "BMS",
        "BOOM": "BOOM",
        "Boomerang": "BOOM",
        "BP": "BP",
        "Brasil Paralelo": "BP",
        "BRAV": "BRAV",
        "Bravia Core": "BCORE",
        "BRAVIA CORE": "BCORE",
        "BravoTV": "BRAV",
        "BritBox": "BB",
        "BRTB": "BB",
        "C More": "CMOR",
        "Canal+": "CNLP",
        "Cartoon Network": "CN",
        "CBC": "CBC",
        "CBS": "CBS",
        "CC": "CC",
        "CCGC": "CCGC",
        "Channel 4": "ALL4",
        "Channel 5": "MY5",
        "Chaupal": "CHTV",
        "CHGD": "CHGD",
        "Chorki": "CRKI",
        "CHRGD": "CHGD",
        "CHTV": "CHTV",
        "Cinego": "CNGO",
        "Cinemax": "CMAX",
        "CineMember": "CM",
        "Cinobo": "CNB",
        "CLBI": "CLBI",
        "Club illico": "CLBI",
        "CM": "CM",
        "CMAX": "CMAX",
        "CMOR": "CMOR",
        "CMT": "CMT",
        "CN": "CN",
        "CNB": "CNB",
        "CNBC": "CNBC",
        "CNGO": "CNGO",
        "CNLP": "CNLP",
        "Comedians in Cars Getting Coffee": "CCGC",
        "Comedy Central": "CC",
        "COOK": "COOK",
        "Cooking Channel": "COOK",
        "CORE": "BCORE",
        "Country Music Television": "CMT",
        "CR": "CR",
        "Crackle": "CRKL",
        "CRAV": "CRAV",
        "Crave": "CRAV",
        "CRIT": "CRIT",
        "Criterion Channel": "CRIT",
        "Criterion": "CRIT",
        "CRKI": "CRKI",
        "CRKL": "CRKL",
        "Crunchy Roll": "CR",
        "Crunchyroll": "CR",
        "CRZN": "CRZN",
        "CSpan": "CSPN",
        "CSPN": "CSPN",
        "CTHP": "CTHP",
        "CTV": "CTV",
        "CUR": "CUR",
        "CuriosityStream": "CUR",
        "Curzon": "CRZN",
        "CW": "CW",
        "CWS": "CWS",
        "CWSeed": "CWS",
        "CWTV": "CW",
        "DailyWire+": "DLWP",
        "Daisuki": "DSKI",
        "DARKROOM": "DARKROOM",
        "DAZN": "DAZN",
        "DC Universe": "DCU",
        "DCU": "DCU",
        "DDY": "DDY",
        "Deadhouse Films": "DHF",
        "DEST": "DEST",
        "Destination America": "DEST",
        "DF": "DF",
        "DHF": "DHF",
        "Digiturk Diledigin Yerde": "DDY",
        "Digiturk Dilediğin Yerde": "DDY",
        "DirecTV Now": "DTV",
        "DISC": "DISC",
        "Discovery Channel": "DISC",
        "Discovery Plus": "DSCP",
        "Discovery": "DISC",
        "Discovery+": "DSCP",
        "Disney": "DSNY",
        "Disney+ (MENA/SEA)": "APPS",
        "Disney+": "DSNP",
        "DIY Network": "DIY",
        "DIY": "DIY",
        "DLWP": "DLWP",
        "Doc Club": "DOCC",
        "DOCC": "DOCC",
        "DocPlay": "DOCPLAY",
        "DOCPLAY": "DOCPLAY",
        "DPlay": "DPLY",
        "DPLY": "DPLY",
        "DramaFever": "DF",
        "Dropout": "DRPO",
        "DRPO": "DRPO",
        "DRTV": "DRTV",
        "DSCP": "DSCP",
        "DSKI": "DSKI",
        "DSNP": "DSNP",
        "DSNY": "DSNY",
        "DTV": "DTV",
        "E!": "ETV",
        "El Trece": "ETTV",
        "ePix": "EPIX",
        "EPIX": "EPIX",
        "ESPN": "ESPN",
        "ESQ": "ESQ",
        "Esquire": "ESQ",
        "ETTV": "ETTV",
        "ETV": "ETV",
        "Eye Film Player": "EYE",
        "EYE": "EYE",
        "Facebook Watch": "FBW",
        "FAM": "FAM",
        "Family Jr": "FJR",
        "Family": "FAM",
        "Fandango at Home": "FNDG",
        "Fandango": "FNDG",
        "Fandor": "FANDOR",
        "FANDOR": "FANDOR",
        "Fawsome TV": "FSTV",
        "FBW": "FBW",
        "FBWatch": "FBW",
        "Filmicca": "FLMC",
        "Filmin": "FLMN",
        "Filmio": "FMIO",
        "FJR": "FJR",
        "FLMC": "FLMC",
        "FLMN": "FLMN",
        "FMIO": "FMIO",
        "FNDG": "FNDG",
        "Food Network": "FOOD",
        "FOOD": "FOOD",
        "Fox Premium": "FOXP",
        "Fox": "FOX",
        "FOX": "FOX",
        "FOXP": "FOXP",
        "Foxtel Now": "FXTL",
        "Foxtel": "FXTL",
        "FP": "FP",
        "FPT Play": "FPT",
        "FPT": "FPT",
        "France.tv": "FTV",
        "FREE": "FREE",
        "Freeform": "FREE",
        "FSTV": "FSTV",
        "FTV": "FTV",
        "FUBO": "FUBO",
        "FuboTV": "FUBO",
        "FUNi": "FUNI",
        "FUNI": "FUNI",
        "Funimation": "FUNI",
        "FXTL": "FXTL",
        "FYI Network": "FYI",
        "FYI": "FYI",
        "Gaga": "GAGA",
        "GAGA": "GAGA",
        "GagaOOLala": "GAGA",
        "GC": "GC",
        "GLBL": "GLBL",
        "GLBO": "GLBO",
        "GLOB": "GLBO",
        "Global": "GLBL",
        "Globoplay": "GLBO",
        "GloboSat Play": "GLBO",
        "go90": "GO90",
        "GO90": "GO90",
        "Google Play": "PLAY",
        "Hallmark": "HLMK",
        "HBO Go": "HBO",
        "HBO Max": "HMAX",
        "HBO": "HBO",
        "HBOMAX": "HMAX",
        "HGM": "HGM",
        "HGTV": "HGTV",
        "HIDI": "HIDI",
        "HiDive": "HIDI",
        "HIDIVE": "HIDI",
        "HIST": "HIST",
        "History Channel": "HIST",
        "History": "HIST",
        "HLMK": "HLMK",
        "HMAX": "HMAX",
        "hoichoi": "HoiChoi",
        "HoiChoi": "HoiChoi",
        "Hotstar": "HTSR",
        "HPLAY": "HPLAY",
        "HS": "HTSR",
        "HSTR": "HTSR",
        "HTSR": "HTSR",
        "Hulu": "HULU",
        "HULU": "HULU",
        "Hungama OTT": "HGM",
        "Hungama Play": "HPLAY",
        "Ici TOU.TV": "TOU",
        "ICP": "ICP",
        "ID": "ID",
        "IFC": "IFC",
        "iflix": "IFX",
        "IFX": "IFX",
        "INA": "INA",
        "Infinity+": "INFP",
        "INFP": "INFP",
        "Investigation Discovery": "ID",
        "iP": "iP",
        "IQ": "iQIYI",
        "iQIYI": "iQIYI",
        "iT": "iT",
        "Itaú Cultural Play": "ICP",
        "iTunes": "iT",
        "ITV": "ITV",
        "ITVX": "ITV",
        "Ivi.ru": "IVI",
        "IVI": "IVI",
        "JC": "JC",
        "JHS": "JHS",
        "JioCinema": "JC",
        "JioHotstar": "JHS",
        "JOYN": "JOYN",
        "JUAN": "JUAN",
        "JuanFlix": "JUAN",
        "Kaleidescape": "KS",
        "Kanopy": "KNPY",
        "Kayo Sports": "KAYO",
        "KAYO": "KAYO",
        "KCW": "KCW",
        "KF": "KF",
        "KiKA": "KiKA",
        "KlikFilm": "KF",
        "KNOW": "KNOW",
        "Knowledge Network": "KNOW",
        "KNPY": "KNPY",
        "Kocowa": "KCW",
        "Kocowa+": "KCW",
        "KPN": "KPN",
        "KS": "KS",
        "LBXD": "LBXD",
        "Le.com": "LeTV",
        "Letterboxd": "LBXD",
        "LeTV": "LeTV",
        "LGP": "LGP",
        "LIFE": "LIFE",
        "Lifetime": "LIFE",
        "Lionsgate Play": "LGP",
        "LN": "LN",
        "Looke": "LOOKE",
        "LOOKE": "LOOKE",
        "Loving Nature": "LN",
        "MA": "MA",
        "manoramaMAX": "MMAX",
        "Max": "MAX",
        "MAX": "MAX",
        "MBC": "MBC",
        "Megogo": "MGG",
        "MeGoGo": "MGG",
        "MEGOGO": "MGG",
        "MGG": "MGG",
        "Microsoft Store": "MS",
        "MMAX": "MMAX",
        "MNBC": "MNBC",
        "MONOMAX": "MX",
        "Motor Trend OnDemand": "MTOD",
        "Movies Anywhere": "MA",
        "MS": "MS",
        "MSNBC": "MNBC",
        "MTOD": "MTOD",
        "MTV": "MTV",
        "Mubi": "MUBI",
        "MUBI": "MUBI",
        "MX": "MX",
        "MY5": "MY5",
        "NATG": "NATG",
        "National Audiovisual Institute": "INA",
        "National Film Board of Canada": "NFB",
        "National Film Board": "NFB",
        "National Geographic": "NATG",
        "NBA League Pass": "NBA",
        "NBA TV": "NBA",
        "NBA": "NBA",
        "NBC": "NBC",
        "NBLA": "NBLA",
        "Nebula": "NBLA",
        "Netflix": "NF",
        "NF": "NF",
        "NFB": "NFB",
        "NFL Network": "NFL",
        "NFL Now": "NFLN",
        "NFL": "NFL",
        "NFLN": "NFLN",
        "NHL GameCenter": "GC",
        "NICK": "NICK",
        "Nickelodeon": "NICK",
        "Norsk Rikskringkasting": "NRK",
        "Now": "NOW",
        "NOW": "NOW",
        "NOWTV": "NOW",
        "NPO Start": "NPO",
        "NPO": "NPO",
        "NRK": "NRK",
        "OBB Railnet": "RNET",
        "ODK": "ODK",
        "OFTV": "OFTV",
        "OnDemandKorea": "ODK",
        "OnlyFans TV": "OFTV",
        "Oprah Winfrey Network": "OWN",
        "Opto": "OPTO",
        "OPTO": "OPTO",
        "ORF ON": "ORF",
        "ORF": "ORF",
        "OSN": "OSN",
        "OSN+": "OSN",
        "OWN": "OWN",
        "OXGN": "OXGN",
        "Oxygen": "OXGN",
        "PA": "PA",
        "Paramount Network": "PMNT",
        "Paramount+": "PMTP",
        "PBS Kids": "PBSK",
        "PBS": "PBS",
        "PBSK": "PBSK",
        "PCOK": "PCOK",
        "Peacock": "PCOK",
        "PKO": "PKO",
        "Planeta Kino Online": "PKO",
        "PLAY": "PLAY",
        "Player": "PLYR",
        "Playstation Network": "PSN",
        "PlayStation Network": "PSN",
        "PLTV": "PLTV",
        "Pluto TV": "PLTV",
        "PLUZ": "PLUZ",
        "Pluzz": "PLUZ",
        "PLYR": "PLYR",
        "PMNP": "PMNP",
        "PMNT": "PMNT",
        "PMTP": "PMTP",
        "POGO": "POGO",
        "PokerGo": "POGO",
        "PokerGO": "POGO",
        "Prime Video": "AMZN",
        "Project Alpha": "PA",
        "PSN": "PSN",
        "PUHU": "PUHU",
        "puhutv": "PUHU",
        "QIBI": "QIBI",
        "Quibi": "QIBI",
        "Rakuten TV": "RKTN",
        "RED": "RED",
        "RKTN": "RKTN",
        "RNET": "RNET",
        "ROKU": "ROKU",
        "Rooster Teeth": "RSTR",
        "RSTR": "RSTR",
        "RTE One": "RTE",
        "RTE": "RTE",
        "RTÉ": "RTE",
        "RTL+": "RTLP",
        "RTLP": "RTLP",
        "RUUTU": "RUUTU",
        "Saina Play": "SAINA",
        "SAINA": "SAINA",
        "SBS On Demand": "SBS",
        "SBS": "SBS",
        "SCI": "SCI",
        "Science Channel": "SCI",
        "Seeso": "SESO",
        "SeeSo": "SESO",
        "SESO": "SESO",
        "SF Anytime": "SF",
        "SF": "SF",
        "Shahid": "SHAHID",
        "SHAHID": "SHAHID",
        "SHDR": "SHDR",
        "SHMI": "SHMI",
        "SHO": "SHO",
        "Shomi": "SHMI",
        "Showmax": "SMAX",
        "Showtime": "SHO",
        "Shudder": "SHDR",
        "Simply South": "SS",
        "SKSH": "SKSH",
        "SKSP": "SKSP",
        "SKST": "SKST",
        "SKSTR": "SKSTR",
        "Sky Show": "SKSH",
        "Sky Sport": "SKSP",
        "Sky Store": "SKSTR",
        "SkyShowtime": "SKST",
        "Sling TV": "SLNG",
        "SLIV": "SLIV",
        "SLNG": "SLNG",
        "SMAX": "SMAX",
        "SNET": "SNET",
        "SNXT": "SNXT",
        "Sony Pictures Core": "BCORE",
        "Sony": "SONY",
        "SONY": "SONY",
        "SonyLIV": "SLIV",
        "SPIK": "SPIK",
        "Spike TV": "SPKE",
        "Spike": "SPIK",
        "SPKE": "SPKE",
        "Sportsnet": "SNET",
        "Sprout": "SPRT",
        "SPRT": "SPRT",
        "SS": "SS",
        "Stan": "STAN",
        "STAN": "STAN",
        "Star+": "STRP",
        "Starz": "STZ",
        "STARZ": "STZ",
        "STMZ": "STMZ",
        "Streamz": "STMZ",
        "STRP": "STRP",
        "STZ": "STZ",
        "Sun NXT": "SNXT",
        "SunNXT": "SNXT",
        "Sveriges Television": "SVT",
        "SVT": "SVT",
        "SwearNet": "SWER",
        "SWEET.TV": "SWEET",
        "SWEET": "SWEET",
        "SWER": "SWER",
        "Syfy": "SYFY",
        "SyFy": "SYFY",
        "SYFY": "SYFY",
        "takflix": "TF",
        "Takflix": "TF",
        "TBS": "TBS",
        "TEN": "TEN",
        "TenPlay": "TEN",
        "Tentkotta": "TK",
        "TF": "TF",
        "TFou": "TFOU",
        "TFOU": "TFOU",
        "The CW": "CW",
        "The Roku Channel": "ROKU",
        "TIMV": "TIMV",
        "TIMvision": "TIMV",
        "TK": "TK",
        "TLC": "TLC",
        "TOU.TV": "TOU",
        "TOU": "TOU",
        "Travel Channel": "TRVL",
        "TRVL": "TRVL",
        "TUBI": "TUBI",
        "TubiTV": "TUBI",
        "TV Land": "TVL",
        "TV2": "TV2",
        "TV3 Ireland": "TV3",
        "TV3": "TV3",
        "TV4 Sweden": "TV4",
        "TV4": "TV4",
        "TVF": "TVF",
        "TVFPlay": "TVF",
        "TVING": "TVING",
        "TVL": "TVL",
        "TVLand": "TVL",
        "TVNZ": "TVNZ",
        "U-NEXT": "UNXT",
        "UFC Fight Pass": "FP",
        "UFC": "UFC",
        "UKTV": "UKTV",
        "UNIV": "UNIV",
        "Univer Vídeo": "UNVD",
        "Univision": "UNIV",
        "UNVD": "UNVD",
        "UNXT": "UNXT",
        "USA Network": "USAN",
        "USAN": "USAN",
        "VDO": "VDO",
        "Velocity": "VLCT",
        "VET Tv": "VTRN",
        "VH1": "VH1",
        "VIAP": "VIAP",
        "Viaplay": "VIAP",
        "VICE": "VICE",
        "Viceland": "VICE",
        "Videoland": "VLD",
        "Vidio": "VDO",
        "Viki": "VIKI",
        "VIKI": "VIKI",
        "Vimeo": "VMEO",
        "VIMEO": "VMEO",
        "VIU": "VIU",
        "Vivamax": "VMX",
        "Vivaone": "VONE",
        "VLCT": "VLCT",
        "VLD": "VLD",
        "VMAX": "VMX",
        "VMEO": "VMEO",
        "VMX": "VMX",
        "VONE": "VONE",
        "VRV": "VRV",
        "VTRN": "VTRN",
        "Vudu": "VUDU",
        "VUDU": "VUDU",
        "VVMX": "VMX",
        "W Network": "WNET",
        "Watcha": "WTCH",
        "WatchMe": "WME",
        "WME": "WME",
        "WNET": "WNET",
        "WOW Presents Plus": "WOWP",
        "WOWP": "WOWP",
        "WTCH": "WTCH",
        "WWE Network": "WWEN",
        "WWEN": "WWEN",
        "Xbox Video": "XBOX",
        "XBOX": "XBOX",
        "Xumo Play": "XUMO",
        "Xumo": "XUMO",
        "XUMO": "XUMO",
        "Yahoo": "YHOO",
        "YHOO": "YHOO",
        "YOUKU": "YOUKU",
        "YoukuTV": "YOUKU",
        "YouTube Movies": "YT",
        "YouTube Premium": "RED",
        "YouTube Red": "RED",
        "YT": "YT",
        "ZDF": "ZDF",
        "ZEE5": "ZEE5",
    }

    if get_services_only:
        return services

    if video is None:
        return "", ""

    guess_data = guessit_fn(video)
    service: str = str(guess_data.get("streaming_service", ""))
    service = services.get(service, service)

    video_name = " " + re.sub(r"[.()]", " ", video.replace(tag or "", "").replace(guess_title or "", "")) + " "
    if audio and "DTS-HD MA" in audio:
        video_name = video_name.replace("DTS-HD.MA.", "").replace("DTS-HD MA ", "")
    title_guess = guessit_fn(video, {"excludes": ["country", "language"]})
    title_guess_title = str(title_guess.get("title", ""))
    title_guess_episode_title = str(title_guess.get("episode_title", ""))
    longest_match = 0
    for key, value in services.items():
        # Keep long descriptive names for metadata, but only match concise filename aliases.
        filename_alias = re.sub(r"[.()]", " ", key)
        if len(filename_alias.split()) > 3:
            continue
        # Compact service names, not filename fields, so titles and tags stay separate.
        for alias in (filename_alias, filename_alias.replace(" ", "")):
            if (
                len(alias) > longest_match
                and (" " + alias + " ") in video_name
                and key not in title_guess_title
                and key not in title_guess_episode_title
                and alias not in title_guess_title
                and alias not in title_guess_episode_title
            ):
                service = value
                longest_match = len(alias)
    service_longname: str = service
    for key, value in services.items():
        if value == service and len(key) > len(service_longname):
            service_longname = key
    if service_longname in ("Amazon Prime", "Amazon Prime Video"):
        service_longname = "Amazon"
    return service, service_longname
