# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import contextlib
import functools
import importlib
import json
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

GuessitFn = Callable[[str, dict[str, Any] | None], dict[str, Any]]
_guessit_module = importlib.import_module("guessit")
_guessit_fn: GuessitFn = _guessit_module.guessit


def guessit_fn(value: str, options: dict[str, Any] | None = None) -> dict[str, Any]:
    return _guessit_fn(value, options)


@functools.lru_cache(maxsize=1)
def _get_unit3d_default_ids() -> dict[str, Any]:
    json_path = Path(__file__).resolve().parent.parent / "data" / "unit3d_default_ids.json"
    if json_path.exists():
        with contextlib.suppress(Exception), json_path.open(encoding="utf-8") as f:
            return json.load(f)
    return {}


async def get_region(bdinfo: dict[str, Any], region: str | None = None) -> str:
    label = (bdinfo.get("label") or bdinfo.get("title") or bdinfo.get("path") or "").replace(".", " ")
    if region is not None:
        region = region.upper()
    else:
        regions = _get_unit3d_default_ids().get("regions", {})
        for key in regions:
            if f" {key} " in label:
                region = key
                break

    if region is None:
        region = ""
    return region


async def get_distributor(distributor_in: str | None) -> str:
    distributors = _get_unit3d_default_ids().get("distributors", {})
    distributor_out = ""
    if distributor_in is not None and distributor_in not in ["None", ""]:
        target = distributor_in.upper()
        if target in distributors:
            distributor_out = target
        else:
            for each in distributors:
                if target == each.upper():
                    distributor_out = each
                    break
    return distributor_out


async def get_service(
    video: str | None = None, tag: str | None = None, audio: str | None = None, guess_title: str | None = None, get_services_only: bool = False
) -> dict[str, str] | tuple[str, str]:
    services = {
        "9Now": "9NOW",
        "9NOW": "9NOW",
        "A&E": "AE",
        "ABC Australia": "AUBC",
        "ABC": "AMBC",
        "ADN": "ADN",
        "Adult Swim": "AS",
        "AE": "AE",
        "AJAZ": "AJAZ",
        "Al Jazeera English": "AJAZ",
        "ALL4": "ALL4",
        "Amazon Prime": "AMZN",
        "AMBC": "AMBC",
        "AMC": "AMC",
        "America's Test Kitchen": "ATK",
        "AMZN": "AMZN",
        "Animal Planet": "ANPL",
        "Animation Digital Network": "ADN",
        "AnimeLab": "ANLB",
        "ANLB": "ANLB",
        "ANPL": "ANPL",
        "AOL": "AOL",
        "Apple TV": "ATV",
        "Apple TV+": "ATVP",
        "ARD": "ARD",
        "AS": "AS",
        "ATK": "ATK",
        "ATV": "ATV",
        "ATVP": "ATVP",
        "AUBC": "AUBC",
        "BBC iPlayer": "iP",
        "BCORE": "BCORE",
        "BILI": "BILI",
        "Bilibili": "BILI",
        "Binge": "BNGE",
        "BKPL": "BKPL",
        "Blackpills": "BKPL",
        "BluTV": "BLU",
        "BOOM": "BOOM",
        "Boomerang": "BOOM",
        "BP": "BP",
        "Brasil Paralelo": "BP",
        "BRAV": "BRAV",
        "BravoTV": "BRAV",
        "Canal+": "CNLP",
        "Cartoon Network": "CN",
        "CBC": "CBC",
        "CBS": "CBS",
        "CC": "CC",
        "CCGC": "CCGC",
        "Channel 4": "ALL4",
        "CHGD": "CHGD",
        "Chorki": "CRKI",
        "CHRGD": "CHGD",
        "Cinego": "CNGO",
        "Cinemax": "CMAX",
        "CMAX": "CMAX",
        "CMOR": "CMOR",
        "CMT": "CMT",
        "CN": "CN",
        "CNBC": "CNBC",
        "CNGO": "CNGO",
        "CNLP": "CNLP",
        "Comedians in Cars Getting Coffee": "CCGC",
        "Comedy Central": "CC",
        "COOK": "COOK",
        "CORE": "CORE",
        "Country Music Television": "CMT",
        "CR": "CR",
        "Crackle": "CRKL",
        "CRAV": "CRAV",
        "Crave": "CRAV",
        "CRIT": "CRIT",
        "Criterion": "CRIT",
        "CRKI": "CRKI",
        "CRKL": "CRKL",
        "Crunchy Roll": "CR",
        "CSpan": "CSPN",
        "CSPN": "CSPN",
        "CTHP": "CTHP",
        "CTV": "CTV",
        "CUR": "CUR",
        "CuriosityStream": "CUR",
        "CW": "CW",
        "CWS": "CWS",
        "CWSeed": "CWS",
        "Daisuki": "DSKI",
        "DARKROOM": "DARKROOM",
        "DAZN": "DAZN",
        "DC Universe": "DCU",
        "DCU": "DCU",
        "DDY": "DDY",
        "Deadhouse Films": "DHF",
        "DEST": "DEST",
        "DHF": "DHF",
        "Digiturk Diledigin Yerde": "DDY",
        "DISC": "DISC",
        "Discovery Plus": "DSCP",
        "Discovery": "DISC",
        "Disney": "DSNY",
        "Disney+": "DSNP",
        "DIY Network": "DIY",
        "DIY": "DIY",
        "Doc Club": "DOCC",
        "DOCC": "DOCC",
        "DOCPLAY": "DOCPLAY",
        "DPlay": "DPLY",
        "DPLY": "DPLY",
        "DramaFever": "DF",
        "DRPO": "DRPO",
        "DSKI": "DSKI",
        "DSNP": "DSNP",
        "DSNY": "DSNY",
        "DTV": "DTV",
        "E!": "ETV",
        "El Trece": "ETTV",
        "ePix": "EPIX",
        "EPIX": "EPIX",
        "ESPN": "ESPN",
        "ESQ": "ESQ",
        "Esquire": "ESQ",
        "ETTV": "ETTV",
        "ETV": "ETV",
        "Facebook Watch": "FBWatch",
        "FAM": "FAM",
        "Family Jr": "FJR",
        "Fandor": "FANDOR",
        "Filmio": "FMIO",
        "FJR": "FJR",
        "FMIO": "FMIO",
        "Food Network": "FOOD",
        "FOOD": "FOOD",
        "Fox Premium": "FOXP",
        "Fox": "FOX",
        "FOX": "FOX",
        "Foxtel": "FXTL",
        "FPT": "FPT",
        "FREE": "FREE",
        "Freeform": "FREE",
        "FTV": "FTV",
        "FUNi": "FUNI",
        "FUNI": "FUNI",
        "FYI Network": "FYI",
        "FYI": "FYI",
        "GagaOOLala": "Gaga",
        "GC": "GC",
        "GLBL": "GLBL",
        "GLBO": "GLBO",
        "GLOB": "GLOB",
        "Global": "GLBL",
        "Globoplay": "GLBO",
        "GloboSat Play": "GLOB",
        "GO90": "GO90",
        "Hallmark": "HLMK",
        "HBO Go": "HBO",
        "HBO Max": "HMAX",
        "HBO": "HBO",
        "HBOMAX": "HMAX",
        "HGTV": "HGTV",
        "HIDI": "HIDI",
        "HiDive": "HIDI",
        "HIST": "HIST",
        "History": "HIST",
        "HLMK": "HLMK",
        "HMAX": "HMAX",
        "hoichoi": "HoiChoi",
        "HS": "HTSR",
        "HSTR": "Hotstar",
        "HTSR": "HTSR",
        "Hulu": "HULU",
        "HULU": "HULU",
        "ID": "ID",
        "IFC": "IFC",
        "iflix": "IFX",
        "Investigation Discovery": "ID",
        "iP": "iP",
        "iQIYI": "iQIYI",
        "iT": "iT",
        "iTunes": "iT",
        "ITV": "ITV",
        "JOYN": "JOYN",
        "Kanopy": "KNPY",
        "KAYO": "KAYO",
        "KCW": "KCW",
        "KNOW": "KNOW",
        "Knowledge Network": "KNOW",
        "KNPY": "KNPY",
        "Kocowa": "KCW",
        "Kocowa+": "KCW",
        "KS": "KS",
        "Kyivstar TV": "KS",
        "kyivstar": "KS",
        "Kyivstar": "KS",
        "KyivstarTV": "KS",
        "LIFE": "LIFE",
        "Lifetime": "LIFE",
        "LN": "LN",
        "Looke": "LOOKE",
        "LOOKE": "LOOKE",
        "MA": "MA",
        "MAX": "MAX",
        "MBC": "MBC",
        "Megogo": "MGG",
        "MeGoGo": "MGG",
        "MEGOGO": "MGG",
        "MGG": "MGG",
        "MNBC": "MNBC",
        "Motor Trend OnDemand": "MTOD",
        "Movies Anywhere": "MA",
        "MSNBC": "MNBC",
        "MTOD": "MTOD",
        "MTV": "MTV",
        "MUBI": "MUBI",
        "NATG": "NATG",
        "National Audiovisual Institute": "INA",
        "National Film Board": "NFB",
        "National Geographic": "NATG",
        "NBA TV": "NBA",
        "NBA": "NBA",
        "NBC": "NBC",
        "NBLA": "NBLA",
        "Nebula": "NBLA",
        "Netflix": "NF",
        "NF": "NF",
        "NFL Now": "NFLN",
        "NFL": "NFL",
        "NFLN": "NFLN",
        "NHL GameCenter": "GC",
        "NICK": "NICK",
        "Nickelodeon": "NICK",
        "Norsk Rikskringkasting": "NRK",
        "NOW": "NOW",
        "NOWTV": "NOW",
        "NRK": "NRK",
        "OBB Railnet": "RNET",
        "OnDemandKorea": "ODK",
        "Oprah Winfrey Network": "OWN",
        "Opto": "OPTO",
        "ORF ON": "ORF",
        "ORF": "ORF",
        "PA": "PA",
        "PBS Kids": "PBSK",
        "PBS": "PBS",
        "PBSK": "PBSK",
        "PCOK": "PCOK",
        "Peacock": "PCOK",
        "PKO": "PKO",
        "Planeta Kino Online": "PKO",
        "PLAY": "PLAY",
        "Playstation Network": "PSN",
        "PLTV": "PLTV",
        "Pluto TV": "PLTV",
        "PLUZ": "PLUZ",
        "Pluzz": "PLUZ",
        "PMNP": "PMNP",
        "PMNT": "PMNT",
        "PMTP": "PMTP",
        "POGO": "POGO",
        "PokerGO": "POGO",
        "PSN": "PSN",
        "PUHU": "PUHU",
        "QIBI": "QIBI",
        "Rakuten TV": "RKTN",
        "RED": "RED",
        "RKTN": "RKTN",
        "RNET": "RNET",
        "RSTR": "RSTR",
        "RTE One": "RTE",
        "RTE": "RTE",
        "RTL+": "RTLP",
        "RTLP": "RTLP",
        "RUUTU": "RUUTU",
        "SBS": "SBS",
        "Science Channel": "SCI",
        "SeeSo": "SESO",
        "SESO": "SESO",
        "SHMI": "SHMI",
        "SHO": "SHO",
        "Shomi": "SHMI",
        "Showtime": "SHO",
        "SKST": "SKST",
        "SkyShowtime": "SKST",
        "SNET": "SNET",
        "Sony": "SONY",
        "SPIK": "SPIK",
        "Spike TV": "SPKE",
        "Spike": "SPIK",
        "Sportsnet": "SNET",
        "Sprout": "SPRT",
        "SPRT": "SPRT",
        "Stan": "STAN",
        "STAN": "STAN",
        "Star+": "STRP",
        "STARZ": "STARZ",
        "Starz": "STZ",
        "STRP": "STRP",
        "STZ": "STZ",
        "Sveriges Television": "SVT",
        "SVT": "SVT",
        "SwearNet": "SWER",
        "SWEET": "SWEET",
        "SWER": "SWER",
        "Syfy": "SYFY",
        "SYFY": "SYFY",
        "takflix": "TF",
        "Takflix": "TF",
        "TBS": "TBS",
        "TEN": "TEN",
        "TF": "TF",
        "TFou": "TFOU",
        "TFOU": "TFOU",
        "The CW": "CW",
        "The Roku Channel": "ROKU",
        "TIMV": "TIMV",
        "TIMvision": "TIMV",
        "TLC": "TLC",
        "TOU": "TOU",
        "TRVL": "TRVL",
        "TUBI": "TUBI",
        "TubiTV": "TUBI",
        "TV Land": "TVL",
        "TV2": "TV2",
        "TV3 Ireland": "TV3",
        "TV3": "TV3",
        "TV4 Sweeden": "TV4",
        "TV4": "TV4",
        "TVING": "TVING",
        "TVL": "TVL",
        "TVNZ": "TVNZ",
        "UFC Fight Pass": "FP",
        "UFC": "UFC",
        "UKTV": "UKTV",
        "UNIV": "UNIV",
        "Univer Vídeo": "UNVD",
        "Univision": "UNIV",
        "UNVD": "UNVD",
        "USA Network": "USAN",
        "USAN": "USAN",
        "Velocity": "VLCT",
        "VH1": "VH1",
        "VIAP": "VIAP",
        "VICE": "VICE",
        "Viceland": "VICE",
        "Viki": "VIKI",
        "VIMEO": "VIMEO",
        "Vimeo": "VMEO",
        "Vivamax": "VMAX",
        "Vivaone": "VONE",
        "VLCT": "VLCT",
        "VMAX": "VMAX",
        "VMEO": "VMEO",
        "VONE": "VONE",
        "VRV": "VRV",
        "VUDU": "VUDU",
        "W Network": "WNET",
        "WatchMe": "WME",
        "WME": "WME",
        "WNET": "WNET",
        "WOW Presents Plus": "WOWP",
        "WOWP": "WOWP",
        "WWE Network": "WWEN",
        "WWEN": "WWEN",
        "Xbox Video": "XBOX",
        "XBOX": "XBOX",
        "XUMO": "XUMO",
        "Yahoo": "YHOO",
        "YHOO": "YHOO",
        "YouTube Red": "RED",
        "YT": "YT",
        "ZDF": "ZDF",
    }

    if get_services_only:
        return services

    if video is None:
        return "", ""

    guess_data = guessit_fn(video)
    service: str = str(guess_data.get("streaming_service", ""))

    video_name = re.sub(r"[.()]", " ", video.replace(tag or "", "").replace(guess_title or "", ""))
    if audio and "DTS-HD MA" in audio:
        video_name = video_name.replace("DTS-HD.MA.", "").replace("DTS-HD MA ", "")
    title_guess = guessit_fn(video, {"excludes": ["country", "language"]})
    title_guess_title = str(title_guess.get("title", ""))
    for key, value in services.items():
        if ((" " + key + " ") in video_name and key not in title_guess_title) or key == service:
            service = value
    service_longname: str = service
    for key, value in services.items():
        if value == service and len(key) > len(service_longname):
            service_longname = key
    if service_longname == "Amazon Prime":
        service_longname = "Amazon"
    return service, service_longname
