# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import importlib
import re
from collections.abc import Callable
from typing import Any

GuessitFn = Callable[[str, dict[str, Any] | None], dict[str, Any]]
_guessit_module = importlib.import_module("guessit")
_guessit_fn: GuessitFn = _guessit_module.guessit


def guessit_fn(value: str, options: dict[str, Any] | None = None) -> dict[str, Any]:
    return _guessit_fn(value, options)


async def get_region(bdinfo: dict[str, Any], region: str | None = None) -> str:
    label = (bdinfo.get("label") or bdinfo.get("title") or bdinfo.get("path") or "").replace(".", " ")
    if region is not None:
        region = region.upper()
    else:
        regions = {
            "AFG": "AFG",
            "AIA": "AIA",
            "ALA": "ALA",
            "ALG": "ALG",
            "AND": "AND",
            "ANG": "ANG",
            "ARG": "ARG",
            "ARM": "ARM",
            "ARU": "ARU",
            "ASA": "ASA",
            "ATA": "ATA",
            "ATF": "ATF",
            "ATG": "ATG",
            "AUS": "AUS",
            "AUT": "AUT",
            "AZE": "AZE",
            "BAH": "BAH",
            "BAN": "BAN",
            "BDI": "BDI",
            "BEL": "BEL",
            "BEN": "BEN",
            "BER": "BER",
            "BES": "BES",
            "BFA": "BFA",
            "BHR": "BHR",
            "BHU": "BHU",
            "BIH": "BIH",
            "BLM": "BLM",
            "BLR": "BLR",
            "BLZ": "BLZ",
            "BOL": "BOL",
            "BOT": "BOT",
            "BRA": "BRA",
            "BRB": "BRB",
            "BRU": "BRU",
            "BVT": "BVT",
            "CAM": "CAM",
            "CAN": "CAN",
            "CAY": "CAY",
            "CCK": "CCK",
            "CEE": "CEE",
            "CGO": "CGO",
            "CHA": "CHA",
            "CHI": "CHI",
            "CHN": "CHN",
            "CIV": "CIV",
            "CMR": "CMR",
            "COD": "COD",
            "COK": "COK",
            "COL": "COL",
            "COM": "COM",
            "CPV": "CPV",
            "CRC": "CRC",
            "CRO": "CRO",
            "CTA": "CTA",
            "CUB": "CUB",
            "CUW": "CUW",
            "CXR": "CXR",
            "CYP": "CYP",
            "DJI": "DJI",
            "DMA": "DMA",
            "DOM": "DOM",
            "ECU": "ECU",
            "EGY": "EGY",
            "ENG": "ENG",
            "EQG": "EQG",
            "ERI": "ERI",
            "ESH": "ESH",
            "ESP": "ESP",
            "ETH": "ETH",
            "EUR": "EUR",
            "FIJ": "FIJ",
            "FLK": "FLK",
            "FRA": "FRA",
            "FRO": "FRO",
            "FSM": "FSM",
            "GAB": "GAB",
            "GAM": "GAM",
            "GBR": "GBR",
            "GEO": "GEO",
            "GER": "GER",
            "GGY": "GGY",
            "GHA": "GHA",
            "GIB": "GIB",
            "GLP": "GLP",
            "GNB": "GNB",
            "GRE": "GRE",
            "GRL": "GRL",
            "GRN": "GRN",
            "GUA": "GUA",
            "GUF": "GUF",
            "GUI": "GUI",
            "GUM": "GUM",
            "GUY": "GUY",
            "HAI": "HAI",
            "HKG": "HKG",
            "HMD": "HMD",
            "HON": "HON",
            "HUN": "HUN",
            "IDN": "IDN",
            "IMN": "IMN",
            "IND": "IND",
            "IOT": "IOT",
            "IRL": "IRL",
            "IRN": "IRN",
            "IRQ": "IRQ",
            "ISL": "ISL",
            "ISR": "ISR",
            "ITA": "ITA",
            "JAM": "JAM",
            "JEY": "JEY",
            "JOR": "JOR",
            "JPN": "JPN",
            "KAZ": "KAZ",
            "KEN": "KEN",
            "KGZ": "KGZ",
            "KIR": "KIR",
            "KNA": "KNA",
            "KOR": "KOR",
            "KSA": "KSA",
            "KUW": "KUW",
            "KVX": "KVX",
            "LAO": "LAO",
            "LBN": "LBN",
            "LBR": "LBR",
            "LBY": "LBY",
            "LCA": "LCA",
            "LES": "LES",
            "LIE": "LIE",
            "LKA": "LKA",
            "LUX": "LUX",
            "MAC": "MAC",
            "MAD": "MAD",
            "MAF": "MAF",
            "MAR": "MAR",
            "MAS": "MAS",
            "MDA": "MDA",
            "MDV": "MDV",
            "MEX": "MEX",
            "MHL": "MHL",
            "MKD": "MKD",
            "MLI": "MLI",
            "MLT": "MLT",
            "MNG": "MNG",
            "MNP": "MNP",
            "MON": "MON",
            "MOZ": "MOZ",
            "MRI": "MRI",
            "MSR": "MSR",
            "MTN": "MTN",
            "MTQ": "MTQ",
            "MWI": "MWI",
            "MYA": "MYA",
            "MYT": "MYT",
            "NAM": "NAM",
            "NCA": "NCA",
            "NCL": "NCL",
            "NEP": "NEP",
            "NFK": "NFK",
            "NIG": "NIG",
            "NIR": "NIR",
            "NIU": "NIU",
            "NLD": "NLD",
            "NOR": "NOR",
            "NRU": "NRU",
            "NZL": "NZL",
            "OMA": "OMA",
            "PAK": "PAK",
            "PAN": "PAN",
            "PAR": "PAR",
            "PCN": "PCN",
            "PER": "PER",
            "PHI": "PHI",
            "PLE": "PLE",
            "PLW": "PLW",
            "PNG": "PNG",
            "POL": "POL",
            "POR": "POR",
            "PRK": "PRK",
            "PUR": "PUR",
            "QAT": "QAT",
            "REU": "REU",
            "ROU": "ROU",
            "RSA": "RSA",
            "RUS": "RUS",
            "RWA": "RWA",
            "SAM": "SAM",
            "SCO": "SCO",
            "SDN": "SDN",
            "SEN": "SEN",
            "SEY": "SEY",
            "SGS": "SGS",
            "SHN": "SHN",
            "SIN": "SIN",
            "SJM": "SJM",
            "SLE": "SLE",
            "SLV": "SLV",
            "SMR": "SMR",
            "SOL": "SOL",
            "SOM": "SOM",
            "SPM": "SPM",
            "SRB": "SRB",
            "SSD": "SSD",
            "STP": "STP",
            "SUI": "SUI",
            "SUR": "SUR",
            "SWZ": "SWZ",
            "SXM": "SXM",
            "SYR": "SYR",
            "TAH": "TAH",
            "TAN": "TAN",
            "TCA": "TCA",
            "TGA": "TGA",
            "THA": "THA",
            "TJK": "TJK",
            "TKL": "TKL",
            "TKM": "TKM",
            "TLS": "TLS",
            "TOG": "TOG",
            "TRI": "TRI",
            "TUN": "TUN",
            "TUR": "TUR",
            "TUV": "TUV",
            "TWN": "TWN",
            "UAE": "UAE",
            "UGA": "UGA",
            "UKR": "UKR",
            "UMI": "UMI",
            "URU": "URU",
            "USA": "USA",
            "UZB": "UZB",
            "VAN": "VAN",
            "VAT": "VAT",
            "VEN": "VEN",
            "VGB": "VGB",
            "VIE": "VIE",
            "VIN": "VIN",
            "VIR": "VIR",
            "WAL": "WAL",
            "WLF": "WLF",
            "YEM": "YEM",
            "ZAM": "ZAM",
            "ZIM": "ZIM",
        }
        for key, value in regions.items():
            if f" {key} " in label:
                region = value

    if region is None:
        region = ""
    return region


async def get_distributor(distributor_in: str | None) -> str:
    distributor_list = [
        "@ANIME",
        "01 DISTRIBUTION",
        "100 DESTINATIONS TRAVEL FILM",
        "101 FILMS",
        "1FILMS",
        "2 ENTERTAIN VIDEO",
        "20TH CENTURY FOX",
        "2L",
        "3D CONTENT HUB",
        "3D MEDIA",
        "3L FILM",
        "3RD WINDOW FILMS",
        "3RD WINDOW",
        "4DIGITAL",
        "4DVD",
        "4K UHD",
        "4K ULTRA HD MOVIES",
        "8-FILMS",
        "84 ENTERTAINMENT",
        "88 FILMS",
        "A CONTRACORRIENTE FILMS",
        "A CONTRACORRIENTE",
        "A-FILM",
        "A&E HOME VIDEO",
        "A&E",
        "A&M RECORDS",
        "A+E NETWORKS",
        "A+R",
        "AAA",
        "AB VIDEO",
        "AB VIDÉO",
        "ABC - (AUSTRALIAN BROADCASTING CORPORATION)",
        "ABC",
        "ABKCO",
        "ABSOLUT MEDIEN",
        "ABSOLUTE",
        "ACCENT FILM ENTERTAINMENT",
        "ACCENTUS",
        "ACORN MEDIA",
        "AD VITAM",
        "ADA",
        "ADITYA VIDEOS",
        "ADSO FILMS",
        "AFM RECORDS",
        "AGFA",
        "AIX RECORDS",
        "ALAMODE FILM",
        "ALBA RECORDS",
        "ALBANY RECORDS",
        "ALBATROS",
        "ALCHEMY",
        "ALIVE",
        "ALL ANIME",
        "ALL INTERACTIVE ENTERTAINMENT",
        "ALLEGRO",
        "ALLIANCE",
        "ALPHA MUSIC",
        "ALTERDYSTRYBUCJA",
        "ALTERED INNOCENCE",
        "ALTITUDE FILM DISTRIBUTION",
        "ALUCARD RECORDS",
        "AMAZING D.C.",
        "AMAZING DC",
        "AMMO CONTENT",
        "AMUSE SOFT ENTERTAINMENT",
        "ANCHOR BAY",
        "ANCONNECT",
        "ANEC",
        "ANIMATSU",
        "ANIME HOUSE",
        "ANIME LTD",
        "ANIME WORKS",
        "ANIME",
        "ANIMEIGO",
        "ANIPLEX",
        "ANOLIS ENTERTAINMENT",
        "ANOTHER WORLD ENTERTAINMENT",
        "AP INTERNATIONAL",
        "APPLE",
        "ARA MEDIA",
        "ARBELOS",
        "ARC ENTERTAINMENT",
        "ARISTA BMG",
        "ARISTA",
        "ARISTA/BMG",
        "ARISTABMG",
        "ARP SELECTION",
        "ARP SÉLECTION",
        "ARROW",
        "ART SERVICE",
        "ART VISION",
        "ARTE EDITIONS",
        "ARTE ÉDITIONS",
        "ARTE VIDEO",
        "ARTE VIDÉO",
        "ARTHAUS MUSIK",
        "ARTIFICIAL EYE",
        "ARTSPLOITATION FILMS",
        "ARTUS FILMS",
        "ASCOT ELITE HOME ENTERTAINMENT",
        "ASIA VIDEO",
        "ASMIK ACE",
        "ASTRO RECORDS & FILMWORKS",
        "ASYLUM",
        "ATLANTIC FILM",
        "ATLANTIC RECORDS",
        "ATLAS FILM",
        "AUDIO VISUAL ENTERTAINMENT",
        "AURO-3D CREATIVE LABEL",
        "AURUM",
        "AV VISIONEN",
        "AV-JET",
        "AVALON",
        "AVENTI",
        "AVEX TRAX",
        "AXIOM",
        "AXIS RECORDS",
        "AYNGARAN",
        "BAC FILMS",
        "BACH FILMS",
        "BANDAI VISUAL",
        "BARCLAY",
        "BBC",
        "BBI FILMS",
        "BBI",
        "BCI HOME ENTERTAINMENT",
        "BEGGARS BANQUET",
        "BEL AIR CLASSIQUES",
        "BELGA FILMS",
        "BELVEDERE",
        "BENELUX FILM DISTRIBUTORS",
        "BENNETT-WATT MEDIA",
        "BERLIN CLASSICS",
        "BERLINER PHILHARMONIKER RECORDINGS",
        "BEST ENTERTAINMENT",
        "BEYOND HOME ENTERTAINMENT",
        "BFI VIDEO",
        "BFI",
        "BFS ENTERTAINMENT",
        "BFS",
        "BHAVANI",
        "BIBER RECORDS",
        "BIG HOME VIDEO",
        "BILDSTORUNG",
        "BILDSTÖRUNG",
        "BILL ZEBUB",
        "BIRNENBLATT",
        "BIT WEL",
        "BLACK BOX",
        "BLACK HILL PICTURES",
        "BLACK HILL",
        "BLACK HOLE RECORDINGS",
        "BLACK HOLE",
        "BLAQOUT",
        "BLAUFIELD MUSIC",
        "BLAUFIELD",
        "BLOCKBUSTER ENTERTAINMENT",
        "BLOCKBUSTER",
        "BLU PHASE MEDIA",
        "BLU-RAY ONLY",
        "BLU-RAY",
        "BLU",
        "BLUE GENTIAN RECORDS",
        "BLUE KINO",
        "BLUE UNDERGROUND",
        "BLURAY ONLY",
        "BLURAY",
        "BMG ARISTA",
        "BMG",
        "BMG/ARISTA",
        "BMGARISTA",
        "BONTON FILM",
        "BONTON",
        "BOOMERANG PICTURES",
        "BOOMERANG",
        "BQHL EDITIONS",
        "BQHL ÉDITIONS",
        "BQHL",
        "BREAKING GLASS",
        "BRIDGESTONE",
        "BRINK",
        "BRITISH BROADCASTING CORPORATION",
        "BRITISH FILM INSTITUTE",
        "BROAD GREEN PICTURES",
        "BROAD GREEN",
        "BUENA VISTA",
        "BUSCH MEDIA GROUP",
        "BUSCH",
        "C MAJOR",
        "C.B.S.",
        "CAICHANG",
        "CALIFORNIA FILMES",
        "CALIFÓRNIA FILMES",
        "CALIFORNIA",
        "CAMEO",
        "CAMERA OBSCURA",
        "CAMERATA",
        "CAMP MOTION PICTURES",
        "CAMP MOTION",
        "CAPELIGHT PICTURES",
        "CAPELIGHT",
        "CAPITOL RECORDS",
        "CAPITOL",
        "CAPRICCI",
        "CARGO RECORDS",
        "CARLOTA",
        "CARLOTTA FILMS",
        "CARLOTTA",
        "CARMEN FILM",
        "CASCADE",
        "CATCHPLAY",
        "CAULDRON FILMS",
        "CAULDRON",
        "CBS TELEVISION STUDIOS",
        "CBS",
        "CC",
        "CCTV",
        "CCV ENTERTAINMENT",
        "CCV",
        "CD BABY",
        "CD LAND",
        "CECCHI GORI",
        "CENTURY MEDIA",
        "Che Ku Yu Le",
        "CHUAN XUN SHI DAI MULTIMEDIA",
        "CINE-ASIA",
        "CINEART",
        "CINÉART",
        "CINEDIGM",
        "CINEFIL IMAGICA",
        "CINEMA EPOCH",
        "CINEMA GUILD",
        "CINEMA LIBRE STUDIOS",
        "CINEMA MONDO",
        "CINEMATIC VISION",
        "CINEPLOIT RECORDS",
        "CINESTRANGE EXTREME",
        "CITEL VIDEO",
        "CITEL",
        "CJ ENTERTAINMENT",
        "CJ",
        "CLASSIC MEDIA",
        "CLASSICFLIX",
        "CLASSICLINE",
        "CLAUDIO RECORDS",
        "CLEAR VISION",
        "CLEOPATRA",
        "CLOSE UP",
        "CMS MEDIA LIMITED",
        "CMV LASERVISION",
        "CN ENTERTAINMENT",
        "CODE RED",
        "COHEN MEDIA GROUP",
        "COHEN",
        "COIN DE MIRE CINEMA",
        "COIN DE MIRE CINÉMA",
        "COLOSSEO FILM",
        "COLUMBIA PICTURES",
        "COLUMBIA",
        "COLUMBIA/TRI-STAR",
        "COMMERCIAL MARKETING",
        "CONCORD MUSIC GROUP",
        "CONCORDE VIDEO",
        "CONDOR",
        "CONSTANTIN FILM",
        "CONSTANTIN",
        "CONSTANTINO FILMES",
        "CONSTANTINO",
        "CONSTRUCTIVE MEDIA SERVICE",
        "CONSTRUCTIVE",
        "CONTENT ZONE",
        "CONTENTS GATE",
        "COQUEIRO VERDE",
        "CORNERSTONE MEDIA",
        "CORNERSTONE",
        "CP DIGITAL",
        "CREST MOVIES",
        "CRITERION COLLECTION",
        "CRITERION",
        "CRYSTAL CLASSICS",
        "CULT EPICS",
        "CULT FILMS",
        "CULT VIDEO",
        "CURZON FILM WORLD",
        "D AILLY COMPANY",
        "D AILLY",
        "D FILMS",
        "D'AILLY COMPANY",
        "D'AILLY",
        "DA CAPO",
        "DA MUSIC",
        "DAILLY COMPANY",
        "DAILLY",
        "DALL ANGELO PICTURES",
        "DALL ANGELO",
        "DALL'ANGELO PICTURES",
        "DALL'ANGELO",
        "DALLANGELO PICTURES",
        "DAREDO",
        "DARK FORCE ENTERTAINMENT",
        "DARK FORCE",
        "DARK SIDE RELEASING",
        "DARK SIDE",
        "DAZZLER MEDIA",
        "DAZZLER",
        "DCM PICTURES",
        "DCM",
        "DEAPLANETA",
        "DECCA",
        "DEEPJOY",
        "DEFIANT SCREEN ENTERTAINMENT",
        "DEFIANT SCREEN",
        "DEFIANT",
        "DELOS",
        "DELPHIAN RECORDS",
        "DELPHIAN",
        "DELTA MUSIC & ENTERTAINMENT",
        "DELTA MUSIC AND ENTERTAINMENT",
        "DELTA MUSIC ENTERTAINMENT",
        "DELTA MUSIC",
        "DELTAMAC CO LTD",
        "DELTAMAC CO. LTD.",
        "DELTAMAC CO",
        "DELTAMAC",
        "DEMAND MEDIA",
        "DEMAND",
        "DEP",
        "DEUTSCHE GRAMMOPHON",
        "DFW",
        "DGM",
        "DIAPHANA",
        "DIGIDREAMS STUDIOS",
        "DIGIDREAMS",
        "DIGITAL ENVIRONMENTS",
        "DIGITAL",
        "DISCOTEK MEDIA",
        "DISCOVERY CHANNEL",
        "DISCOVERY",
        "DISK KINO",
        "DISNEY / BUENA VISTA",
        "DISNEY BUENA VISTA",
        "DISNEY",
        "DISTRIBUTION SELECT",
        "DIVISA",
        "DNC ENTERTAINMENT",
        "DNC",
        "DOGWOOF",
        "DOLMEN HOME VIDEO",
        "DOLMEN",
        "DONAU FILM",
        "DONAU",
        "DORADO FILMS",
        "DORADO",
        "DRAFTHOUSE FILMS",
        "DRAFTHOUSE",
        "DRAGON ENTERTAINMENT",
        "DRAGON FILM ENTERTAINMENT",
        "DRAGON FILM",
        "DRAGON",
        "DREAMWORKS",
        "DRIVE ON RECORDS",
        "DRIVE ON",
        "DRIVE-ON",
        "DRIVEON",
        "DS MEDIA",
        "DTP AG",
        "DTP ENTERTAINMENT AG",
        "DTP ENTERTAINMENT",
        "DTP",
        "DTS ENTERTAINMENT",
        "DTS",
        "DUKE MARKETING",
        "DUKE VIDEO DISTRIBUTION",
        "DUKE",
        "DUTCH FILMWORKS",
        "DUTCH",
        "DVD INTERNATIONAL",
        "DVD",
        "DYBEX",
        "DYNAMIC",
        "DYNIT",
        "E1 ENTERTAINMENT",
        "E1",
        "EAGLE ENTERTAINMENT",
        "EAGLE HOME ENTERTAINMENT PVT LTD",
        "EAGLE HOME ENTERTAINMENT PVT.LTD.",
        "EAGLE HOME ENTERTAINMENT PVTLTD",
        "EAGLE HOME ENTERTAINMENT",
        "EAGLE PICTURES",
        "EAGLE ROCK ENTERTAINMENT",
        "EAGLE ROCK",
        "EAGLE VISION MEDIA",
        "EAGLE VISION",
        "EARMUSIC",
        "EARTH ENTERTAINMENT",
        "EARTH",
        "ECHO BRIDGE ENTERTAINMENT",
        "ECHO BRIDGE",
        "EDEL GERMANY GMBH",
        "EDEL GERMANY",
        "EDEL RECORDS",
        "EDITION TONFILM",
        "EDITIONS MONTPARNASSE",
        "EDKO FILMS LTD.",
        "EDKO FILMS LTD",
        "EDKO FILMS",
        "EDKO",
        "EIN'S M&M CO",
        "EIN'S M&M",
        "EINS M&M CO",
        "EINS M&M",
        "ELEA MEDIA",
        "ELEA-MEDIA",
        "ELEA",
        "ELECTRIC PICTURE",
        "ELECTRIC",
        "ELEPHANT FILMS",
        "ELEPHANT",
        "ELEVATION",
        "EMI",
        "EMON",
        "EMS",
        "EMYLIA",
        "ENE MEDIA",
        "ENE",
        "ENTERTAINMENT IN VIDEO",
        "ENTERTAINMENT IN",
        "ENTERTAINMENT ONE CANADA INC",
        "ENTERTAINMENT ONE CANADA",
        "ENTERTAINMENT ONE FILMS CANADA INC.",
        "ENTERTAINMENT ONE FILMS CANADA INC",
        "ENTERTAINMENT ONE FILMS CANADA",
        "ENTERTAINMENT ONE",
        "ENTERTAINMENTONE",
        "EONE",
        "EOS",
        "EPIC PICTURES",
        "EPIC RECORDS",
        "EPIC",
        "ERATO",
        "EROS",
        "ESC EDITIONS",
        "ESCAPI MEDIA BV",
        "ESOTERIC RECORDINGS",
        "ESPN FILMS",
        "EUREKA ENTERTAINMENT",
        "EUREKA",
        "EURO PICTURES",
        "EURO VIDEO",
        "EUROARTS",
        "EUROPA FILMES",
        "EUROPA",
        "EUROPACORP",
        "EUROZOOM",
        "EXCEL",
        "EXPLOSIVE MEDIA",
        "EXPLOSIVE",
        "EXTRALUCID FILMS",
        "EXTRALUCID",
        "EYE SEE MOVIES",
        "EYE SEE",
        "EYK MEDIA",
        "EYK",
        "FABULOUS FILMS",
        "FABULOUS",
        "FACTORIS FILMS",
        "FACTORIS",
        "FARAO RECORDS",
        "FARBFILM ENTERTAINMENT",
        "FARBFILM HOME ENTERTAINMENT",
        "FARBFILM HOME",
        "FARBFILM",
        "FEELGOOD ENTERTAINMENT",
        "FEELGOOD",
        "FERNSEHJUWELEN",
        "FILM CHEST",
        "FILM DETECTIVE",
        "FILM MEDIA",
        "FILM MOVEMENT",
        "FILM4",
        "FILMART",
        "FILMAURO",
        "FILMAX",
        "FILMCONFECT ENTERTAINMENT",
        "FILMCONFECT HOME ENTERTAINMENT",
        "FILMCONFECT HOME",
        "FILMCONFECT",
        "FILMEDIA",
        "FILMJUWELEN",
        "FILMOTEKA NARODAWA",
        "FILMRISE",
        "FINAL CUT ENTERTAINMENT",
        "FINAL CUT",
        "FIREHOUSE 12 RECORDS",
        "FIREHOUSE 12",
        "FIRST INTERNATIONAL PRODUCTION",
        "FIRST INTERNATIONAL",
        "FIRST LOOK STUDIOS",
        "FIRST LOOK",
        "FLAGMAN TRADE",
        "FLASHSTAR FILMES",
        "FLASHSTAR",
        "FLICKER ALLEY",
        "FNC ADD CULTURE",
        "FOCUS FILMES",
        "FOCUS",
        "FOKUS MEDIA",
        "FOKUSA",
        "FOX EUROPA",
        "FOX MGM",
        "FOX PATHE EUROPA",
        "FOX PATHE",
        "FOX",
        "FOX/MGM",
        "FPE",
        "FRANCE TELEVISIONS DISTRIBUTION",
        "FRANCE TÉLÉVISIONS DISTRIBUTION",
        "FRANCE TELEVISIONS",
        "FRANCE",
        "FREE DOLPHIN ENTERTAINMENT",
        "FREE DOLPHIN",
        "FREESTYLE DIGITAL MEDIA",
        "FREESTYLE DIGITAL",
        "FREESTYLE",
        "FREMANTL",
        "FREMANTLE ENTERTAINMENT",
        "FREMANTLE HOME ENTERTAINMENT",
        "FREMANTLE HOME",
        "FRENETIC FILMS",
        "FRENETIC",
        "FRONTIER WORKS",
        "FRONTIER",
        "FRONTIERS MUSIC",
        "FRONTIERS RECORDS",
        "FS FILM OY",
        "FS FILM",
        "FULL MOON FEATURES",
        "FULL MOON",
        "FUN CITY EDITIONS",
        "FUN CITY",
        "FUNIMATION ENTERTAINMENT",
        "FUNIMATION",
        "FUSION",
        "FUTUREFILM",
        "G2 PICTURES",
        "G2",
        "GAGA COMMUNICATIONS",
        "GAGA",
        "GAIAM",
        "GALAPAGOS",
        "GAMMA ENTERTAINMENT",
        "GAMMA HOME ENTERTAINMENT",
        "GAMMA HOME",
        "GAMMA",
        "GARAGEHOUSE PICTURES",
        "GARAGEHOUSE",
        "GARAGEPLAY (Che Ku Yu Le )",
        "GARAGEPLAY (車庫娛樂)",
        "GARAGEPLAY",
        "GAUMONT",
        "GEFFEN",
        "GENEON ENTERTAINMENT",
        "GENEON UNIVERSAL ENTERTAINMENT",
        "GENEON",
        "GENERAL VIDEO RECORDING",
        "GHIBLI",
        "GLASS DOLL FILMS",
        "GLASS DOLL",
        "GLOBE MEDIA",
        "GLOBE MUSIC MEDIA",
        "GLOBE MUSIC",
        "GLOBE",
        "GO ENTERTAIN",
        "GO",
        "GOLDEN HARVEST",
        "GOOD MOVIES",
        "GOOD! MOVIES",
        "GOOD!MOVIES",
        "GRAPEVINE VIDEO",
        "GRAPEVINE",
        "GRASSHOPPER FILM",
        "GRASSHOPPER FILMS",
        "GRASSHOPPER",
        "GRAVITAS VENTURES",
        "GRAVITAS",
        "GREAT MOVIES",
        "GREAT",
        "GREEN APPLE ENTERTAINMENT",
        "GREEN APPLE",
        "GREEN ENTERTAINMENT",
        "GREEN",
        "GREENNARAE MEDIA",
        "GREENNARAE",
        "GRIND HOUSE",
        "GRINDHOUSE RELEASING",
        "GRINDHOUSE",
        "GRYPHON ENTERTAINMENT",
        "GRYPHON",
        "GUNPOWDER & SKY",
        "GUNPOWDER + SKY",
        "GUNPOWDER AND SKY",
        "GUNPOWDER SKY",
        "GUNPOWDER",
        "HAMBURG ENTERPRISES",
        "HAMBURG",
        "HAMBURGER MEDIEN HAUS",
        "HANABEE ENTERTAINMENT",
        "HANABEE",
        "HANNOVER HOUSE",
        "HANNOVER",
        "HANNSLER CLASSIC",
        "HÄNNSLER CLASSIC",
        "HANNSLER",
        "HANSE SOUND",
        "HANSE",
        "HANSESOUND",
        "HAPPINET",
        "HARMONIA MUNDI",
        "HARMONIA",
        "HBO",
        "HDC",
        "HEC",
        "HELL & BACK RECORDINGS",
        "HELL & BACK",
        "HELL AND BACK RECORDINGS",
        "HELL AND BACK",
        "HEN'S TOOTH VIDEO",
        "HEN'S TOOTH",
        "HENS TOOTH VIDEO",
        "HENS TOOTH",
        "HIGH FLIERS",
        "HIGHLIGHT",
        "HILLSONG",
        "HISTORY CHANNEL",
        "HISTORY",
        "HK VIDEO",
        "HK VIDÉO",
        "HK",
        "HMH HAMBURGER MEDIEN HAUS",
        "HMH HAMBURGER MEDIEN",
        "HMH HAMBURGER",
        "HMH",
        "HOLLYWOOD CLASSIC ENTERTAINMENT",
        "HOLLYWOOD CLASSIC",
        "HOLLYWOOD PICTURES",
        "HOLLYWOOD",
        "HOPSCOTCH ENTERTAINMENT",
        "HOPSCOTCH",
        "HPM",
        "I CATCHER",
        "I ON NEW MEDIA",
        "I-CATCHER",
        "I-ON NEW MEDIA",
        "I-ON",
        "IAN PRODUCTIONS",
        "IAN",
        "ICATCHER",
        "ICESTORM",
        "ICON DISTRIBUTION",
        "ICON FILM DISTRIBUTION",
        "ICON FILM",
        "ICON",
        "IDEALE AUDIENCE",
        "IDEALE",
        "IFC FILMS",
        "IFC",
        "IFILM",
        "ILLUSIONS UNLTD.",
        "ILLUSIONS UNLTD",
        "ILLUSIONS",
        "IMAGE ENTERTAINMENT",
        "IMAGE",
        "IMAGEM FILMES",
        "IMAGEM",
        "IMOVISION",
        "IMPERIAL CINEPIX",
        "IMPRINT",
        "IMPULS ENTERTAINMENT",
        "IMPULS HOME ENTERTAINMENT",
        "IMPULS HOME",
        "IMPULS",
        "IN AKUSTIK",
        "IN-AKUSTIK",
        "INAKUSTIK",
        "INCEPTION GROUP",
        "INCEPTION MEDIA GROUP",
        "INCEPTION MEDIA",
        "INCEPTION",
        "INDEPENDENT",
        "INDICAN",
        "INDIE RIGHTS",
        "INDIE",
        "INDIGO",
        "INFO",
        "INJOINGAN",
        "INKED PICTURES",
        "INKED",
        "INSIDE MUSIC",
        "INSIDE OUT MUSIC",
        "INSIDE OUT",
        "INSIDE",
        "INTERCOM",
        "INTERCONTINENTAL VIDEO",
        "INTERCONTINENTAL",
        "INTERGROOVE",
        "INTERSCOPE",
        "INVINCIBLE PICTURES",
        "INVINCIBLE",
        "ION MEDIA",
        "ION NEW MEDIA",
        "ION",
        "ISLAND & MERCURY",
        "ISLAND AND MERCURY",
        "ISLAND MERCURY",
        "ISLAND",
        "ISLAND/MERCURY",
        "ISLANDMERCURY",
        "ITN",
        "ITV DVD",
        "ITV",
        "IVC",
        "IVE ENTERTAINMENT",
        "IVE",
        "J&R ADVENTURES",
        "J&R",
        "JAKOB",
        "JOKERS",
        "JONU MEDIA",
        "JONU",
        "JR",
        "JRB PRODUCTIONS",
        "JRB",
        "JUST BRIDGE ENTERTAINMENT",
        "JUST BRIDGE",
        "JUST ENTERTAINMENT",
        "JUST",
        "KABOOM ENTERTAINMENT",
        "KABOOM",
        "KADOKAWA ENTERTAINMENT",
        "KADOKAWA",
        "KAIROS",
        "KALEIDOSCOPE ENTERTAINMENT",
        "KALEIDOSCOPE",
        "KAM & RONSON ENTERPRISES",
        "KAM & RONSON",
        "KAM AND RONSON ENTERPRISES",
        "KAM AND RONSON",
        "KAM&RONSON ENTERPRISES",
        "KAM&RONSON",
        "KANA HOME VIDEO",
        "KARMA FILMS",
        "KARMA",
        "KATZENBERGER",
        "KAZE",
        "KBS MEDIA",
        "KBS",
        "KD MEDIA",
        "KD",
        "KING MEDIA",
        "KING RECORDS",
        "KING",
        "KINO LORBER",
        "KINO SWIAT",
        "KINO",
        "KINOKUNIYA",
        "KINOWELT DVD",
        "KINOWELT ENTERTAINMENT",
        "KINOWELT ENTERTAINMENT/DVD",
        "KINOWELT HOME DVD",
        "KINOWELT HOME ENTERTAINMENT",
        "KINOWELT HOME ENTERTAINMENT/DVD",
        "KINOWELT",
        "KIT PARKER FILMS",
        "KIT PARKER",
        "KITTY MEDIA",
        "KNM ENTERTAINMENT",
        "KNM HOME ENTERTAINMENT",
        "KNM HOME",
        "KNM",
        "KOBA FILMS",
        "KOBA",
        "KOCH ENTERTAINMENT",
        "KOCH MEDIA",
        "KOCH",
        "KRAKEN RELEASING",
        "KRAKEN",
        "KSCOPE",
        "KSM",
        "KULTUR",
        "L ATELIER D IMAGES",
        "L ATELIER D'IMAGES",
        "L ATELIER",
        "L'ATELIER D IMAGES",
        "L'ATELIER D'IMAGES",
        "L'ATELIER DIMAGES",
        "L'ATELIER",
        "LA AVENTURA AUDIOVISUAL",
        "LA AVENTURA",
        "LACE GROUP",
        "LACE",
        "LASER PARADISE",
        "LATELIER D'IMAGES",
        "LATELIER DIMAGES",
        "LATELIER",
        "LAYONS",
        "LCJ EDITIONS",
        "LCJ",
        "LE CHAT QUI FUME",
        "LE PACTE",
        "LEDICK FILMHANDEL",
        "LEGEND",
        "LEOMARK STUDIOS",
        "LEOMARK",
        "LEONINE FILMS",
        "LEONINE",
        "LICHTUNG LTD.",
        "LICHTUNG LTD",
        "LICHTUNG MEDIA LTD.",
        "LICHTUNG MEDIA LTD",
        "LICHTUNG MEDIA",
        "LICHTUNG",
        "LIGHTHOUSE ENTERTAINMENT",
        "LIGHTHOUSE HOME ENTERTAINMENT",
        "LIGHTHOUSE HOME",
        "LIGHTHOUSE",
        "LIGHTYEAR",
        "LIONSGATE FILMS",
        "LIONSGATE",
        "LIZARD CINEMA TRADE",
        "LLAMENTOL",
        "LOBSTER FILMS",
        "LOBSTER",
        "LOGON",
        "LORBER FILMS",
        "LORBER",
        "LOS BANDITOS FILMS",
        "LOS BANDITOS",
        "LOUD & PROUD RECORDS",
        "LOUD & PROUD",
        "LOUD AND PROUD RECORDS",
        "LOUD AND PROUD",
        "LSO LIVE",
        "LUCASFILM",
        "LUCKY RED",
        "LUMIERE ENTERTAINMENT",
        "LUMIERE HOME ENTERTAINMENT",
        "LUMIÈRE HOME ENTERTAINMENT",
        "LUMIERE HOME",
        "LUMIERE",
        "M6 VIDEO",
        "M6",
        "MAD DIMENSION",
        "MADMAN ENTERTAINMENT",
        "MADMAN",
        "MAGIC BOX",
        "MAGIC PLAY",
        "MAGNA ENTERTAINMENT",
        "MAGNA HOME ENTERTAINMENT",
        "MAGNA HOME",
        "MAGNA",
        "MAGNOLIA PICTURES",
        "MAGNOLIA",
        "MAIDEN JAPAN",
        "MAIDEN",
        "MAJENG MEDIA",
        "MAJENG",
        "MAJESTIC ENTERTAINMENT",
        "MAJESTIC HOME ENTERTAINMENT",
        "MAJESTIC HOME",
        "MAJESTIC",
        "MANGA ENTERTAINMENT",
        "MANGA HOME ENTERTAINMENT",
        "MANGA HOME",
        "MANGA",
        "MANTA LAB",
        "MAPLE STUDIOS",
        "MAPLE",
        "MARCO POLO PRODUCTION",
        "MARCO POLO",
        "MARIINSKY",
        "MARVEL STUDIOS",
        "MARVEL",
        "MASCOT RECORDS",
        "MASCOT",
        "MASSACRE VIDEO",
        "MASSACRE",
        "MASTERS OF CINEMA",
        "MATCHBOX",
        "MATRIX D",
        "MAXAM",
        "MAYA ENTERTAINMENT",
        "MAYA HOME ENTERTAINMENT",
        "MAYA HOME",
        "MAYAT",
        "MDG",
        "MEDIA BLASTERS",
        "MEDIA FACTORY",
        "MEDIA TARGET DISTRIBUTION",
        "MEDIA TARGET",
        "MEDIAINVISION",
        "MEDIATOON",
        "MEDIATRES ESTUDIO",
        "MEDIATRES STUDIO",
        "MEDIATRES",
        "MEDICI ARTS",
        "MEDICI CLASSICS",
        "MEDIUMRARE ENTERTAINMENT",
        "MEDIUMRARE",
        "MEDUSA",
        "MEGASTAR",
        "MEI AH",
        "MELI MEDIAS",
        "MELI MÉDIAS",
        "MEMENTO FILMS",
        "MEMENTO",
        "MENEMSHA FILMS",
        "MENEMSHA",
        "MERCURY STUDIOS",
        "MERCURY",
        "MERGE PRODUCTIONS",
        "MERGE SOFT PRODUCTIONS",
        "MERGE SOFT",
        "MERGE",
        "MERIDIAN",
        "METAL BLADE RECORDS",
        "METAL BLADE",
        "METEOR",
        "METRO GOLDWYN MAYER",
        "METRO-GOLDWYN-MAYER",
        "METRODOME VIDEO",
        "METRODOME",
        "METROGOLDWYNMAYER",
        "METROPOLITAN",
        "MFA",
        "MFA+",
        "MGM",
        "MGM/FOX",
        "MIG FILMGROUP",
        "MIG",
        "MILESTONE",
        "MILL CREEK ENTERTAINMENT",
        "MILL CREEK",
        "MILLENNIUM MEDIA",
        "MILLENNIUM",
        "MIRAGE ENTERTAINMENT",
        "MIRAGE",
        "MIRAMAX",
        "MISTERIYA ZVUKA",
        "MK2",
        "MOC",
        "MODE RECORDS",
        "MODE",
        "MOMENTUM PICTURES",
        "MONDO ENTERTAINMENT",
        "MONDO HOME ENTERTAINMENT",
        "MONDO HOME",
        "MONDO MACABRO",
        "MONGREL MEDIA",
        "MONOLIT",
        "MONOLITH VIDEO",
        "MONOLITH",
        "MONSTER PICTURES",
        "MONSTER",
        "MONTEREY VIDEO",
        "MONTEREY",
        "MONUMENT RELEASING",
        "MONUMENT",
        "MORNING STAR",
        "MORNINGSTAR",
        "MOSERBAER",
        "MOVIEMAX",
        "MOVINSIDE",
        "MPI MEDIA GROUP",
        "MPI MEDIA",
        "MPI",
        "MR BONGO FILMS",
        "MR BONGO",
        "MR. BONGO FILMS",
        "MRG (MERIDIAN)",
        "MRG MERIDIAN",
        "MRG",
        "MUBI",
        "MUG SHOT PRODUCTIONS",
        "MUG SHOT",
        "MULTI MUSIC",
        "MULTI-MUSIC",
        "MULTIMUSIC",
        "MUSE",
        "MUSIC BOX FILMS",
        "MUSIC BOX",
        "MUSIC BROKERS",
        "MUSIC THEORIES",
        "MUSIC VIDEO DISTRIBUTORS",
        "MUSIC VIDEO",
        "MUSICBOX",
        "MUSTANG ENTERTAINMENT",
        "MUSTANG",
        "MVD VISUAL",
        "MVD",
        "MVD/VSC",
        "MVL",
        "MVM ENTERTAINMENT",
        "MVM",
        "MYNDFORM",
        "MYSTIC NIGHT PICTURES",
        "MYSTIC NIGHT",
        "NAMELESS MEDIA",
        "NAMELESS",
        "NAPALM RECORDS",
        "NAPALM",
        "NAT GEO TV",
        "NAT GEO",
        "NATIONAL ARCHIVE",
        "NATIONAL ENTERTAINMENT MEDIA",
        "NATIONAL ENTERTAINMENT",
        "NATIONAL FILM ARCHIVE",
        "NATIONAL FILM",
        "NATIONAL GEOGRAPHIC",
        "NATIONAL MEDIA",
        "NAXOS",
        "NBC JAPAN",
        "NBC UNIVERSAL ENTERTAINMENT JAPAN",
        "NBC UNIVERSAL JAPAN",
        "NBCUNIVERSAL ENTERTAINMENT JAPAN",
        "NBCUNIVERSAL JAPAN",
        "NBO ENTERTAINMENT",
        "NBO",
        "NEOS",
        "NETFLIX",
        "NETWORK",
        "NEW BLOOD",
        "NEW DISC",
        "NEW KSM",
        "NEW LINE CINEMA",
        "NEW LINE",
        "NEW MOVIE TRADING CO LTD",
        "NEW MOVIE TRADING CO. LTD",
        "NEW MOVIE TRADING CO",
        "NEW MOVIE TRADING",
        "NEW WAVE FILMS",
        "NEW WAVE",
        "NFI",
        "NGO",
        "NHK",
        "NIPPONART",
        "NIS AMERICA",
        "NJUTAFILMS",
        "NOBLE ENTERTAINMENT",
        "NOBLE",
        "NORDISK FILM",
        "NORDISK",
        "NORSK FILM",
        "NORSK",
        "NORTH AMERICAN MOTION PICTURES",
        "NOS AUDIOVISUAIS",
        "NOTORIOUS PICTURES",
        "NOTORIOUS",
        "NOVA MEDIA",
        "NOVA SALES & DISTRIBUTION",
        "NOVA SALES AND DISTRIBUTION",
        "NOVA",
        "NSM RECORDS",
        "NSM",
        "NUCLEAR BLAST",
        "NUCLEUS FILMS",
        "NUCLEUS",
        "OBERLIN MUSIC",
        "OBERLIN",
        "OBRAS PRIMAS CINEMA",
        "OBRAS PRIMAS DO CINEMA",
        "OBRAS PRIMAS",
        "OBRAS-PRIMAS CINEMA",
        "OBRAS-PRIMAS DO CINEMA",
        "OBRAS-PRIMAS",
        "OBRASPRIMAS CINEMA",
        "OBRASPRIMAS DO CINEMA",
        "OBRASPRIMAS",
        "ODEON",
        "OFDB FILMWORKS",
        "OFDB",
        "OLIVE FILMS",
        "OLIVE",
        "ON",
        "ONDINE",
        "ONSCREEN FILMS",
        "ONSCREEN",
        "OPENING DISTRIBUTION",
        "OPERA AUSTRALIA",
        "OPTIMUM ENTERTAINMENT",
        "OPTIMUM HOME ENTERTAINMENT",
        "OPTIMUM HOME",
        "OPTIMUM",
        "OPUS ARTE",
        "ORANGE STUDIO",
        "ORANGE",
        "ORLANDO EASTWOOD FILMS",
        "ORLANDO EASTWOOD",
        "ORLANDO FILMS",
        "ORLANDO",
        "ORUSTAK PICTURES",
        "ORUSTAK",
        "OSCILLOSCOPE PICTURES",
        "OSCILLOSCOPE",
        "OUTPLAY",
        "PALISADES TARTAN",
        "PAN VISION",
        "PANAMINT CINEMA",
        "PANAMINT",
        "PANDA STORM ENTERTAINMENT",
        "PANDA STORM",
        "PANDASTORM ENTERTAINMENT",
        "PANDASTORM",
        "PANDORA FILM",
        "PANDORA",
        "PANEGYRIC",
        "PANORAMA",
        "PANVISION",
        "PARADE DECK FILMS",
        "PARADE DECK",
        "PARADISE",
        "PARADISO FILMS",
        "PARADOX",
        "PARAMOUNT PICTURES",
        "PARAMOUNT",
        "PARIS FILMES",
        "PARIS FILMS",
        "PARIS",
        "PARK CIRCUS",
        "PARLOPHONE",
        "PASSION RIVER",
        "PATHE DISTRIBUTION",
        "PATHE",
        "PBS",
        "PEACE ARCH TRINITY",
        "PECCADILLO PICTURES",
        "PEPPERMINT",
        "PHASE 4 FILMS",
        "PHASE 4",
        "PHILHARMONIA BAROQUE",
        "PICTURE ENTERTAINMENT",
        "PICTURE HOUSE ENTERTAINMENT",
        "PICTURE HOUSE",
        "PICTURE",
        "PIDAX",
        "PINK FLOYD RECORDS",
        "PINK FLOYD",
        "PINNACLE FILMS",
        "PINNACLE",
        "PLAIN",
        "PLATFORM ENTERTAINMENT LIMITED",
        "PLATFORM ENTERTAINMENT LTD.",
        "PLATFORM ENTERTAINMENT LTD",
        "PLATFORM ENTERTAINMENT",
        "PLATFORM",
        "PLAYARTE",
        "PLG UK CLASSICS",
        "PLG UK",
        "PLG",
        "POLYBAND & TOPPIC VIDEO & WVG",
        "POLYBAND & TOPPIC VIDEO AND WVG",
        "POLYBAND & TOPPIC VIDEO WVG",
        "POLYBAND & TOPPIC VIDEO",
        "POLYBAND & TOPPIC VIDEO/WVG",
        "POLYBAND & TOPPIC",
        "POLYBAND AND TOPPIC VIDEO & WVG",
        "POLYBAND AND TOPPIC VIDEO AND WVG",
        "POLYBAND AND TOPPIC VIDEO WVG",
        "POLYBAND AND TOPPIC VIDEO",
        "POLYBAND AND TOPPIC VIDEO/WVG",
        "POLYBAND AND TOPPIC",
        "POLYBAND",
        "POLYDOR",
        "PONY CANYON",
        "PONY",
        "POTEMKINE",
        "POWERHOUSE FILMS",
        "POWERHOUSE",
        "POWERSTATIOM",
        "PRIDE & JOY",
        "PRIDE AND JOY",
        "PRINZ MEDIA",
        "PRINZ",
        "PRIS AUDIOVISUAIS",
        "PRO MOTION",
        "PRO VIDEO",
        "PRO-MOTION",
        "PRO-VIDEO",
        "PROD JRB",
        "PROD. JRB",
        "PRODISC",
        "PROKINO",
        "PROVOGUE RECORDS",
        "PROVOGUE",
        "PROWARE",
        "PULP VIDEO",
        "PULP",
        "PULSE VIDEO",
        "PULSE",
        "PURE AUDIO RECORDINGS",
        "PURE AUDIO",
        "PURE ENTERTAINMENT",
        "PURE FLIX ENTERTAINMENT",
        "PURE FLIX",
        "PYRAMIDE VIDEO",
        "PYRAMIDE",
        "QUALITY FILMS",
        "QUALITY",
        "QUARTO VALLEY RECORDS",
        "QUARTO VALLEY",
        "QUESTAR",
        "R SQUARED FILMS",
        "R SQUARED",
        "RAPID EYE MOVIES",
        "RAPID EYE",
        "RARO U.S.",
        "RARO US",
        "RARO VIDEO U.S.",
        "RARO VIDEO US",
        "RARO VIDEO",
        "RARO",
        "RAROVIDEO U.S.",
        "RAROVIDEO US",
        "RAVEN BANNER RELEASING",
        "RAVEN BANNER",
        "RAVEN",
        "RAZOR DIGITAL ENTERTAINMENT",
        "RAZOR DIGITAL",
        "RCA",
        "RCO LIVE",
        "RCO",
        "RCV",
        "REAL GONE MUSIC",
        "REAL GONE",
        "REANI MEDIA",
        "REANIMEDIA",
        "REDEMPTION",
        "REEL",
        "RELIANCE HOME VIDEO & GAMES",
        "RELIANCE HOME VIDEO AND GAMES",
        "RELIANCE HOME VIDEO",
        "RELIANCE HOME",
        "RELIANCE VIDEO",
        "RELIANCE",
        "REM CULTURE",
        "REMAIN IN LIGHT",
        "REPRISE",
        "RESEN",
        "RETROMEDIA",
        "REVELATION FILMS LTD.",
        "REVELATION FILMS LTD",
        "REVELATION FILMS",
        "REVELATION LTD.",
        "REVELATION LTD",
        "REVELATION",
        "REVOLVER ENTERTAINMENT",
        "REVOLVER",
        "RHINO MUSIC",
        "RHINO",
        "RHV",
        "RIGHT STUF",
        "RIMINI EDITIONS",
        "RISING SUN MEDIA",
        "RLJ ENTERTAINMENT",
        "RLJ",
        "ROADRUNNER RECORDS",
        "ROADSHOW ENTERTAINMENT",
        "ROADSHOW",
        "RONE",
        "RONIN FLIX",
        "ROTANA ENTERTAINMENT",
        "ROTANA HOME ENTERTAINMENT",
        "ROTANA HOME",
        "ROTANA",
        "ROUGH TRADE",
        "ROUNDER",
        "SAFFRON HILL FILMS",
        "SAFFRON HILL",
        "SAFFRON",
        "SAMUEL GOLDWYN FILMS",
        "SAMUEL GOLDWYN",
        "SAN FRANCISCO SYMPHONY",
        "SANDREW METRONOME",
        "SAPHRANE",
        "SAVOR",
        "SCANBOX ENTERTAINMENT",
        "SCANBOX",
        "SCENIC LABS",
        "SCHRODER MEDIA",
        "SCHRODERMEDIA",
        "SCHRÖDERMEDIA",
        "SCORPION RELEASING",
        "SCORPION",
        "SCREAM TEAM RELEASING",
        "SCREAM TEAM",
        "SCREEN MEDIA",
        "SCREEN",
        "SCREENBOUND PICTURES",
        "SCREENBOUND",
        "SCREENWAVE MEDIA",
        "SCREENWAVE",
        "SECOND RUN",
        "SECOND SIGHT",
        "SEEDSMAN GROUP",
        "SELECT VIDEO",
        "SELECTA VISION",
        "SENATOR",
        "SENTAI FILMWORKS",
        "SENTAI",
        "SEVEN7",
        "SEVERIN FILMS",
        "SEVERIN",
        "SEVILLE",
        "SEYONS ENTERTAINMENT",
        "SEYONS",
        "SF STUDIOS",
        "SFI",
        "SGL ENTERTAINMENT",
        "SGL",
        "SHAMELESS",
        "SHAMROCK MEDIA",
        "SHAMROCK",
        "SHANGHAI ENTERTAINMENT",
        "SHANGHAI EPIC ENTERTAINMENT",
        "SHANGHAI EPIC MUSIC ENTERTAINMENT",
        "SHANGHAI EPIC MUSIC",
        "SHANGHAI MUSIC ENTERTAINMENT",
        "SHANGHAI MUSIC",
        "SHANGHAI",
        "SHEMAROO",
        "SHOCHIKU",
        "SHOCK",
        "SHOGAKU KAN",
        "SHOUT FACTORY",
        "SHOUT! FACTORY",
        "SHOUT!",
        "SHOUT",
        "SHOWBOX",
        "SHOWTIME ENTERTAINMENT",
        "SHOWTIME",
        "SHRIEK SHOW",
        "SHUDDER",
        "SIDONIS CALYSTA",
        "SIDONIS",
        "SIGNAL ONE ENTERTAINMENT",
        "SIGNAL ONE",
        "SIGNATURE ENTERTAINMENT",
        "SIGNATURE",
        "SILVER VISION",
        "SINISTER FILM",
        "SINISTER",
        "SIREN ENTERTAINMENT",
        "SIREN VISUAL ENTERTAINMENT",
        "SIREN VISUAL",
        "SIREN",
        "SKANI",
        "SKY DIGI",
        "SLASHER / VIDEO",
        "SLASHER // VIDEO",
        "SLASHER VIDEO",
        "SLASHER",
        "SLOVAK FILM INSTITUTE",
        "SLOVAK FILM",
        "SM LIFE DESIGN GROUP",
        "SMOOTH PICTURES",
        "SMOOTH",
        "SNAPPER MUSIC",
        "SNAPPER",
        "SODA PICTURES",
        "SODA",
        "SONO LUMINUS",
        "SONY CLASSICS",
        "SONY MUSIC",
        "SONY PICTURES CLASSICS",
        "SONY PICTURES",
        "SONY",
        "SOUL MEDIA",
        "SOUL",
        "SOULFOOD DISTRIBUTION",
        "SOULFOOD MUSIC DISTRIBUTION",
        "SOULFOOD MUSIC",
        "SOULFOOD",
        "SOYUZ",
        "SPECTRUM",
        "SPENTZOS FILM",
        "SPENTZOS",
        "SPIRIT ENTERTAINMENT",
        "SPIRIT MEDIA GMBH",
        "SPIRIT MEDIA",
        "SPIRIT",
        "SPLENDID ENTERTAINMENT",
        "SPLENDID FILM",
        "SPO",
        "SQUARE ENIX",
        "SRI BALAJI VIDEO",
        "SRI BALAJI",
        "SRI VIDEO",
        "SRI",
        "SRS CINEMA",
        "SRS",
        "SSO RECORDINGS",
        "SSO",
        "ST2 MUSIC",
        "ST2",
        "STAR ENTERTAINMENT",
        "STAR MEDIA ENTERTAINMENT",
        "STAR MEDIA",
        "STAR",
        "STARLIGHT",
        "STARZ / ANCHOR BAY",
        "STARZ ANCHOR BAY",
        "STARZ",
        "STER KINEKOR",
        "STERLING ENTERTAINMENT",
        "STERLING",
        "STINGRAY",
        "STOCKFISCH RECORDS",
        "STOCKFISCH",
        "STRAND RELEASING",
        "STRAND",
        "STUDIO 4K",
        "STUDIO CANAL",
        "STUDIO GHIBLI",
        "STUDIO HAMBURG ENTERPRISES",
        "STUDIO HAMBURG",
        "STUDIO S",
        "SUBKULTUR ENTERTAINMENT",
        "SUBKULTUR",
        "SUEVIA FILMS",
        "SUEVIA",
        "SUMMIT ENTERTAINMENT",
        "SUMMIT",
        "SUNFILM ENTERTAINMENT",
        "SUNFILM",
        "SURROUND RECORDS",
        "SURROUND",
        "SVENSK FILMINDUSTRI",
        "SVENSK",
        "SWEN FILMES",
        "SWEN FILMS",
        "SWEN",
        "SYNAPSE FILMS",
        "SYNAPSE",
        "SYNDICADO",
        "SYNERGETIC",
        "T SERIES",
        "T- SERIES",
        "T-SERIES",
        "T.V.P.",
        "TACET RECORDS",
        "TACET",
        "TAI SENG",
        "TAI SHENG",
        "TAKEONE",
        "TAKESHOBO",
        "TAMASA DIFFUSION",
        "TC ENTERTAINMENT",
        "TC",
        "TDK",
        "TEAM MARKETING",
        "TEATRO REAL",
        "TEMA DISTRIBUCIONES",
        "TEMPE DIGITAL",
        "TF1 VIDEO",
        "TF1 VIDÉO",
        "TF1",
        "THE BLU",
        "THE ECSTASY OF FILMS",
        "THE FILM DETECTIVE",
        "THE JOKERS",
        "THE ON",
        "THIM FILM",
        "THIM",
        "THIMFILM",
        "THIRD WINDOW FILMS",
        "THIRD WINDOW",
        "THUNDERBEAN ANIMATION",
        "THUNDERBEAN",
        "THUNDERBIRD RELEASING",
        "THUNDERBIRD",
        "TIBERIUS FILM",
        "TIME LIFE",
        "TIMELESS GROUP",
        "TIMELESS MEDIA GROUP",
        "TIMELESS MEDIA",
        "TIMELESS",
        "TLA RELEASING",
        "TLA",
        "TOBIS FILM",
        "TOBIS",
        "TOEI",
        "TOHO",
        "TOKYO SHOCK",
        "TOKYO",
        "TONPOOL MEDIEN GMBH",
        "TONPOOL MEDIEN",
        "TOPICS ENTERTAINMENT",
        "TOPICS",
        "TOUCHSTONE PICTURES",
        "TOUCHSTONE",
        "TRANSMISSION FILMS",
        "TRANSMISSION",
        "TRAVEL VIDEO STORE",
        "TRI PICTURES",
        "TRI-PICTURES",
        "TRI-STAR",
        "TRIART",
        "TRIGON FILM",
        "TRIGON",
        "TRINITY ENTERTAINMENT",
        "TRINITY HOME ENTERTAINMENT",
        "TRINITY HOME",
        "TRINITY",
        "TRIPICTURES",
        "TROMA",
        "TSERIES",
        "TT",
        "TURBINE MEDIEN",
        "TURTLE RECORDS",
        "TURTLE",
        "TVA FILMS",
        "TVA",
        "TVP",
        "TWILIGHT TIME",
        "TWILIGHT",
        "TWIN CO LTD",
        "TWIN CO, LTD.",
        "TWIN CO, LTD",
        "TWIN CO., LTD.",
        "TWIN CO., LTD",
        "TWIN CO.",
        "TWIN CO",
        "TWIN LTD",
        "TWIN",
        "UCA",
        "UDR",
        "UEK",
        "UFA DVD",
        "UFA/DVD",
        "UFADVD",
        "UGC PH",
        "ULTIMATE3DHEAVEN",
        "ULTRA",
        "UMBRELLA ENTERTAINMENT",
        "UMBRELLA",
        "UMC",
        "UNCORK D ENTERTAINMENT",
        "UNCORK D",
        "UNCORK'D ENTERTAINMENT",
        "UNCORK'D",
        "UNCORKD ENTERTAINMENT",
        "UNCORKD",
        "UNEARTHED FILMS",
        "UNEARTHED",
        "UNI DISC",
        "UNIMUNDOS",
        "UNITEL",
        "UNIVERSAL ENTERTAINMENT",
        "UNIVERSAL HOME ENTERTAINMENT",
        "UNIVERSAL HOME",
        "UNIVERSAL MUSIC",
        "UNIVERSAL SONY PICTURES ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES HOME ENTERTAINMENT",
        "UNIVERSAL SONY PICTURES HOME",
        "UNIVERSAL SONY PICTURES",
        "UNIVERSAL STUDIOS",
        "UNIVERSAL",
        "UNIVERSE LASER & VIDEO CO.",
        "UNIVERSE LASER & VIDEO CO",
        "UNIVERSE LASER AND VIDEO CO.",
        "UNIVERSE LASER AND VIDEO CO",
        "UNIVERSE LASER CO.",
        "UNIVERSE LASER CO",
        "UNIVERSE LASER",
        "UNIVERSUM FILM",
        "UNIVERSUM",
        "UTV",
        "VAP",
        "VCI",
        "VENDETTA FILMS",
        "VENDETTA",
        "VERSATIL HOME VIDEO",
        "VERSÁTIL HOME VIDEO",
        "VERSATIL HOME",
        "VERSÁTIL HOME",
        "VERSATIL VIDEO",
        "VERSÁTIL VIDEO",
        "VERSATIL",
        "VERSÁTIL",
        "VERTICAL ENTERTAINMENT",
        "VERTICAL",
        "VERTICE 360",
        "VÉRTICE 360",
        "VERTICE 360o",
        "VÉRTICE 360º",
        "VERTIGO BERLIN",
        "VERTIGO FILMS",
        "VÉRTIGO FILMS",
        "VERTIGO",
        "VÉRTIGO",
        "VERVE PICTURES",
        "VIA VISION ENTERTAINMENT",
        "VIA VISION",
        "VICOL ENTERTAINMENT",
        "VICOL",
        "VICOM",
        "VICTOR ENTERTAINMENT",
        "VICTOR",
        "VIDEA CDE",
        "VIDEO EXPRESS",
        "VIDEO FILM EXPRESS",
        "VIDEO FILM",
        "VIDEO MAX",
        "VIDEO MUSIC INC.",
        "VIDEO MUSIC INC",
        "VIDEO MUSIC, INC.",
        "VIDEO MUSIC, INC",
        "VIDEO MUSIC",
        "VIDEO SERVICE CORP.",
        "VIDEO SERVICE CORP",
        "VIDEO SERVICE",
        "VIDEO TRAVEL",
        "VIDEOMAX",
        "VII PILLARS ENTERTAINMENT",
        "VII PILLARS",
        "VILLAGE FILMS",
        "VINEGAR SYNDROME",
        "VINEGAR",
        "VINNY MOVIES",
        "VINNY",
        "VIRGIL ENTERTAINMENT",
        "VIRGIL FILMS & ENTERTAINMENT",
        "VIRGIL FILMS AND ENTERTAINMENT",
        "VIRGIL FILMS",
        "VIRGIL",
        "VIRGIN RECORDS",
        "VIRGIN",
        "VISION FILMS",
        "VISION",
        "VISUAL ENTERTAINMENT GROUP",
        "VISUAL ENTERTAINMENT",
        "VISUAL GROUP",
        "VISUAL",
        "VIVENDI VISUAL ENTERTAINMENT",
        "VIVENDI VISUAL",
        "VIVENDI",
        "VIZ PICTURES",
        "VIZ",
        "VL MEDIA",
        "VL",
        "VLMEDIA",
        "VOLGA",
        "VS",
        "VVS FILMS",
        "VVS",
        "VZ HANDELS GMBH",
        "VZ HANDELS",
        "WAC",
        "WARD RECORDS",
        "WARD",
        "WARNER ARCHIVE COLLECTION",
        "WARNER ARCHIVE",
        "WARNER BROS.",
        "WARNER BROS",
        "WARNER MUSIC",
        "WARNER",
        "WEA",
        "WEINSTEIN COMPANY",
        "WEINSTEIN",
        "WELL GO USA",
        "WELL GO",
        "WELTKINO FILMVERLEIH",
        "WEST VIDEO",
        "WEST",
        "WHITE PEARL MOVIES",
        "WHITE PEARL",
        "WICKED VISION MEDIA",
        "WICKED VISION",
        "WICKED-VISION MEDIA",
        "WICKED-VISION",
        "WICKEDVISION MEDIA",
        "WICKEDVISION",
        "WIENERWORLD",
        "WILD BUNCH",
        "WILD EYE RELEASING",
        "WILD EYE",
        "WILD SIDE VIDEO",
        "WILD SIDE",
        "WME",
        "WOLFE VIDEO",
        "WOLFE",
        "WORD ON FIRE",
        "WORKS FILM GROUP",
        "WORLD WRESTLING",
        "WVG MEDIEN",
        "WVG",
        "WWE STUDIOS",
        "WWE",
        "X RATED CULT",
        "X RATED KULT",
        "X RATED",
        "X-RATED CULT",
        "X-RATED KULT",
        "X-RATED",
        "XCESS",
        "XLRATOR",
        "XT VIDEO",
        "XT",
        "YAMATO VIDEO",
        "YAMATO",
        "YASH RAJ FILMS",
        "YASH RAJS",
        "ZEITGEIST FILMS",
        "ZEITGEIST",
        "ZENITH PICTURES",
        "ZENITH",
        "ZIMA",
        "ZYLO",
        "ZYX MUSIC",
        "ZYX",
        "車庫娛樂",
    ]
    distributor_out = ""
    if distributor_in is not None and distributor_in not in ["None", ""]:
        for each in distributor_list:
            if distributor_in.upper() == each:
                distributor_out = each
    return distributor_out


async def get_service(
    video: str | None = None, tag: str | None = None, audio: str | None = None, guess_title: str | None = None, get_services_only: bool = False
) -> dict[str, str] | tuple[str, str]:
    services = {
        "3Sat": "3SAT",
        "3SAT": "3SAT",
        "9Now": "9NOW",
        "9NOW": "9NOW",
        "À LA CARTE": "BELA",
        "A&E": "AE",
        "ABC Australia": "AUBC",
        "ABC": "AMBC",
        "ADN": "ADN",
        "Adult Swim": "AS",
        "AE": "AE",
        "AJAZ": "AJAZ",
        "Al Jazeera English": "AJAZ",
        "ALL4": "ALL4",
        "Amazon Prime": "AMZN",
        "AMBC": "AMBC",
        "AMC": "AMC",
        "America's Test Kitchen": "ATK",
        "AMZN": "AMZN",
        "Animal Planet": "ANPL",
        "Animation Digital Network": "ADN",
        "AnimeLab": "ANLB",
        "ANLB": "ANLB",
        "ANPL": "ANPL",
        "AOL": "AOL",
        "Apple TV": "ATV",
        "Apple TV+": "ATVP",
        "ARD Mediathek": "ARD",
        "ARD": "ARD",
        "ARD Plus": "ARDP",
        "ARDP": "ARDP",
        "ARTE": "ARTE",
        "AS": "AS",
        "ATK": "ATK",
        "ATV": "ATV",
        "ATVP": "ATVP",
        "AUBC": "AUBC",
        "BBC iPlayer": "iP",
        "BCORE": "BCORE",
        "BELA": "BELA",
        "Belas Artes À La Carte": "BELA",
        "BILI": "BILI",
        "Bilibili": "BILI",
        "Binge": "BNGE",
        "BKPL": "BKPL",
        "Blackpills": "BKPL",
        "BluTV": "BLU",
        "BOOM": "BOOM",
        "Boomerang": "BOOM",
        "BP": "BP",
        "Brasil Paralelo": "BP",
        "BRAV": "BRAV",
        "BravoTV": "BRAV",
        "Canal+": "CNLP",
        "Cartoon Network": "CN",
        "CBC": "CBC",
        "CBS": "CBS",
        "CC": "CC",
        "CCGC": "CCGC",
        "Channel 4": "ALL4",
        "CHGD": "CHGD",
        "Chorki": "CRKI",
        "CHRGD": "CHGD",
        "Cinego": "CNGO",
        "Cinemax": "CMAX",
        "CMAX": "CMAX",
        "CMOR": "CMOR",
        "CMT": "CMT",
        "CN": "CN",
        "CNBC": "CNBC",
        "CNGO": "CNGO",
        "CNLP": "CNLP",
        "Comedians in Cars Getting Coffee": "CCGC",
        "Comedy Central": "CC",
        "COOK": "COOK",
        "CORE": "CORE",
        "Country Music Television": "CMT",
        "CR": "CR",
        "Crackle": "CRKL",
        "CRAV": "CRAV",
        "Crave": "CRAV",
        "CRIT": "CRIT",
        "Criterion": "CRIT",
        "CRKI": "CRKI",
        "CRKL": "CRKL",
        "Crunchy Roll": "CR",
        "CSpan": "CSPN",
        "CSPN": "CSPN",
        "CTHP": "CTHP",
        "CTV": "CTV",
        "CUR": "CUR",
        "CuriosityStream": "CUR",
        "CW": "CW",
        "CWS": "CWS",
        "CWSeed": "CWS",
        "Daisuki": "DSKI",
        "DARKROOM": "DARKROOM",
        "DAZN": "DAZN",
        "DC Universe": "DCU",
        "DCU": "DCU",
        "DDY": "DDY",
        "Deadhouse Films": "DHF",
        "DEST": "DEST",
        "DHF": "DHF",
        "Digiturk Diledigin Yerde": "DDY",
        "DISC": "DISC",
        "Discovery Plus": "DSCP",
        "Discovery": "DISC",
        "Disney": "DSNY",
        "Disney+": "DSNP",
        "DIY Network": "DIY",
        "DIY": "DIY",
        "Doc Club": "DOCC",
        "DOCC": "DOCC",
        "DOCPLAY": "DOCPLAY",
        "DPlay": "DPLY",
        "DPLY": "DPLY",
        "DramaFever": "DF",
        "DRPO": "DRPO",
        "DSKI": "DSKI",
        "DSNP": "DSNP",
        "DSNY": "DSNY",
        "DTV": "DTV",
        "E!": "ETV",
        "El Trece": "ETTV",
        "ePix": "EPIX",
        "EPIX": "EPIX",
        "ESPN": "ESPN",
        "ESQ": "ESQ",
        "Esquire": "ESQ",
        "ETTV": "ETTV",
        "ETV": "ETV",
        "Facebook Watch": "FBWatch",
        "FAM": "FAM",
        "Family Jr": "FJR",
        "Fandor": "FANDOR",
        "Filmicca": "FLMC",
        "Filmio": "FMIO",
        "FJR": "FJR",
        "FLMC": "FLMC",
        "FMIO": "FMIO",
        "Food Network": "FOOD",
        "FOOD": "FOOD",
        "Fox Premium": "FOXP",
        "Fox": "FOX",
        "FOX": "FOX",
        "Foxtel": "FXTL",
        "FPT": "FPT",
        "FREE": "FREE",
        "Freeform": "FREE",
        "FTV": "FTV",
        "FUNi": "FUNI",
        "FUNI": "FUNI",
        "FYI Network": "FYI",
        "FYI": "FYI",
        "GagaOOLala": "Gaga",
        "GC": "GC",
        "GLBL": "GLBL",
        "GLBO": "GLBO",
        "GLOB": "GLOB",
        "Global": "GLBL",
        "Globoplay": "GLBO",
        "GloboSat Play": "GLOB",
        "GO90": "GO90",
        "Hallmark": "HLMK",
        "HBO Go": "HBO",
        "HBO Max": "HMAX",
        "HBO": "HBO",
        "HBOMAX": "HMAX",
        "HGTV": "HGTV",
        "HIDI": "HIDI",
        "HiDive": "HIDI",
        "HIST": "HIST",
        "History": "HIST",
        "HLMK": "HLMK",
        "HMAX": "HMAX",
        "hoichoi": "HoiChoi",
        "HS": "HTSR",
        "HSTR": "Hotstar",
        "HTSR": "HTSR",
        "Hulu": "HULU",
        "HULU": "HULU",
        "ICP": "ICP",
        "ID": "ID",
        "IFC": "IFC",
        "iflix": "IFX",
        "Investigation Discovery": "ID",
        "iP": "iP",
        "iQIYI": "iQIYI",
        "iT": "iT",
        "Itaú Cultural Play": "ICP",
        "iTunes": "iT",
        "ITV": "ITV",
        "JOYN": "JOYN",
        "Kanopy": "KNPY",
        "KAYO": "KAYO",
        "KCW": "KCW",
        "KiKA": "KiKA",
        "KNOW": "KNOW",
        "Knowledge Network": "KNOW",
        "KNPY": "KNPY",
        "Kocowa": "KCW",
        "Kocowa+": "KCW",
        "KS": "KS",
        "Kyivstar TV": "KS",
        "kyivstar": "KS",
        "Kyivstar": "KS",
        "KyivstarTV": "KS",
        "LIFE": "LIFE",
        "Lifetime": "LIFE",
        "LN": "LN",
        "Looke": "LOOKE",
        "LOOKE": "LOOKE",
        "MA": "MA",
        "MAX": "MAX",
        "MBC": "MBC",
        "Megogo": "MGG",
        "MeGoGo": "MGG",
        "MEGOGO": "MGG",
        "MGG": "MGG",
        "MNBC": "MNBC",
        "Motor Trend OnDemand": "MTOD",
        "Movies Anywhere": "MA",
        "MSNBC": "MNBC",
        "MTOD": "MTOD",
        "MTV": "MTV",
        "MUBI": "MUBI",
        "NATG": "NATG",
        "National Audiovisual Institute": "INA",
        "National Film Board": "NFB",
        "National Geographic": "NATG",
        "NBA TV": "NBA",
        "NBA": "NBA",
        "NBC": "NBC",
        "NBLA": "NBLA",
        "Nebula": "NBLA",
        "Netflix": "NF",
        "NF": "NF",
        "NFL Now": "NFLN",
        "NFL": "NFL",
        "NFLN": "NFLN",
        "NHL GameCenter": "GC",
        "NICK": "NICK",
        "Nickelodeon": "NICK",
        "Norsk Rikskringkasting": "NRK",
        "NOW": "NOW",
        "NOWTV": "NOW",
        "NRK": "NRK",
        "OBB Railnet": "RNET",
        "OnDemandKorea": "ODK",
        "Oprah Winfrey Network": "OWN",
        "Opto": "OPTO",
        "ORF ON": "ORF",
        "ORF": "ORF",
        "PA": "PA",
        "PBS Kids": "PBSK",
        "PBS": "PBS",
        "PBSK": "PBSK",
        "PCOK": "PCOK",
        "Peacock": "PCOK",
        "PKO": "PKO",
        "Planeta Kino Online": "PKO",
        "PLAY": "PLAY",
        "Playstation Network": "PSN",
        "PLTV": "PLTV",
        "Pluto TV": "PLTV",
        "PLUZ": "PLUZ",
        "Pluzz": "PLUZ",
        "PMNP": "PMNP",
        "PMNT": "PMNT",
        "PMTP": "PMTP",
        "POGO": "POGO",
        "PokerGO": "POGO",
        "Prime Video": "AMZN",
        "PSN": "PSN",
        "PUHU": "PUHU",
        "QIBI": "QIBI",
        "Rakuten TV": "RKTN",
        "RED": "RED",
        "RKTN": "RKTN",
        "RNET": "RNET",
        "RSTR": "RSTR",
        "RTE One": "RTE",
        "RTE": "RTE",
        "RTL+": "RTLP",
        "RTLP": "RTLP",
        "RUUTU": "RUUTU",
        "SBS": "SBS",
        "Science Channel": "SCI",
        "SeeSo": "SESO",
        "SESO": "SESO",
        "SHMI": "SHMI",
        "SHO": "SHO",
        "Shomi": "SHMI",
        "Showtime": "SHO",
        "SKST": "SKST",
        "SkyShowtime": "SKST",
        "SNET": "SNET",
        "Sony": "SONY",
        "SPIK": "SPIK",
        "Spike TV": "SPKE",
        "Spike": "SPIK",
        "Sportsnet": "SNET",
        "Sprout": "SPRT",
        "SPRT": "SPRT",
        "Stan": "STAN",
        "STAN": "STAN",
        "Star+": "STRP",
        "STARZ": "STARZ",
        "Starz": "STZ",
        "STRP": "STRP",
        "STZ": "STZ",
        "Sveriges Television": "SVT",
        "SVT": "SVT",
        "SwearNet": "SWER",
        "SWEET": "SWEET",
        "SWER": "SWER",
        "Syfy": "SYFY",
        "SYFY": "SYFY",
        "takflix": "TF",
        "Takflix": "TF",
        "TBS": "TBS",
        "TEN": "TEN",
        "TF": "TF",
        "TFou": "TFOU",
        "TFOU": "TFOU",
        "The CW": "CW",
        "The Roku Channel": "ROKU",
        "TIMV": "TIMV",
        "TIMvision": "TIMV",
        "TLC": "TLC",
        "TOU": "TOU",
        "TRVL": "TRVL",
        "TUBI": "TUBI",
        "TubiTV": "TUBI",
        "TV Land": "TVL",
        "TV2": "TV2",
        "TV3 Ireland": "TV3",
        "TV3": "TV3",
        "TV4 Sweeden": "TV4",
        "TV4": "TV4",
        "TVING": "TVING",
        "TVL": "TVL",
        "TVNZ": "TVNZ",
        "UFC Fight Pass": "FP",
        "UFC": "UFC",
        "UKTV": "UKTV",
        "UNIV": "UNIV",
        "Univer Vídeo": "UNVD",
        "Univision": "UNIV",
        "UNVD": "UNVD",
        "USA Network": "USAN",
        "USAN": "USAN",
        "Velocity": "VLCT",
        "VH1": "VH1",
        "VIAP": "VIAP",
        "VICE": "VICE",
        "Viceland": "VICE",
        "Viki": "VIKI",
        "VIMEO": "VIMEO",
        "Vimeo": "VMEO",
        "Vivamax": "VMAX",
        "Vivaone": "VONE",
        "VLCT": "VLCT",
        "VMAX": "VMAX",
        "VMEO": "VMEO",
        "VONE": "VONE",
        "VRV": "VRV",
        "VUDU": "VUDU",
        "W Network": "WNET",
        "WatchMe": "WME",
        "WME": "WME",
        "WNET": "WNET",
        "WOW Presents Plus": "WOWP",
        "WOWP": "WOWP",
        "WWE Network": "WWEN",
        "WWEN": "WWEN",
        "Xbox Video": "XBOX",
        "XBOX": "XBOX",
        "XUMO": "XUMO",
        "Yahoo": "YHOO",
        "YHOO": "YHOO",
        "YouTube Red": "RED",
        "YT": "YT",
        "ZDF": "ZDF",
    }

    if get_services_only:
        return services

    if video is None:
        return "", ""

    guess_data = guessit_fn(video)
    service: str = str(guess_data.get("streaming_service", ""))

    video_name = re.sub(r"[.()]", " ", video.replace(tag or "", "").replace(guess_title or "", ""))
    if audio and "DTS-HD MA" in audio:
        video_name = video_name.replace("DTS-HD.MA.", "").replace("DTS-HD MA ", "")
    title_guess = guessit_fn(video, {"excludes": ["country", "language"]})
    title_guess_title = str(title_guess.get("title", ""))
    for key, value in services.items():
        if ((" " + key + " ") in video_name and key not in title_guess_title) or key == service:
            service = value
    service_longname: str = service
    for key, value in services.items():
        if value == service and len(key) > len(service_longname):
            service_longname = key
    if service_longname == "Amazon Prime":
        service_longname = "Amazon"
    return service, service_longname
