# Upload Assistant © 2025 Audionut & wastaken7 — Licensed under UAPL v1.0
import asyncio
import platform
from pathlib import Path
from typing import Any

import aiofiles
import httpx
from bs4 import BeautifulSoup

from src.console import logger
from src.cookie_auth import CookieAuthUploader, CookieValidator
from src.get_desc import DescriptionBuilder
from src.languages import languages_manager
from src.meta import Meta


class FunFile:
    """
    FF Private Torrent Tracker
    """

    auth_type = "cookies"
    tracker = "FUNFILE"
    display_name = "FunFile"
    banned_groups: tuple[str, ...] = ()
    source_flag = "FunFile"
    base_url = "https://www.funfile.org"
    auth_token = None
    torrent_url = f"{base_url}/details.php?id="
    requests_url = f"{base_url}/requests.php"
    supported_categories = ("TV", "MOVIE")
    tracker_urls = ("tracker.funfile.org",)
    allows_bloated_audio = True

    def __init__(self, config: dict[str, Any]) -> None:
        self.config = config
        self.cookie_validator = CookieValidator(config)
        self.cookie_auth_uploader = CookieAuthUploader(config)
        self.session = httpx.AsyncClient(headers={"User-Agent": f"Upload-Assistant/2.3 ({platform.system()} {platform.release()})"}, timeout=30.0)

    async def validate_credentials(self, meta: Meta) -> bool:
        from src.cookie_auth import find_cookie_file

        cookie_file = find_cookie_file(meta.base_dir, self.tracker, self.config)
        if not Path(cookie_file).exists():
            await self.login(meta)

        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return False
        self.session.cookies = cookie_jar
        return True

    async def validate_cookies(self, meta: Meta) -> bool:
        return await self.cookie_validator.cookie_validation(
            meta=meta,
            tracker=self.tracker,
            test_url=f"{self.base_url}/upload.php",
            success_text="friends.php",
        )

    async def login(self, meta: Meta) -> None:
        login_url = "https://www.funfile.org/takelogin.php"
        from src.cookie_auth import find_cookie_file

        cookie_file = find_cookie_file(meta.base_dir, self.tracker, self.config)

        payload: dict[str, Any] = {
            "returnto": "/index.php",
            "username": self.config["TRACKERS"][self.tracker]["username"],
            "password": self.config["TRACKERS"][self.tracker]["password"],
            "login": "Login",
        }

        logger.info(f"{self.tracker}: Trying to login...", extra={"markup": False})
        response = await self.session.post(login_url, data=payload)

        if response.status_code == 302:
            logger.info(f"{self.tracker}: Login Successful!", extra={"markup": False})

            async with aiofiles.open(cookie_file, "w") as f:
                await f.write("# Netscape HTTP Cookie File\n")
                await f.write("# This file was generated by an automated script.\n\n")
                for cookie in self.session.cookies.jar:
                    domain = cookie.domain
                    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
                    path = cookie.path
                    secure = "TRUE" if cookie.secure else "FALSE"
                    expires = str(cookie.expires) if cookie.expires else "0"
                    name = cookie.name
                    value = cookie.value
                    await f.write(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
            logger.info(f"{self.tracker}: Saving the cookie file...", extra={"markup": False})
        else:
            logger.info(f"{self.tracker}: Login failed. Status code: {response.status_code}", extra={"markup": False})

    async def search_existing(self, meta: Meta) -> list[str]:
        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return []
        self.session.cookies = cookie_jar

        query = meta.title
        if meta.category == "TV":
            query = f"{meta.title} {meta.season}{meta.episode}"

        search_url = f"{self.base_url}/suggest.php?q={query}"
        response = await self.session.get(search_url)

        if response.status_code != 200 or "login" in str(response.url) or "login" in response.text:
            # Try to login and retry
            await self.login(meta)
            response = await self.session.get(search_url)
            response.raise_for_status()
            if "login" in str(response.url) or "login" in response.text:
                await self.cookie_validator.handle_validation_failure(meta, self.tracker, response.text)
                meta.skipping = self.tracker
                return []

        return [line.strip() for line in response.text.splitlines() if line.strip()]

    async def get_requests(self, meta: Meta) -> bool | list[dict[str, str]]:
        if self.config["TRACKERS"][self.tracker].get("check_requests", False) is False:
            return False

        try:
            cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
            if cookie_jar is None:
                return []
            self.session.cookies = cookie_jar
            category = self.get_type_id(meta)

            query_1 = meta.title
            query_2 = meta.title.replace(" ", ".")

            search_url_1 = f"{self.requests_url}?filter=open&category={category}&search={query_1}"

            if query_1 != query_2:
                search_url_2 = f"{self.base_url}/requests.php?filter=open&category={category}&search={query_2}"
                responses = await asyncio.gather(self.session.get(search_url_1), self.session.get(search_url_2))
                response_results_text = responses[0].text + responses[1].text
                responses[0].raise_for_status()
                responses[1].raise_for_status()
            else:
                response = await self.session.get(search_url_1)
                response.raise_for_status()
                response_results_text = response.text

            soup = BeautifulSoup(response_results_text, "html.parser")
            request_rows = soup.select("td.mf_content table tr")

            results: list[dict[str, str]] = []
            for row in request_rows:
                name_element = row.select_one("td.row3 nobr a b")
                if not name_element:
                    continue

                name = name_element.text.strip()
                link_element = name_element.find_parent("a")
                link = str(link_element["href"]) if link_element and link_element.has_attr("href") else ""

                all_tds = row.find_all("td", class_="row3")
                reward = all_tds[2].text.strip() if len(all_tds) > 2 else ""

                results.append({"Name": name, "Link": link, "Reward": reward})

            if results:
                message = f"\n{self.tracker}: [bold yellow]Your upload may fulfill the following request(s), check it out:[/bold yellow]\n\n"
                for r in results:
                    message += f"[bold green]Name:[/bold green] {r['Name']}\n"
                    message += f"[bold green]Reward:[/bold green] {r['Reward']}\n"
                    message += f"[bold green]Link:[/bold green] {r['Link']}\n\n"
                logger.info(message)

            return results

        except Exception as e:
            logger.info(f"{self.tracker}: An error occurred while fetching requests: {e}", extra={"markup": False})
            return []

    async def generate_description(self, meta: Meta) -> str:
        builder = DescriptionBuilder(self.tracker, self.config)
        return await builder.general_description_generator(
            meta,
            bluray=False,
            book=False,
            custom_signature=False,
            game=False,
            nfo=False,
            signature=f"[url=https://github.com/wastaken7/Upload-Assistant][center][size=1]{meta.ua_signature}[/size][/center][/url]",
        )

    def get_type_id(self, meta: Meta) -> str:
        if meta.anime:
            return "44"
        category = meta.category

        if category == "MOVIE":
            return "19"

        if category == "TV":
            return "7"

        return "19"

    def file_information(self, meta: Meta) -> None:
        vc = meta.video_codec
        if vc:
            self.video_codec = vc.strip().lower()

        ve = meta.video_encode
        if ve:
            self.video_encode = ve.strip().lower()

        vs = meta.source
        if vs:
            self.video_source = vs.strip().lower()

        vt = meta.type
        if vt:
            self.video_type = vt.strip().lower()

    def movie_type(self, _meta: Meta) -> str:
        # Possible values: "XviD", "DVDR", "x264", "x265", "MP4", "VCD"
        if self.video_source == "dvd":
            return "DVDR"

        if self.video_codec == "hevc":
            return "x265"
        return "x264"

    def tv_type(self, meta: Meta) -> str:
        # Possible values: "XviD", "HR-XviD", "x264-SD", "x264-HD", "x265-SD", "x265-HD", "Web-SD", "Web-HD", "DVDR", "MP4"
        if self.video_source == "dvd":
            return "DVDR"

        if self.video_source == "web":
            if meta.sd:
                return "Web-SD"
            return "Web-HD"

        if self.video_codec == "hevc":
            if meta.sd:
                return "x265-SD"
            return "x265-HD"
        if meta.sd:
            return "x264-SD"
        return "x264-HD"

    def anime_type(self, meta: Meta) -> str:
        # Possible values: "TVSeries", "TVSpecial", "Movie", "OVA", "ONA", "DVDSpecial"
        if meta.tvmaze_episode_data.get("season_number") == 0:
            return "TVSpecial"

        if self.video_source == "dvd":
            return "DVDSpecial"

        category = meta.category

        if category == "TV":
            return "TVSeries"

        if category == "MOVIE":
            return "Movie"

        return "TVSeries"

    def movie_source(self, _meta: Meta) -> str | None:
        # Possible values: "DVD", "DVDSCR", "Workprint", "TeleCine", "TeleSync", "CAM", "BluRay", "HD-DVD", "HDTV", "R5", "WebRIP"
        mapping = {
            "dvd": "DVD",
            "dvdscr": "DVDSCR",
            "workprint": "Workprint",
            "telecine": "TeleCine",
            "telesync": "TeleSync",
            "cam": "CAM",
            "bluray": "BluRay",
            "blu-ray": "BluRay",
            "hd-dvd": "HD-DVD",
            "hdtv": "HDTV",
            "r5": "R5",
            "web": "WebRIP",
            "webrip": "WebRIP",
        }

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def tv_source(self, _meta: Meta) -> str | None:
        # Possible values: "HDTV", "DSR", "PDTV", "TV", "DVD", "DvdScr", "BluRay", "WebRIP"
        mapping = {
            "hdtv": "HDTV",
            "dsr": "DSR",
            "pdtv": "PDTV",
            "tv": "TV",
            "dvd": "DVD",
            "dvdscr": "DvdScr",
            "bluray": "BluRay",
            "blu-ray": "BluRay",
            "web": "WebRIP",
            "webrip": "WebRIP",
        }

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def anime_source(self, _meta: Meta) -> str | None:
        # Possible values: "DVD", "BluRay", "Anime Series", "HDTV"
        mapping = {"hdtv": "HDTV", "tv": "HDTV", "dvd": "DVD", "bluray": "BluRay", "blu-ray": "BluRay", "web": "Anime Series", "webrip": "Anime Series"}

        src = (self.video_source or "").strip().lower()
        return mapping.get(src)

    def anime_v_dar(self, meta: Meta) -> str:
        # Possible values: "16_9", "4_3"
        if meta.is_disc != "BDMV":
            tracks = meta.mediainfo.get("media", {}).get("track", [])
            for track in tracks:
                if track.get("@type") == "Video":
                    dar_str = track.get("DisplayAspectRatio")
                    if dar_str:
                        try:
                            dar = float(dar_str)
                            return "16_9" if dar > 1.34 else "4_3"
                        except ValueError, TypeError:
                            return "16_9"

            return "16_9"
        return "16_9"

    def anime_v_codec(self, _meta: Meta) -> str:
        # Possible values: "x264", "h264", "XviD", "DivX", "WMV", "VC1"
        if self.video_codec == "vc-1":
            return "VC1"

        if self.video_encode == "h.264":
            return "h264"
        return "x264"

    async def get_name(self, meta: Meta) -> str:
        return (meta.scene_name if meta.scene_name else meta.basename_no_ext.replace(" ", ".")) if meta.scene else meta.clean_name.replace(" ", ".")

    async def languages(self, meta: Meta) -> dict[str, list[str]]:
        if not meta.language_checked:
            await languages_manager.process_desc_language(meta, tracker=self.tracker)

        lang_map = {
            "english": "en",
            "japanese": "jp",
            "korean": "kr",
            "thai": "th",
            "chinese": "zh",
        }

        anime_a_codec: list[str] = []
        anime_a_ch: list[str] = []
        anime_a_lang: list[str] = []

        anime_s_format: list[str] = []
        anime_s_type: list[str] = []
        anime_s_lang: list[str] = []

        audio_languages = meta.audio_languages
        if isinstance(audio_languages, list) and audio_languages:
            audio_desc = meta.audio.lower()
            found_codec = "0"
            codec_options = {
                "aac": "aac",
                "ac3": "ac3",
                "dd": "ac3",
                "dolby digital": "ac3",
                "ogg": "ogg",
                "mp3": "mp3",
                "dts-es": "dtses",
                "dtses": "dtses",
                "dts": "dts",
                "flac": "flac",
                "pcm": "pcm",
                "wma": "wma",
            }
            for key, value in codec_options.items():
                if key in audio_desc:
                    found_codec = value
                    break

            channels_desc = meta.channels
            channel_map = {"2.0": "2", "5.1": "5_1", "7.1": "7_1"}
            found_channel = channel_map.get(channels_desc, "0")

            audio_languages_list = audio_languages
            for lang_str in audio_languages_list:
                lang_code = lang_map.get(str(lang_str).lower(), "1")

                anime_a_codec.append(found_codec)
                anime_a_ch.append(found_channel)
                anime_a_lang.append(lang_code)

        subtitle_languages = meta.subtitle_languages
        if isinstance(subtitle_languages, list) and subtitle_languages:
            subtitle_format = "srt"
            subtitle_type = "sub"

            subtitle_languages_list = subtitle_languages
            for lang_str in subtitle_languages_list:
                lang_code = lang_map.get(str(lang_str).lower(), "1")

                anime_s_format.append(subtitle_format)
                anime_s_type.append(subtitle_type)
                anime_s_lang.append(lang_code)

        return {
            "anime_a_codec": anime_a_codec,
            "anime_a_ch": anime_a_ch,
            "anime_a_lang": anime_a_lang,
            "anime_s_format": anime_s_format,
            "anime_s_type": anime_s_type,
            "anime_s_lang": anime_s_lang,
        }

    async def get_poster(self, meta: Meta) -> tuple[str, bytes, str] | None:
        poster_url = meta.artwork_url

        if poster_url:
            async with httpx.AsyncClient() as client:
                response = await client.get(poster_url)
                if response.status_code == 200:
                    poster_ext = Path(poster_url).suffix or ".jpg"
                    poster_filename = f"{meta.name}{poster_ext}"
                    return (poster_filename, response.content, "image/jpeg")

        return None

    def get_nfo(self, meta: Meta) -> dict[str, tuple[str, Any, str]]:
        nfo_dir = Path(meta.base_dir) / "tmp" / meta.uuid
        nfo_files = list(nfo_dir.glob("*.nfo"))

        if nfo_files:
            nfo_path = nfo_files[0]

            return {"nfo": (nfo_path.name, nfo_path.open("rb"), "application/octet-stream")}
        return {}

    async def get_data(self, meta: Meta) -> dict[str, Any]:
        languages = await self.languages(meta)
        self.file_information(meta)

        data: dict[str, Any] = {
            "MAX_FILE_SIZE": 10000000,
            "type": self.get_type_id(meta),
            "tags": "",
            "descr": await self.generate_description(meta),
        }

        if meta.anime:
            data.update(
                {
                    "anime_type": self.anime_type(meta),
                    "anime_source": self.anime_source(meta),
                    "anime_container": "mkv",
                    "anime_v_res": meta.resolution,
                    "anime_v_dar": self.anime_v_dar(meta),
                    "anime_v_codec": self.anime_v_codec(meta),
                    "anime_a_codec[]": ["0", *languages.get("anime_a_codec", [])],
                    "anime_a_ch[]": ["0", *languages.get("anime_a_ch", [])],
                    "anime_a_lang[]": ["0", *languages.get("anime_a_lang", [])],
                    "anime_s_format[]": ["0", *languages.get("anime_s_format", [])],
                    "anime_s_type[]": ["0", *languages.get("anime_s_type", [])],
                    "anime_s_lang[]": ["0", *languages.get("anime_s_lang", [])],
                }
            )

        else:
            if meta.category == "MOVIE":
                data.update(
                    {
                        "movie_type": self.movie_type(meta),
                        "movie_source": self.movie_source(meta),
                        "movie_imdb": str(meta.imdb_info.get("imdb_url", "")),
                        "pack": 0,
                    }
                )

            if meta.category == "TV":
                data.update(
                    {
                        "tv_type": self.tv_type(meta),
                        "tv_source": self.tv_source(meta),
                        "tv_imdb": str(meta.imdb_info.get("imdb_url", "")),
                        "pack": 1 if meta.tv_pack else 0,
                    }
                )

        return data

    async def upload(self, meta: Meta) -> bool:
        cookie_jar = await self.cookie_validator.load_session_cookies(meta, self.tracker)
        if cookie_jar is None:
            return False
        self.session.cookies = cookie_jar
        data = await self.get_data(meta)
        torrent_name = await self.get_name(meta)
        files: dict[str, Any] = {}
        poster = await self.get_poster(meta)
        if poster:
            files["poster"] = poster
        nfo = self.get_nfo(meta)
        if nfo:
            files["nfo"] = nfo["nfo"]

        return await self.cookie_auth_uploader.handle_upload(
            meta=meta,
            tracker=self.tracker,
            source_flag=self.source_flag,
            torrent_url=self.torrent_url,
            data=data,
            torrent_field_name="file",
            torrent_name=torrent_name,
            upload_cookies=self.session.cookies,
            upload_url=f"{self.base_url}/takeupload.php",
            id_pattern=r"details\.php\?id=(\d+)",
            success_status_code="302",
            additional_files=files,
        )
