name: PR Build Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    if: github.event.issue.pull_request && github.event.comment.user.login == 'Audionut' && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
      pr-number: ${{ steps.pr-info.outputs.pr-number }}
      pr-ref: ${{ steps.pr-info.outputs.pr-ref }}
      pr-sha: ${{ steps.pr-info.outputs.pr-sha }}
      pr-repo: ${{ steps.pr-info.outputs.pr-repo }}
    
    steps:
      - name: Check comment and permissions
        id: check
        run: |
          echo "Comment by: ${{ github.event.comment.user.login }}"
          echo "Comment body: ${{ github.event.comment.body }}"
          echo "should-build=true" >> $GITHUB_OUTPUT

      - name: Get PR information
        id: pr-info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            core.setOutput('pr-number', context.issue.number);
            core.setOutput('pr-ref', pr.data.head.ref);
            core.setOutput('pr-sha', pr.data.head.sha);
            core.setOutput('pr-repo', pr.data.head.repo.full_name);
            
            console.log(`PR #${context.issue.number}: ${pr.data.title}`);
            console.log(`Branch: ${pr.data.head.ref}`);
            console.log(`SHA: ${pr.data.head.sha}`);
            console.log(`Repo: ${pr.data.head.repo.full_name}`);

      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

  trigger-build:
    needs: check-comment
    if: needs.check-comment.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Docker build workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if PR is from a fork
            const prRepo = '${{ needs.check-comment.outputs.pr-repo }}';
            const baseRepo = context.repo.owner + '/' + context.repo.repo;
            const isFromFork = prRepo !== baseRepo;
            
            let ref;
            if (isFromFork) {
              // For forks, we can't dispatch to the fork's branch, so we'll trigger on main/master
              // but pass the PR info so the workflow can checkout the right commit
              console.log(`PR is from fork (${prRepo}), dispatching on default branch`);
              
              // Get the default branch
              const repo = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              ref = repo.data.default_branch;
              console.log(`Using default branch: ${ref}`);
            } else {
              // For same-repo PRs, use the actual branch
              ref = '${{ needs.check-comment.outputs.pr-ref }}';
              console.log(`PR is from same repo, using branch: ${ref}`);
            }
            
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker-image.yml',
              ref: ref,
              inputs: {
                pr_number: '${{ needs.check-comment.outputs.pr-number }}',
                pr_ref: '${{ needs.check-comment.outputs.pr-ref }}',
                pr_sha: '${{ needs.check-comment.outputs.pr-sha }}'
              }
            });
            
            console.log(`Triggered workflow dispatch for PR #${{ needs.check-comment.outputs.pr-number }} on ref: ${ref}`);

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.check-comment.outputs.pr-number }},
              body: '🚀 Docker build triggered for PR #${{ needs.check-comment.outputs.pr-number }}!\n\nCheck the [Actions tab](https://github.com/${{ github.repository }}/actions) for build progress.'
            });